### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by voldikss** [voldikss/vim-floaterm#1]
~- [ ] Give floaterm buffer a unique variable to differentiate from other terminals(if there are multiple terminal buffers...)~
https://github.com/voldikss/vim-floaterm/blob/64bdf5b74349a11d45fde078ac5b066942f4ac80/autoload/floaterm.vim#L126-L139
https://github.com/voldikss/vim-floaterm/blob/64bdf5b74349a11d45fde078ac5b066942f4ac80/autoload/floaterm.vim#L16-L29

**Comment by kdurant** [comment]
可以设置float terminal的默认位置（左上，右上之类），大小

**Comment by voldikss** [comment]
> * [x]  可以设置float terminal的默认位置（左上，右上之类），大小

Done
