### ISSUE TITLE
Dynamic values of g:floaterm_width and g:floaterm_height

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#10]
`g:floaterm_width` and `g:floaterm_height` are constant (integer) expressions, so we cannot have values that are dependent on the window height/width, etc.

One option would be to allow float-type values, or to accept functions.

**Comment by voldikss** [comment]
Hi @wookayin thank you for this suggestion. But I can't understand your idea very clearly... Could you be more specific? e.g. Why window height/width must be float type instead of integer type? I ever thought that they could only be integer type...

**Comment by wookayin** [comment]
Let me clarify a bit more. Their default values are the number of columns and rows, but these value are determined at the point when the script is being executed.

```
let g:floaterm_width = get(g:, 'floaterm_width', &columns)
let g:floaterm_height = get(g:, 'floaterm_height', winheight(0)/2)
```

That said, even if you resize your terminal, they would remain in old values. For example, if you launch vim with a very small size and maximize the window --- the floating window will be still small. I think those value needs to be determined at runtime.

**Comment by voldikss** [comment]
Thanks, I got it.

**Comment by wookayin** [comment]
After the change, the floating window does not get placed in the center.

**Comment by voldikss** [comment]
> After the change, the floating window does not get placed in the center.

I can not reproduced this issue, 'center' works normally on my laptop. Did you set `g:floaterm_position` option to `'center'`?

**Comment by wookayin** [comment]
That works. But then it the default option for g:floaterm_position should be 'center'.

Also, it appears that width is only respect to the current window (not the entire vim window).

![image](https://user-images.githubusercontent.com/1009873/67135051-bcdd4a00-f1e3-11e9-97f6-67f8a6523733.png)

**Comment by voldikss** [comment]
The issue was fixed. Thanks!

**Comment by voldikss** [comment]
BTW, could you share your colorscheme? Looks good

**Comment by wookayin** [comment]
I see. The `auto` default makes a sense to me (though I prefer to put it center, which I can configure on my own).

BTW my colorscheme is based on xoria256 with some slight modifications. You can see my full vimrc at https://github.com/wookayin/dotfiles/tree/master/vim.

**Comment by wookayin** [comment]
A quick comment -- in case `g:floaterm_position' not equals auto (cursor relative), the relative option should be 'editor' rather than 'win'.

**Comment by voldikss** [comment]
Thanks, fixed now
