### ISSUE TITLE
Run a floaterm window with a $SHELL running that would autoclose without altering `g:floaterm_autoclose`(only for the current one).

### ISSUE THREAD

**Issue by voldikss** [voldikss/vim-floaterm#100]
Thanks @voldikss. I also agree that Option 2 is the best and most reasonable choice. For having the original behavior (i.e., sendkeys), I end up using a custom command to sendkeys myself: https://github.com/wookayin/dotfiles/commit/edfc2e0b3a0c6b69744438294ade32189ed8fe51

I would also need a configuration point so that one can run a floaterm window with a $SHELL running that would autoclose (**only for the current one**) without altering `g:floaterm_autoclose`. This is similar to Option 3, but I don't think your original API proposal -- adding a new argument --- is a good idea.

Some suggestions:
- (1) we can maybe have it in `winopts` (but this is technically not a "window" opts)?
- (2) Or how about using bang, e.g. `FloatermNew!` ?
- (3) Floaterm already takes options (e.g. `FloatermNew height=0.6 width=0.4 ...`) so we can add the option here. Like `:FloatermNew -i`).  
  - As a side note, I think `height`, `width`, etc. should also have been prefixed with `-`, because you cannot discriminate with running commands with overriding environment variables, `e.g. :FloatermNew HEIGHT=0.6 ./some_command.sh`. That's potentially yet another breaking change.

My personal preference is (3) but would love to discuss more about what'd be the best way.

_Originally posted by @wookayin in https://github.com/voldikss/vim-floaterm/issues/98#issuecomment-616198003_

**Comment by voldikss** [comment]
> I would also need a configuration point so that one can run a floaterm window with a $SHELL running that would autoclose (only for the current one) without altering g:floaterm_autoclose

So you mean we should add 2 configuration points to a specific floaterm locally: one is "run that program in a `$SHELL`", the other is "autoclose the floaterm window once the job gets finished(suppose `g:floaterm_autoclose` option has been set to `v:false`)". Am I right?

**Comment by voldikss** [comment]
Firstly I considered adding `autoclose` field to `winopts` and `shell` field to `jobopts`. That is to say we can run `FloatermNew` like `:FloatermNew autoclose=1 shell=1 some_command`. But I prefer not to pollute `jobopts` option, which should only be reserved for `termopen()` or `term_start()`. So I think for "running a program in $SHELL", your option 2 is the best choice. 

However, if I add a `<bang>` to `FloatermNew`, then a `bang` argument has to be added to function `floaterm#new` --- back to my option3 in #98... 

```diff
- function! floaterm#new(cmd, winopts, jobopts) abort
+ function! floaterm#new(cmd, winopts, jobopts, bang) abort
```

**Comment by voldikss** [comment]
> because you cannot discriminate with running commands with overriding environment variables, e.g. `:FloatermNew HEIGHT=0.6 ./some_command.sh`

Sorry I don't understand it, do you mean there maybe a variable `HEIGHT` so that when we use tab to get cmdline argument completion, users will choose `HEIGHT` field from completion candidates by accident?

**Comment by wookayin** [comment]
> So you mean we should add 2 configuration points to a specific floaterm locally: one is "run that program in a $SHELL", the other is "autoclose the floaterm window once the job gets finished(suppose g:floaterm_autoclose option has been set to v:false)". Am I right?

Exactly. The first one is something one can implement very easily (`:FloatermNew` + `:FloatermSend`) so whether you'd want include as a feature of vim-floaterm is your call.

For the second one, this is something that vim-floaterm should support.

> However, if I add a <bang> to FloatermNew, then a bang argument has to be added to function floaterm#new --- back to my option3 in #98...

I think bang is specific to `:command` and the vimfunction API itself should have different argument name (but an *optional* argument) or even having it as a part of winopts. My hunch is that if you rename `winopts` as `opts` then it could include `autoclose`.

**Comment by wookayin** [comment]
> Sorry I don't understand it, do you mean there maybe a variable HEIGHT so that when we use tab to get cmdline argument completion, users will choose HEIGHT field from completion candidates by accident?

Regarding the third question, this was a hypothetical example. A valid shell command **may start with** `ENVVAR=value CMD...`, but vim-floaterm simply ignores `ENVVAR=value ...` part treating them as vim-floaterm's option. For example,

* `:FloatermNew TERM=xterm bash -c 'echo $TERM'` executes `bash -c 'echo $TERM'` (note the stripped `TERM=...` part)
* `:terminal TERM=xterm bash -c 'echo $TERM'` executes `TERM=xterm bash -c 'echo $TERM'`

And the latter should be the right behavior. I think this would be a small design miss introduced when winopts parsers were implemented.

**Comment by voldikss** [comment]
> > Sorry I don't understand it, do you mean there maybe a variable HEIGHT so that when we use tab to get cmdline argument completion, users will choose HEIGHT field from completion candidates by accident?
> 
> Regarding the third question, that was a hypothetical example. Let me give a better example here.
> 
> A valid shell command **may start with** `ENVVAR=value CMD...`, but vim-floaterm simply ignores `ENVVAR=value ...` part treating them as vim-floaterm's option. For example,
> 
> * `:FloatermNew TERM=xterm bash -c 'echo $TERM'` executes `bash -c 'echo $TERM'` (note the stripped `TERM=...` part)
> * `:terminal TERM=xterm bash -c 'echo $TERM'` executes `TERM=xterm bash -c 'echo $TERM'`
> 
> And the latter should be the right behavior. I think this would be a small design miss introduced when winopts parsers were implemented.

Thanks for the explaintion, I got it.

**Comment by wookayin** [comment]
Actually I think this is a separate issue, so I have created a new issue #101. In this thread let's discuss only about autoclosing.

**Comment by voldikss** [comment]
> My hunch is that if you rename winopts as opts then it could include autoclose

Nice idea. Besides, since `autoclose` is just a bool option, I will just add it as `--autoclose` instead of `--autoclose=1`. 

Things get clearer now. I will implement this and another one mentioned in #101 when I have spare time.

**Comment by voldikss** [comment]
In additon, about "running a program in a shell". Should we use `:FloatermNew!` or `:FloatermNew ...  --shell`?

**Comment by wookayin** [comment]
Such a decision is hard. The meaning of bang modifier is different across commands so it'd be our decision, taking whether other use cases (e.g. force action, etc.) would exist or not into consideration, for the sake of potential backward compatibility. My personal opinion is that it would be okay, but I am not 100% sure; it might be also a good idea to hear other people's opinion.

Even if we are implementing as the latter, I think `:FloatermUpdate` could simply reject the option. Actually I think there would be no loss if we had `--shell` (or `--interactive`). Or we can do even shorter: **`-i`**: I am supportive of this because this is analogous to `bash -i`, `python -i`, `docker -i`, etc.

**Comment by voldikss** [comment]
> I think `:FloatermUpdate` could simply reject the unexpected option.

Yes it does. I just want to keep the arguments between `:FloatermNew` and `:FloatermUpdate` to be unified.

> Or we can do even shorter: -i: I am supportive of this because this is analogous to bash -i, python -i, docker -i, etc.

That's a good idea. However, I like keeping GNU arguments style for all options. And hmmmm I still prefer `:FloatermNew!` than `:FloatermNew --interactive` which is explained above. I feel that `<bang>` feature is exactly exists for this `in shell` option :joy: 

Anyway, thanks again for your suggestions above!

**Comment by wookayin** [comment]
Great, and it works well.

One small suggestion: you could've not broken the API compatibility by making `bang` and `shell` as an optional argument. And I think it makes a lot of sense because it is consistent with the default behavior of the vim commands.
