### ISSUE TITLE
Ranger opens file in the floating window

### ISSUE THREAD

**Issue by bigardone** [voldikss/vim-floaterm#102]
### Describe the bug

After updating the plugin, when I run `:FloatermNew ranger` and select a file, the file opens in Floaterm's window instead of in the main one.

### To Reproduce

- Use the minimal vimrc

  ```vim
  set nocompatible
  set hidden
  set termguicolors
  set runtimepath^=/path/to/vim-floaterm
  filetype plugin indent on
  syntax on
  ```

- Steps to reproduce the behavior:
  1. Run `:FloatermNew ranger`
  2. Choose a file.

### Enviroment
 - OS [e.g. Arch Linux]: macOS Catalina
 - Version [e.g. NVIM v0.5.0-fa9b057]: NVIM v0.5.0-96059d7
 - Checkhealth info [run `:checkhealth` and post the messages]:

```
health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - ERROR: nvr executable is not found, run `pip install neovim-remote` to install
```

### Screenshots(Optional, GIF is better)

![http://g.recordit.co/Dzu0mM9G7X.gif](http://g.recordit.co/Dzu0mM9G7X.gif)

**Comment by voldikss** [comment]
Fixed, thanks!

**Comment by bigardone** [comment]
Working like a charm now, thanks! 🎉
