### ISSUE TITLE
g:floaterm_autoclose=v:true is not working after today's commit

### ISSUE THREAD

**Issue by kazhala** [voldikss/vim-floaterm#103]
Make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

### Describe the bug
I've noticed that g:floaterm_autoclose was recently added to floaterm. I personally like it to be auto closed so I've added g:floaterm_autoclose=v:true this morning and it was working fine. However, I don't think the variable is now being interpreted after the update "allow autoclose as a command-line option" (I'm not entirely sure exactly which commits, but somewhere around there), as now even with the variable set, I still get the exit number.

### To Reproduce

- Steps to reproduce the behavior:
  1. add g:floaterm_autoclose=v:true to vimrc
  2. FloatermNew
  3. exit floaterm

### Enviroment
 - OS [e.g. Arch Linux]: macOS
 - Version [e.g. NVIM v0.5.0-fa9b057]: NVIM v0.4.3
 - Checkhealth info [run `:checkhealth` and post the messages]:
```markdown
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - OK: nvr is OK
```

### Screenshots(Optional, GIF is better)
![Screen Recording 2020-04-21 at 21 32 59](https://user-images.githubusercontent.com/43941510/79861838-66fa9080-8418-11ea-9cf9-7d57a6b7d087.gif)

**Comment by voldikss** [comment]
Fixed, thanks!
