### ISSUE TITLE
:FloatermNew --name and :FloatermSend does not work 

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#104]
Some bugs around #100.

## :FloatermNew

Try:

```
:FloatermNew --name hello zsh 
```

Result:

```
zsh:1: command not found: hello    
                                   
[Process exited 127]               
```

## :FloatermSend

```
FloatermSend hello bash -c 'exit'  
```

result:

```
[vim-floaterm] No floaterm found with name: hello bash -c 'exit' 
```

**Comment by wookayin** [comment]
They should be easy fixes but let me fire a bug instead of PR as you can work faster than me. I'd recommend you maintain a test if you have extra free cycle or  use a PR-based workflow (rather than closing it via commits) so that people can review if you are writing big changes. Thanks!

**Comment by voldikss** [comment]
> Some bugs around #100.
> 
> ## :FloatermNew
> Try:
> 
> ```
> :FloatermNew --name hello zsh 
> ```
> 
> Result:
> 
> ```
> zsh:1: command not found: hello    
>                                    
> [Process exited 127]               
> ```
> 
> ## :FloatermSend
> ```
> FloatermSend hello bash -c 'exit'  
> ```
> 
> result:
> 
> ```
> [vim-floaterm] No floaterm found with name: hello bash -c 'exit' 
> ```

This plugin only accetps arguments formed as `--key[=value]`. So you should must `--name=hello zsh`.

**Comment by voldikss** [comment]
> use a PR-based workflow (rather than closing it via commits) so that people can review when writing big changes

Got it. Will make a PR next time when there are big changes.

**Comment by wookayin** [comment]
> This plugin only accetps arguments formed as `--key[=value]`. So you should must `--name=hello zsh`.

Well, but then the current error message is very misleading. It is fine to accept `--name` arguments but `:FloatermSend <name> <cmd>` should be supported and that's a very natural way of defining this command.

**Comment by voldikss** [comment]
> Well, but then the current error message is very misleading.

It's hard to check the validity of input but to tell them arguments format in doc.

**Comment by voldikss** [comment]
I've made a PR for this. #105

**Comment by wookayin** [comment]
> It's hard to check the validity of input but to manifest arguments format in doc.

I see, so if name is not given the whole argument should be sent as a commandline (to the current floaterm). Makes a lot of sense! Yeah, I'm now convinced that `--name` should be given.

**Comment by wookayin** [comment]
Thanks @voldikss for #105 and kindly considering my suggestions. However, I think you still have missed `:FloatermNew` part -- it doesn't work.

**Comment by voldikss** [comment]
> I think you still have missed :FloatermNew --name part -- it doesn't work yet.

How did you use it? `:FloatermNew --name=hello` works for me.

**Comment by wookayin** [comment]
Exactly as described in this issue.

```
:FloatermNew --name hello zsh 
:FloatermNew --name py bash
```

**Comment by voldikss** [comment]
This plugin only accetps arguments formed as --key[=value]. So you should use `--name=hello zsh`.

**Comment by wookayin** [comment]
Oh I see, yeah, that's my mistake. Sorry about that! Works well for me.

**Comment by wookayin** [comment]
It would be great as well to have a foolproof warning/error message though, if `--name` is given but `=value` does not follow.

**Comment by voldikss** [comment]
> It would be great as well to have a foolproof warning/error message though, if --name is given but =value does not follow.

It is a nice idea. However, it's hard to implement that as it will make the code a little clumsy. So I just noted the argument format in the doc.
