### ISSUE TITLE
After FloatermSend, the current buffer enters the insert mode

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#106]
After `:FloatermSend` (or `floaterm#terminal#send`), the current window/buffer enters the insert mode. I took a look at `floaterm#terminal#send` but found no line that seems to enter the insert mode, hence this bug report.

One more side bug report: `floaterm#terminal#send(buf, [])` (empty cmds) does not handle the exception.

**Comment by wookayin** [comment]
Hmm, I figured out these three lines are the culprit:

https://github.com/voldikss/vim-floaterm/blob/97f2d566fa4fe023cee7e2ba541ec851b046c789/autoload/floaterm/terminal.vim#L166-L169

When we enter the terminal window through `<winnr>wincmd w`, it enters the insert mode. This is because I have some autoinsert autocmd (which many people would have):

```vim                                                               
autocmd BufWinEnter,WinEnter *  if &buftype == 'terminal' | startinsert | endif
```

But `startinsert` gets executed *after* getting back to the current window. This is weird -- might be a bug of neovim (because autocmd events are supposed to be fired on the buffer itself and in a synchronous fashion). Let me think about a workaround about how to make the window scroll to the end without entering.

**Comment by wookayin** [comment]
The following patch works for me:

```patch
   if ch_winnr > 0
-    execute ch_winnr . 'wincmd w'   
-    execute 'normal! G'
+    noautocmd execute ch_winnr . 'wincmd w'   
+    noautocmd execute 'normal! G'
   endif
-   execute curr_winnr . 'wincmd w'
+   noautocmd execute curr_winnr . 'wincmd w'
```

This disables autocmd to be fired, but not sure this is the *right* way to solve the problem.

**Comment by voldikss** [comment]
Thanks, I'll fix this using the patch.

**Comment by wookayin** [comment]
Thanks for the quick follow-up!
