### ISSUE TITLE
Feature request: FloatermShow, FloatermHide

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#109]
### `:FloatermShow <name>`

- Should bring up an existing floaterm window by name. If not exists, should be an error.
- A vimfunction counterpart could be also added.
- We can factor out some lines out of `floaterm#toggle`.

### `:FloatermHide <name>`

- Currently, `:FloatermHide` hides all floaterm windows. It cannot take additional arguments.
   - NOTE: The command and `floaterm#hide()` should have the argument optional, e.g. calling without any argument would hide all.
- I want to have specific window hidden, with all other floaterm windows kept intact.
- It is possible to get `bufnr` by name and call `floaterm#window#hide_floaterm` manually, but it's somewhat inconvenient.

**Comment by wookayin** [comment]
Thanks for the update.

As I noted, you should have made vim function take an optional argument (i.e. use `...` and `a:0`, `a:000`, etc.). With the current change, `floaterm#hide()` will lead to an error. Please avoid breaking changes function signatures as much as possible.

**Comment by voldikss** [comment]
Sorry I didn't noticed that. Regret for my carelessness.

I would like `:FloatermHide` and `:FloatermShow` behavior like `:FloatermKill` --- if no arguments, hide/show/kill the current floaterm. For hiding all floaterm windows, a new command like `:FloatermHideAll` might be a better choice. However, I don't like this prolix name...

**Comment by voldikss** [comment]
> floaterm#hide() will lead to an error.

It shouldn't lead to an error. Just changed the behavior: hiding all floaterm windows --> hiding current one.

**Comment by wookayin** [comment]
@voldikss Thank you! Yes, I agree that `:FloatermHide` (without arguments) might mean hide the current or hide'em all, it can be confusing. The behavior seems to have changed, but I think this consistency is reasonable.
