### ISSUE TITLE
Can't update with dein

### ISSUE THREAD

**Issue by glepnir** [voldikss/vim-floaterm#110]
Make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

### Describe the bug
use dein update plugins
```
[dein] /Users/stephen/.cache/vim/dein/repos/github.com/voldikss/vim-floaterm
[dein] fatal: Not possible to fast-forward, aborting
```
### To Reproduce

- Steps to reproduce the behavior:

### Enviroment
 - OS [e.g. Arch Linux]: macos
 - Version [e.g. NVIM v0.5.0-fa9b057]:NVIM 0.5.0-nightly
 - Checkhealth info [run `:checkhealth` and post the messages]:
```
health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - OK: nvr is OK

```

**Comment by voldikss** [comment]
It might be caused by some rebased commits. Try removing and reinstalling this plugin.
