### ISSUE TITLE
Weird padding on neovim

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#112]
Commit 5ee45c3dc added a padding for neovim in the left side of the floaterm. But I personally don't like this -- I just want to have no padding of one column. Can we make it confugrable?

Also, there is a subtle difference (see the rightmost column); foldcolumn only brings a padding to the left, not to the right.

vim8

![image](https://user-images.githubusercontent.com/1009873/80927807-30484280-8d55-11ea-8b09-c38ebc70eb63.png)

neovim

![image](https://user-images.githubusercontent.com/1009873/80927816-3e965e80-8d55-11ea-917e-c3d75afcfc09.png)

**Comment by wookayin** [comment]
I think the right way to implement this is tweaking on `s:floatwin_pos`, not changing the foldcolumn.

**Comment by voldikss** [comment]
> Also, there is a subtle difference (see the rightmost column); foldcolumn only brings a padding to the left, not to the right.

Thanks, I just reverted that commit. 

> Can we make it confugrable?

For the configuration, I would like to wait for the builtin implementation of border in neovim.

**Comment by wookayin** [comment]
Thanks for your updates. I agree manually drawing border is annoying. Though it might be possible to carefully adjust the width of the inner window so that we can have paddings on both side, but we may not want to bother ourselves implementing that.

**Comment by voldikss** [comment]
> Though it might be possible to carefully adjust the width of the inner window so that we can have paddings on both side, but we may not want to bother ourselves implementing that.

Yes. 

Besides, there is another concern: the only solution for now is to tweak the relative position and size of the border window to add that border. In that case, the padding part is actually made by the border window. Therefore, if one have set `hi FloatermBorder`, the padding would be colorized.

Based on those concerns, I think it's a better choice to wait for the builtin implementation for the border feature.
