### ISSUE TITLE
[Feature]: Add LeaderF support

### ISSUE THREAD

**Issue by cossonleo** [voldikss/vim-floaterm#113]
大佬的这个插件非常好用，已经成为我的日常使用插件。
希望能够添加[LeaderF](https://github.com/Yggdroot/LeaderF)的支持

-----------------

Hope to see the builtin support for Leaderf.

**Comment by voldikss** [comment]
可以参考这里，
https://github.com/voldikss/vim-floaterm/wiki/Integration-with-other-fuzzy-finder

**Comment by voldikss** [comment]
其他模糊搜索功能暂时没考虑加入到插件里面去，所以先关闭这个 issue 了。

--------

No plan for adding builtin support for other fuzzy finders. So let me close this issue for now.
