### ISSUE TITLE
Add an option to change the shell

### ISSUE THREAD

**Issue by maxfl** [voldikss/vim-floaterm#114]
I propose to add an explicit option to change the shell that is used for floaterm since changing the 'shell' option is not always possible.

The floaterm documentation suggests to change the 'shell' vim option which is not suitable for a reason. Some of the non-interactive plugins rely on the bash compatibility of the shell. In case 'fish' is used as interactive shell, the best practice is typically to avoid using it as a shell, which is usually done with the following code in init.vim:
```vim
if &shell =~# 'fish$'
    set shell=/bin/bash
endif
```

**Comment by voldikss** [comment]
Hi, thanks for the suggestion!

But I can not understand the situation you described, could you provide an example?

**Comment by maxfl** [comment]
`fish` is not compatible with bash. You may try running the following code in vim:
```vim
set shell=bash
!test=2; echo $test
set shell=fish
!test=3; echo $test
```

Here is the output of the fish test:
```
fish: Unsupported use of '='. In fish, please use 'set test 3'.
```

I'm using `fish` as an interactive shell since it is very user-friendly. In the same time I would like to make sure that the shell that is used to run commands is `bash`. So the `shell` option in vim has to be set to `bash`, but in `floaterm` I would like to use `fish`.

**Comment by voldikss** [comment]
Thanks for the explaination, that's reasonable. I am going to add an option `g:floaterm_shell` soon

**Comment by maxfl** [comment]
Thank you!
