### ISSUE TITLE
Incorrect rescaling

### ISSUE THREAD

**Issue by uhlajs** [voldikss/vim-floaterm#115]
The floating term does not rescale with respect to current &columns. Rather it keeps the size of the original (value when was the first terminal opened).

Configuration:

```
" Floaterm {{{
Plug 'voldikss/vim-floaterm'

""" Example configuration
let g:floaterm_type = 'floating'
let g:floaterm_position = 'center'
let g:floaterm_width = 0.9
let g:floaterm_height = 0.85
let g:floaterm_keymap_new    = '<F5>'
let g:floaterm_keymap_prev   = '<F6>'
let g:floaterm_keymap_next   = '<F7>'
let g:floaterm_keymap_toggle = '<F8>'
```

First monitor with low resolution:

![2020-05-07-111812_screenshot](https://user-images.githubusercontent.com/13243167/81277439-b796fe00-9054-11ea-8382-c67a55eb0286.png)

Second monitor with high resolution: (after reopening floating term == 2x `:FloatermToggle`)
![2020-05-07-111903_screenshot](https://user-images.githubusercontent.com/13243167/81277460-c087cf80-9054-11ea-9e84-1bb7e7afccde.png)

**Comment by voldikss** [comment]
Thanks, fixed

**Comment by uhlajs** [comment]
Thanks for the quick fix. Also, I have a question, how hard it would be to rerender the floating window on &column change? After this fixed one needs to toggle window to rerender window. It could be automatic, but I guess that this is more related to neovim floating window implementation, isn't it?

**Comment by voldikss** [comment]
> After this fixed one needs to toggle window to rerender window

Actually this is mainly because it make coding easier --- Just update the winopts, hide that window and reopen(still use that open function) it, then the window size will be updated. Otherwise I have to write another function to update the window.
