### ISSUE TITLE
[[Feature request]] scroll the terminal

### ISSUE THREAD

**Issue by yassinebridi** [voldikss/vim-floaterm#116]
Sometimes you get a very long output from a command,
so it would be pretty useful to be able to scroll the terminal.

**Comment by voldikss** [comment]
Could you explain more specific why should we need this?

> so it would be pretty useful to be able to scroll the terminal.

Why not just press `G` to jump to the bottom?

**Comment by yassinebridi** [comment]
Well you can't predict where a useful information might be in a long compiling error output for example,
especially when you have a small floaterm dimensions. You want to be able to scroll through the terminal. The important information might be in the top or middle or bottom.

**Comment by voldikss** [comment]
Hmmm, that doesn't make sense. Why not we just move the cursor using `j`,
`k`, `<C-d>` etc.?

Yassine Bridi <notifications@github.com> 于 2020年5月20日周三 下午7:07写道：

**Comment by yassinebridi** [comment]
That would be lovely, but i can't do that, since the terminal gives
```
[Process exited 0]
```
and exits at any keyboard input i give.

**Comment by voldikss** [comment]
> the terminal gives
[Process exited 0]
and exits at any keyboard input i give

Go to the normal mode using c-\ c-n

Yassine Bridi <notifications@github.com> 于 2020年5月20日周三 下午7:31写道：

**Comment by yassinebridi** [comment]
It worked, thanks @voldikss for the help.

**Comment by wanghuibin0** [comment]
I want to change the key binding of going to the normal mode, since "C-\" is captured by my system to toggle my input method. 
Is this possible?

**Comment by voldikss** [comment]
@wanghuibin0 yes

**Comment by kryptoblack** [comment]
How can I go out of normal mode to type commands again without toggling the terminal off and on again?

**Comment by kryptoblack** [comment]
never mind, just had to press `i` to go into insert mode

**Comment by TouchDeeper** [comment]
I used \tt to open the terminal, but I'm unable to scroll through the terminal output. How can I scroll through the output in the activated terminal?
