### ISSUE TITLE
floaterm did not disappear after running exit in the terminal

### ISSUE THREAD

**Issue by laoshaw** [voldikss/vim-floaterm#117]
Ubuntu 18.04 with vim 8.2, newest vim-floaterm. Use the minimal vimrc.

Type: `:FloatermNew`, a new bash term opens as expected, type `exit` it outputs "exit" below the cursor and the window still floats, it did not disappear.

**Comment by voldikss** [comment]
see https://github.com/voldikss/vim-floaterm#gfloaterm_autoclose

**Comment by Denovocto** [comment]
Having The same issue as @laoshaw. I did `let g:floaterm_autoclose = 2` to no avail. Tried to Invoke FloatermNew as `:FloatermNew --autoclose=2` and still it doesn't close when process ends.

**Comment by lixiaoquan** [comment]
I run into the same issue, after `exit` in term, I have to use :q to quit the term.  

I am using vim tag v8.2.0286

**Comment by voldikss** [comment]
@lixiaoquan thanks for the report. However, now that upgrading vim resolves the problem, I think it’s unnecessary to spend a lot of time on it.
