### ISSUE TITLE
Send buffer to floaterm

### ISSUE THREAD

**Issue by ichbean** [voldikss/vim-floaterm#118]
Am I missing something or have wrong expectations from this plugin, but how do I send the whole buffer with a single command?
What I'm looking for is `:term python %` but in a floating window.

**Comment by voldikss** [comment]
```vim
:FloatermNew python
:%FloatermSend
```

**Comment by ichbean** [comment]
Thanks, I've seen that in the readme, but is there a way to do that with a **single** command so I can bind it to a key?

**Comment by voldikss** [comment]
No plan for this since it will cause arguments ambiguity.
