### ISSUE TITLE
feature request: one floaterm instance per tab

### ISSUE THREAD

**Issue by yazgoo** [voldikss/vim-floaterm#119]
Thanks for this project,

To ease my workflow, I'd like to have the option to have a different floaterm instance for each tab instead of only one shared instance.

**Comment by voldikss** [comment]
Sorry but this seems impossible. A floaterm instance has to be globally shared. There are no easy ways to make it tab independent.

**Comment by yazgoo** [comment]
Would you accept a PR if I was to give it a try ?

**Comment by voldikss** [comment]
Sorry I am not quite certain about this actually. I worry that this feature would make the whole logic difficult to control. 

But if you want to make some changes to meet your requirement, would you please allow me to have a look?
