### ISSUE TITLE
[Feature Request] add multi term instance support

### ISSUE THREAD

**Issue by Shuumatsu** [voldikss/vim-floaterm#12]
For now, there can only be one terminal instance. I'm not sure if it's possible, but I'd like to be able to open multi terminals as I do in VSCode.

**Comment by voldikss** [comment]
Hi Shuumatsu  It's possible actually, but I can not see any necessities to support that feature.

**Comment by voldikss** [comment]
（Sorry 洋文水平有点渣就用中文了）
我觉得这个工具用起来比较方便的地方就是一键切换，如果是多个窗口的话我觉得会不方便管理。

**Comment by Shuumatsu** [comment]
就是有时候需要跑几个服务 并且有时候会切过去看输出 如果放在后台的话更不方便吧

最简单的弄这里可以就加个快捷键切到下一个终端  到最后一个就循环到第一个 反正一般也不会太多个

**Comment by voldikss** [comment]
加上了
