### ISSUE TITLE
Unable hide or toggle the first floaterm

### ISSUE THREAD

**Issue by Martins3** [voldikss/vim-floaterm#121]
- [x] Please make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

- [x] Please make sure you are using the latest version of the plugin.

- [x] Please use English as far as possible.

### Describe the bug

> #### `:FloatermHide [floaterm_name]` Hide the current floaterms window.
> 
> - If `floaterm_name` exists, hide the floaterm named `floaterm_name`.
> #### `:FloatermToggle [floaterm_name]` Open or hide the floaterm window.
> 
> - If `floaterm_name` exists, toggle the floaterm instance whose `name` attribute is `floaterm_name`.
> - Use `<TAB>` to get completion.

By default, FloatermHide and FloatermToggle will hide current floaterm window, but "current" is vague.
If two floaterms are created continually,and switch to the first one, the none of them can be hidden with FloatermHide or FloatermToggle

My suggestion is that maybe we can add a option to hide/toggle **all** floaterms.

### To Reproduce

- Use the minimal vimrc
```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/home/shen/.cache/vimfiles/repos/github.com/voldikss/vim-floaterm
filetype plugin indent on
syntax on
```

- Steps to reproduce the behavior:
  1. vim -u minivimrc
  2. FloatermNew
  3. FloatermNew
  4. FloatermPrev
  5. FloatermHide # unable to hide to window
  6. FloatermToggle # unable to hide to window

### Enviroment
 - OS [Manjaro Linux x86_64]:
 - Version [NVIM v0.4.3]:
 - Checkhealth info [run `:checkhealth` and post the messages]:
```
health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - OK: nvr is OK

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6002'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python version: 2.7.18
  - INFO: pynvim version: 0.3.2 (outdated; from /usr/lib/python2.7/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.2
  - INFO: pynvim version: 0.4.0 (outdated; from /usr/lib/python3.8/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
  - INFO: Host: /home/shen/.gem/ruby/2.6.0/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v14.1.0
  - INFO: Neovim node.js host: /home/shen/.Application/i386elfgcc/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0
```

**Comment by voldikss** [comment]
Thanks for the bug report and suggestion.

> By default, FloatermHide and FloatermToggle will hide current floaterm window, but "current" is vague.
If two floaterms are created continually,and switch to the first one, the none of them can be hidden with FloatermHide or FloatermToggle

Reproduced that issue. I'll fix it when I have spare time.

> My suggestion is that maybe we can add a option to hide/toggle all floaterms.

I am not sure whether it's a strong requirement. But I don't like the name `Floaterm****All`. How about adding an option `g:floaterm_hide_before_open`(another bad name indeed) which hides the previous floaterms before opening a new one? Therefore, there is only one floaterm in the front end all through and it could hide the current floaterm successfully.

**Comment by Martins3** [comment]
Why the default action of `FloatermHide` is hiding "current" floterm? If I want to hide the floaterm,it means I want to edit in vim,so hidding all the floaterms is what I need.In my perspective, the candidate being hidden should be "all" instead of "current".

This's my typical work flow:
1. edit in vim
2. `FloatermToggle` to execute a shell command: e.g. a time consuming `make`.
3. `FloatermNew` to execute another shell command: e.g. `htop` to monitor the cpu usage.
4. hide all floterm so I can edit in vim again. 

What about adding a command `FloatermToggle!` ?
1. hide all the floaterms if anyone is not hidden.
2. show all the floaterms if everyone is hidden.

**Comment by voldikss** [comment]
> Why the default action of FloatermHide is hiding "current" floterm? 

It comes from this issue: https://github.com/voldikss/vim-floaterm/issues/109#issuecomment-619799561

> What about adding a command FloatermToggle! ?

That's reasonable. I'll try adding it.

Thanks for the suggestion.
