### ISSUE TITLE
Dynamic Floatterm width based on overall editor width 

### ISSUE THREAD

**Issue by martinklepsch** [voldikss/vim-floaterm#123]
Hi! I love to use `lazygit` via floatterm but sometimes I run into the issue that the terminal window is relatively small and more complex CLI apps don't render as well: 

<img width="762" alt="Screen Shot 2020-05-30 at 22 49 47" src="https://user-images.githubusercontent.com/97496/83338804-0fc5c680-a2c8-11ea-9955-844296d250ef.png">

I was wondering if there could be an option akin to a breakpoint in CSS that allows users to say "use the full width if my terminal is narrower than N characters". That way people could use use floatterm in almost fullscreen mode on a laptop but without blowing things up overly when connecting to a larger external screen.

**Comment by voldikss** [comment]
You can use `:FloatermUpdate --width=0.9 --height=0.9` or make it a shortcut.

**Comment by martinklepsch** [comment]
Cool that's a good pointer. I'm still thinking it might be a nice feature to have built in. With `:FloatermUpdate` I still need to look up the window width and hook into resize events etc. I'll try to update this issue once I figured out how to do that.

**Comment by voldikss** [comment]
It's not that difficult. You can also make a mapping like 

```vim
nmap some_key :FloatermUpdate --width=0.9 --height=0.9 lazygit
```

**Comment by martinklepsch** [comment]
Ok, this is what I came up with:
```vimscript
function LazyGit()
	if (&columns > 180)
		execute 'FloatermNew lazygit'
	else
		execute 'FloatermNew --width=0.9 --height=0.9 lazygit'
	endif
endfunction

nmap <Leader>g :call LazyGit()<CR>
```
Thanks for the pointers1
