### ISSUE TITLE
Tagbar and NERDTree wrapper needed😍

### ISSUE THREAD

**Issue by suliveevil** [voldikss/vim-floaterm#124]
vim-floaterm is a life changing pack!
Wish it could work with NERDTree and Tagbar.

**Comment by voldikss** [comment]
Thanks.

> Wish it could work with NERDTree and Tagbar.

In what way do you want for that support?

**Comment by suliveevil** [comment]
Display Tagbar or NERDTree‘s window as a popup window.
Since Browser Folder and Files even Tags may be a temporary progress, it’s better to act like a temporary window i.e. popup window.
Let them deal with file folder and tags, leave the control of tab/window/buffer to vim-floaterm.
This is what I expect vim-floaterm to do.

**Comment by voldikss** [comment]
File and tag management can not be handled by floaterm since floaterm is
only for terminal management.

As I know, both coc-explorer and defx support displaying files in floating
window. You may try them if you want this feature.

suliveevil <notifications@github.com> 于 2020年5月31日周日 下午8:53写道：

**Comment by suliveevil** [comment]
Maybe I should find another way to use vim-floaterm as a file manager.
I’m using iVim on iPadOS, it is not a full functional editor or operating system(Vim also) but it do have a builtin terminal called “ivish” and have several tools like ls curl awk.
Thank you very much.
