### ISSUE TITLE
Opening another file with nvim

### ISSUE THREAD

**Issue by ghamarian** [voldikss/vim-floaterm#127]
- Please make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

- Please make sure you are using the latest version of the plugin.

- Please use English as far as possible.

### Describe the bug
I defined a shortcut to open my todo file in combination with the freitass/todo.txt-vim plugin in another nvim instance. Sometimes it confuses about the nvim instances. Commands are run in the original nvim rather than in the todo file. What is the best way to do this?

### Enviroment
 - OSX
 - Version NVIM v0.4.3
 - Checkhealth info [run `:checkhealth` and post the messages]:

**Comment by voldikss** [comment]
Sorry I don't understand quite clearly. Could you describe it more specifically?

Does https://github.com/voldikss/vim-floaterm#general help you?

**Comment by ghamarian** [comment]
Thanks for your quick reply. This video is my inspiration but it is in spacemacs and I am trying to mimic the behavior in neovim. https://youtu.be/E9Fz5PGFK94?t=830 However, when I do that, sometimes neovim gets confused with commands and run them as if they are the commands on the original neovim and not in the neovim in the floaterm. If it is still not clear, I try to make a video of that. My suspicions are either locking issue or a race problem as it does not happen always and only every two-three times that I try this.

**Comment by voldikss** [comment]
Yes, a video or gif will be helpful.
