### ISSUE TITLE
Direnv is not read

### ISSUE THREAD

**Issue by bresilla** [voldikss/vim-floaterm#128]
I heavily use [direnv](https://github.com/direnv/direnv) during development. Which is basically a tool that changes environment variables on the fly when entering a directory or leaving it.

It seems that floaterm, when opened, it does not work with [direnv](https://github.com/direnv/direnv). I don't know how is the mechanism of floaterm when launched, but direnv is a kinda bash/zsh daemon, so it fires when it enters the directory (that has a file .envrc inside it) or when it leaves that directory.

As much as i can understand, this is because floaterm opens in the same directory where the vim is opened (or in the root of the project), thus there is no `cd` invoked, thus [direnv](https://github.com/direnv/direnv) can't be activated.

Is there a possible way to launch a "predefined command" with all floaterms, because what i am doing now is that i always have to do this when I open a floaterm for all floaterms:

```bash
tmppwd=$PWD; cd .. && cd $tmppwd
```

### Enviroment
 - OS [Manjaro]:
 - Version [NVIM v0.4.3]

**Comment by voldikss** [comment]
No other solutions, you can use this:

```vim
nnoremap   <Leader>fl      :FloatermNew! cd && cd -<CR>
```

**Comment by bresilla** [comment]
Okay. Thank you.
