### ISSUE TITLE
floaterm#hide not enough argument error

### ISSUE THREAD

**Issue by xltan** [voldikss/vim-floaterm#129]
can be reproduced by:
`set g:floaterm_gitcommit = "tabe"`
then use `git commit` in floaterm
should relate to the $GIT_EDITOR env

**Comment by voldikss** [comment]
Fixed, thanks.

**Comment by wookayin** [comment]
Why don't you have a default argument? I think that makes a lot of sense as a default behavior. But, before this, why do you keep changing and breaking APIs?

**Comment by voldikss** [comment]
> Why don't you have a default argument? (e.g. you could make both `floaterm#hide()` and `floaterm#hide(1, '')` work) I think that makes a lot of sense as a default behavior. But, before this, why do you keep changing and breaking APIs?

So sorry for the API changing. 

I discarded vimscript's default argument form because they are not user/developer-friendly. Usually they are hard to understand without having an exhaustive look at the function body. I want to make them clearer. Though `floaterm#hide(1, '')` is very ugly, there is no other choices.

**Comment by wookayin** [comment]
You could maintain a few lines of documentation about the argument specification. Even though the parameters are explicitly stated, users won't be able to understand what they are about without documentation (admittedly some parameters are self-explanatory) unless having a look at the function body.

**Comment by voldikss** [comment]
I found that those functions may have breaking changes inevitability during development.  And they shouldn't be exposed to common users.

Therefore, they can not stay in README anymore. Instead, I kept them in a Wiki page with a breaking changes notice attached.

**Comment by wookayin** [comment]
With all due respect, just using vaargs `...` would make our life simpler.
