### ISSUE TITLE
gVIM8.2输入模式下有高亮-切到正常模式就不高亮

### ISSUE THREAD

**Issue by gVimer** [voldikss/vim-floaterm#131]
![Snipaste_2020-06-11_20-49-23](https://user-images.githubusercontent.com/6241431/84387342-6ff02d00-ac25-11ea-9320-f5b4b6eb3115.png)
光标所在行也不高亮了
![Snipaste_2020-06-11_20-49-45](https://user-images.githubusercontent.com/6241431/84387351-71215a00-ac25-11ea-91f5-57136ed217e5.png)

**Comment by voldikss** [comment]
can not reproduce, check your key mapping for `<Esc>`.

**Comment by gVimer** [comment]
`tnoremap <Esc> <C-\><C-N>
`

**Comment by gVimer** [comment]
用命令打开一个终端
`FloatermNew  --wintype=floating  --position=topleft --autoclose=2
`
打开后直接输入 exit 报错
![Snipaste_2020-06-11_21-20-34](https://user-images.githubusercontent.com/6241431/84389985-800a0b80-ac29-11ea-87be-05edafbfa022.png)

**Comment by voldikss** [comment]
gVim 的 wintype 必须是 normal 或者 popup

**Comment by gVimer** [comment]
不好意思  这是我的错 麻烦大神看下高亮的问题吧

**Comment by voldikss** [comment]
我暂时没在用 gVim，等有空我去 Windows 装 gVim 测测

**Comment by gVimer** [comment]
好的 麻烦了 这两天我也多用用这个插件 到时候有问题就反馈到这里来

**Comment by gVimer** [comment]
切换到正常模式的时候 终端没有被填充的部分的背景色变成了非终端的背景色 这个是VIM的BUG吧 看有没有人去给作者提个ISSUE .大神到时候在WIN下可以看下
![Snipaste_2020-06-11_21-54-22](https://user-images.githubusercontent.com/6241431/84393560-51426400-ac2e-11ea-90c3-bfb23ae2a85a.png)

**Comment by gVimer** [comment]
> gVim 的 wintype 必须是 normal 或者 popup

刚试了 wintype=normal 的时候exit也会报错 跟上面的一样的  只有在popup下是正常的

**Comment by gVimer** [comment]
顺便问个题外话 就是这个补全菜单在gVIM下是怎么设置的 
![Snipaste_2020-06-11_22-10-29](https://user-images.githubusercontent.com/6241431/84395155-789a3080-ac30-11ea-808f-212d8985d3b4.png)

**Comment by voldikss** [comment]
gVim 不支持弹出窗口

**Comment by gVimer** [comment]
哦哦 好的  了解了 3Q

**Comment by gVimer** [comment]
语法高亮的问题已经得到解决 设置如下：
`function s:fTerminalSettings()`
 `  setlocal number`
 `  setlocal cursorline`
 `  syntax on`
`endfunction`
`autocmd FileType FLOATERM call s:fTerminalSettings()`
但是不支持在其中使用Leaderf

**Comment by gVimer** [comment]
gVim的悬浮终端问题多 下个版本再看
