### ISSUE TITLE
nnn (nnn wrapper) not opening files in neovim

### ISSUE THREAD

**Issue by arekmd** [voldikss/vim-floaterm#132]
* Neovim 0.4.3
* KDE Neon 5.19 
* nnn 1.7

```
set nocompatible
set termguicolors
...
Plug 'voldikss/vim-floaterm'
...
```

I'm starting nnn using command- :FloatermNew nnn.  When I try to open any file in nnn, default editor (KWrite on my system) is started. 

I'm also using ranger, and it is working fine.

**Comment by voldikss** [comment]
> When I try to open any file in nnn,

Which key did you press to open the file? `<Enter>` or `L`?

**Comment by arekmd** [comment]
Both <Enter> and <L> works the same way.

**Comment by voldikss** [comment]
Please upgrade nnn to version 3.4, then the problem should be solved. Otherwise, you could reopen the issue.
