### ISSUE TITLE
Keybinding to switch between window

### ISSUE THREAD

**Issue by Kidman1670** [voldikss/vim-floaterm#134]
- Normally we can use ```<C-w w>``` or something simmilar to switch between splitted windows. I personally use tmux-vim-plugin to change default keymaps. 
- But seem like I can use those key in Floaterms.
- I must use mouse to switch between window.

**Comment by voldikss** [comment]
You can not because neovim/vim doesn't support `wincmd h/j/k/l` for floating windows.

One possible solution for that is to use `:FloatermPrev` or `:FloatermNext` command.
