### ISSUE TITLE
Can user remove the highlighted column?

### ISSUE THREAD

**Issue by Freed-Wu** [voldikss/vim-floaterm#135]
![image](https://user-images.githubusercontent.com/32936898/85220217-5052c480-b3dc-11ea-96b0-20fb3ebfa1a1.png)
![image](https://user-images.githubusercontent.com/32936898/85220240-8132f980-b3dc-11ea-9e08-ab49b64db01e.png)

when user set colorcolumn, a highlighted column wil appear. but in floaterm border, it also appear. can user remobe the hightlighted column? Thanks!

**Comment by voldikss** [comment]
Thanks, I made a fix on that.

**Comment by inventionate** [comment]
I think the fix doesn't solve the problem because it doesn't change colorcolumn. Shouldn't the code include this line?

` call nvim_win_set_option(border_winid, 'colorcolumn', "")`

**Comment by voldikss** [comment]
Hi @inventionate , according the nvim doc, `cursorcolumn` is a boolean value option. So here it should be `  call nvim_win_set_option(border_winid, 'cursorcolumn', v:false)`.
```
			*'cursorcolumn'* *'cuc'* *'nocursorcolumn'* *'nocuc'*
'cursorcolumn' 'cuc'	boolean	(default off)
			local to window

```

**Comment by voldikss** [comment]
Doesn't ` call nvim_win_set_option(border_winid, 'cursorcolumn', v:false)` fix the problem for you? @inventionate

**Comment by inventionate** [comment]
You're right, cursorcolumn is a boolean value, but to fix the problem colorcolumn must be changes and this variable is no boolean, it's string. If I patch the mentioned line in the problems gone otherwise it persists.

**Comment by voldikss** [comment]
Hi @inventionate , I changed that line to `call nvim_win_set_option(border_winid, 'colorcolumn', '')` but it causes errors.

![image](https://user-images.githubusercontent.com/20282795/88920415-65eec000-d29f-11ea-84c0-a1584dcfed67.png)

**Comment by voldikss** [comment]
Could you give me your nvim version?

**Comment by inventionate** [comment]
I use nvim 0.4.3 and I can't reproduce the error. 

The error also seems to have nothing to do with colorcolumn. Is cursorcolumn set anywhere else? Have you already tried to keep both lines in the code?

The only way to fix the error is to set `colorsolumn = ""` (default) for me. In my init.vim I set `colorcolumn=+1`.

**Comment by inventionate** [comment]
That's great and thank you @voldikss very much for your great plugin!
