### ISSUE TITLE
FloatermNew should not autohide other windows

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#136]
Steps to reproduce:

```
:FloatermNew --position=right --wintype=normal --name=A
:FloatermNew
```

Upon the second `:FloatermNew`, the previous window would be automatically hidden. This is because `floaterm#autohide()` is called in the first few lines of `floaterm#new()`.

However, when there are non-floating windows (e.g. could be normal windows), they should not be automatically hidden.

**Comment by voldikss** [comment]
Yes. I've added an option `autohide` a few days ago because I found toggling off multiple floaterm windows one by one is pretty annoying. 

See https://github.com/voldikss/vim-floaterm#gfloaterm_autohide

However, the option's name seems not intuitive...
