### ISSUE TITLE
[BUG] not focusing on the correct buffer after switching back from terminal

### ISSUE THREAD

**Issue by Shuumatsu** [voldikss/vim-floaterm#14]
> 切换到terminal后再切换回来，焦点并不是切换前正在使用的buffer

EDIT: Can not focusing on the formaer buffer after switching back from terminal

**Comment by voldikss** [comment]
这个可以给出复现步骤吗？我这里没有复现出来

**Comment by wookayin** [comment]
Guys please avoid using Chinese here.

**Comment by voldikss** [comment]
Sorry it's me who firstly use Chinese in #12 . 

I have updated above comments.

**Comment by Shuumatsu** [comment]
Cannot reproduce either after 09cf3e250a0bb0b6cd160e854c51dd068e922ece
