### ISSUE TITLE
Focus editor buffer without closing the floaterm window

### ISSUE THREAD

**Issue by matheusfillipe** [voldikss/vim-floaterm#140]
Is it possible to focus the main buffer editor back after a new window is opened? I mean without having to toggle it. I would like to leave it on the view and focus the text buffer with a keyboard shortcut. 

<C-w> Up doesn't work. The only way I know to do this know is by clicking.

**Comment by voldikss** [comment]
`<C-W>h/j/k/l`

**Comment by matheusfillipe** [comment]
This works from a text buffer to another, not from a shell like python back to the text buffer.

**Comment by voldikss** [comment]
> This works from a text buffer to another, not from a shell like python back to the text buffer.

Sorry for the late response. When you are inside a terminal and want to go back to the normal window, firstly you must go back to the normal mode using `<C-\><C-n>`. Then you can use `<C-W>h/j/k/l` or `<C-w>w` to jump between windows.

Here is a recommended keymap configuration:

```vim
  tnoremap <M-h> <C-\><C-n><C-w>h
  tnoremap <M-j> <C-\><C-n><C-w>j
  tnoremap <M-k> <C-\><C-n><C-w>k
  tnoremap <M-l> <C-\><C-n><C-w>l
```
