### ISSUE TITLE
Vifm in floaterm has wrong colors

### ISSUE THREAD

**Issue by NightH4nter** [voldikss/vim-floaterm#141]
### Describe the bug

Vifm in floaterm has wrong colors while working fine in a regular terminal.

### To Reproduce

- Use the minimal vimrc

  ```vim
  set nocompatible
  set hidden
  set termguicolors
  set runtimepath^=/path/to/vim-floaterm
  filetype plugin indent on
  syntax on
  ```

- Steps to reproduce the behavior:
  1. Launch Vim
  2. Type :FloatermNew vifm, and press Return
  3. Get wrong colors

### Enviroment
 - OS: ArchLinux.
 - Version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 21 2020 16:11:23), Included patches: 1-814 (`gvim` package in Arch).
 - Terminal: Temite.
 - Color schemes: [NeoSolarized](https://github.com/overcache/NeoSolarized) (vim), [solarized-dark-edited](https://gist.github.com/NightH4nter/652df9657330586e1ccd5eac44845351) (vifm), [solarized-dark](https://github.com/alpha-omega/termite-colors-solarized/blob/master/solarized-dark) (Termite).

### Screenshots
This is what vifm looks like in Termite:
![2020-07-26-225352_1440x900_scrot](https://user-images.githubusercontent.com/31319604/88487023-e60ce100-cf92-11ea-8881-98678772e9f9.png)
This is what it looks like in floaterm:
![image](https://user-images.githubusercontent.com/31319604/88487045-10f73500-cf93-11ea-9d0a-c9d8ddf2901f.png)
Same, but with the default color scheme in both vim and vifm (with `colorscheme Default` in `vifmrc` and `vimrc` stated above):
![2020-07-26-230019_1440x900_scrot](https://user-images.githubusercontent.com/31319604/88487163-c9bd7400-cf93-11ea-929c-26149b5152e5.png)
![image](https://user-images.githubusercontent.com/31319604/88487173-d4780900-cf93-11ea-921a-a767d222b493.png)

**Comment by voldikss** [comment]
What's wrong? These two screenshots shows that these two have the identical color(yes, there are some little differences though)

**Comment by voldikss** [comment]
What if you open vifm directly from vim terminal?

**Comment by NightH4nter** [comment]
It seems like it's vim terminal's issue I guess. Still no idea about why does it work this way.
![image](https://user-images.githubusercontent.com/31319604/88511507-f609dc80-cff5-11ea-9c77-a0c53654608f.png)


> What's wrong? These two screenshots shows that these two have the identical color(yes, there are some little differences though)

Status bar is unreadable, command bar is black, folders are light cyan and bold instead of cyan.
