### ISSUE TITLE
File manager open in vertical or horizontal splits?

### ISSUE THREAD

**Issue by zstreeter** [voldikss/vim-floaterm#142]
Please close...

**Comment by voldikss** [comment]
For example, vertical split

```vim
:FloatermNew --wintype=normal --position=right --width=0.5 lf
```

**Comment by zstreeter** [comment]
Thank you for your comment.  I deleted my question because I see you have "let g:floaterm_open_command='edit' and edit could be split or vsplit.  This is what I was wanting!
Though I would like a command for all three cases.  Do you know how to wrap these in a command I could use?  It would be a nice feature to have...

**Comment by voldikss** [comment]
#63 would be helpful

**Comment by zstreeter** [comment]
I think for all the file managers, having the ability to open the file in a vertical split or whatever, once in the file manager is nice.  I used floatLF-nvim because it allowed me to open the file in a vertical split when in the floating window instance of LF with ctr-v and horizontal with ctr-x.  

https://github.com/haorenW1025/floatLf-nvim
