### ISSUE TITLE
How to integrate with fzf.vim?

### ISSUE THREAD

**Issue by gbrlsnchs** [voldikss/vim-floaterm#143]
Hi, I'd love to use vim-floaterm alongside fzf.vim. [The wiki page is empty](https://github.com/voldikss/vim-floaterm/wiki/Integration-with-other-fuzzy-finders) for this exact integration unfortunately, and I have no idea where to start.

Thanks for this awesome plugin nonetheless!

**Comment by voldikss** [comment]
Hi there
I do have the plan to add fzf.vim integration. However, I am not familar with fzf.vim.

**Comment by voldikss** [comment]
I am going to take a look at fzf.vim's instruction and add fzf.vim integration when I have free time.

Or if someone is interested in this feature, feel free to send me a PR.

**Comment by adigitoleo** [comment]
@gbrlsnchs 
> Hi, I'd love to use vim-floaterm alongside fzf.vim.

I am a new user of both fzf and vim-floaterm, but maybe I can help with some ideas. Personally, I don't use fzf.vim, I roll my own fzf wrappers. For starters, fzf already supports floating windows, for example:

```
    " Search for files in <dir> (or $PWD by default).
    command! -bang -complete=dir -nargs=* FuzzyFind
                \ call fzf#run(fzf#wrap(
                \{
                \'sink': 'e',
                \'window': { 'width': 0.9, 'height': 0.6, 'border': 'sharp' },
                \'options': '--multi',
                \'dir': <q-args>
                \},
                \<bang>0
                \))
```

This command will open a floating window running fzf. The `window` option is relevant here. I will need to look at fzf.vim commands more to understand how the wrappers are built, but could you describe more what kind of workflow you are looking for? Maybe you have some good ideas that I didn't think about :smiley:

**Comment by adigitoleo** [comment]
I think I have misunderstood what you are looking for. If I am correct, you want to have a `:Floaterms` command that will show all curent floaterms in an fzf picker window (like fzf.vim does for `:Buffers` etc.) IMHO this should be implemented in fzf.vim, but either way you will basically need to get the list of floaterms and send them to the fzf `source`, and for the `sink` use a callback that will switch to the floaterm. There is also the `preview` option just like for LeaderF.

This is a VERY basic implementation without preview, I haven't tested it much yet:

```vim
function! s:FloatermFeed()
    let candidates = []
    let bufs = floaterm#buflist#gather()
    for bufnr in bufs
        let bufinfo = getbufinfo(bufnr)[0]
        let name = bufinfo['name']
        " Better: generate custom format like for LeaderF example in wiki
        call add(candidates, name)
    endfor
    return candidates
endfunction

function! s:FloatermAccept(line) abort
    " Better: parse whatever line format is generated by s:FloatermFeed and pick out buffer name.
    let bn = bufnr(a:line)
    call floaterm#terminal#open_existing(bn)
endfunction

" Search for open floaterms.
command! -bang Floaterms
            \ call fzf#run(fzf#wrap(
            \{
            \'source': s:FloatermFeed(), 'sink': function('s:FloatermAccept'),
            \'window': { 'width': 0.9, 'height': 0.6, 'border': 'sharp' },
            \},
            \<bang>0
            \))
```

Due to the changes in #175 the list looks very cryptic, so we would want a preview or changes to the functions as I have indicated.

**Comment by gbrlsnchs** [comment]
Thanks for you responses. Actually, I wanted to open FZF wrappers inside floaterms, however, like you said, FZF already allows that by passing the appropriate settings.

Anyway, it is a cool idea to feed FZF all open floaterms. I will give that a try, thank you very much for sharing your knowledge!

**Comment by voldikss** [comment]
>  Actually, I wanted to open FZF wrappers inside floaterms

I ever thought what you want is to feed FZF all opened floaterms and open them by FZF searching API. Now that you just wanted fzf wrapper, this plugin already has it. Just try `:FloatermNew fzf`. Since this plugin is not a fuzzyfinder like plugin, it only has a basic and simple support for fzf.

**Comment by voldikss** [comment]
Let me close this issue since it can be seen as resolved. Feel free to comment if there are any more problems.

**Comment by voldikss** [comment]
> I think I have misunderstood what you are looking for. If I am correct, you want to have a `:Floaterms` command that will show all curent floaterms in an fzf picker window (like fzf.vim does for `:Buffers` etc.) IMHO this should be implemented in fzf.vim, but either way you will basically need to get the list of floaterms and send them to the fzf `source`, and for the `sink` use a callback that will switch to the floaterm. There is also the `preview` option just like for LeaderF.
> 
> This is a VERY basic implementation without preview, I haven't tested it much yet:
> 
> ```viml
> function! s:FloatermFeed()
>     let candidates = []
>     let bufs = floaterm#buflist#gather()
>     for bufnr in bufs
>         let bufinfo = getbufinfo(bufnr)[0]
>         let name = bufinfo['name']
>         " Better: generate custom format like for LeaderF example in wiki
>         call add(candidates, name)
>     endfor
>     return candidates
> endfunction
> 
> function! s:FloatermAccept(line) abort
>     " Better: parse whatever line format is generated by s:FloatermFeed and pick out buffer name.
>     let bn = bufnr(a:line)
>     call floaterm#terminal#open_existing(bn)
> endfunction
> 
> " Search for open floaterms.
> command! -bang Floaterms
>             \ call fzf#run(fzf#wrap(
>             \{
>             \'source': s:FloatermFeed(), 'sink': function('s:FloatermAccept'),
>             \'window': { 'width': 0.9, 'height': 0.6, 'border': 'sharp' },
>             \},
>             \<bang>0
>             \))
> ```
> 
> Due to the changes in #175 the list looks very cryptic, so we would want a preview or changes to the functions as I have indicated.

Thanks! I've post this to the Wiki page and also created a plugin fzf-floaterm using your code.

**Comment by gbrlsnchs** [comment]
No problem, @voldikss, thanks for your attention (and for this great plugin too)!

**Comment by adigitoleo** [comment]
Note that `:FloatermNew fzf` is possibly redundant as of the latest fzf commit at https://github.com/junegunn/fzf/commit/c60ed1758315f0d993fbcbf04459944c87e19a48, which makes fzf use the floating window by default. It also means that the `window` option in the above snippet is not needed anymore.
