### ISSUE TITLE
Buffer refresh after using floaterm

### ISSUE THREAD

**Issue by timsofteng** [voldikss/vim-floaterm#146]
How can i refresh (sync) vim buffers after using floaterm? For example after branch checkout in lazygit using floaterm I need refresh my buffers according to current branch. How can i do it? If I manually do :checktime it works but i want automatically option. Thanks.

**Comment by voldikss** [comment]
I have no idea if there is a proper method for this. This plugin doesn't serve a hook to do this. 
But the only solution appears to be making a key mappings.
