### ISSUE TITLE
Use ranger in floaterm to overwrite netrw

### ISSUE THREAD

**Issue by gianfrappe** [voldikss/vim-floaterm#147]
### Request
I would like to override netrw directory view with a floaterm running ranger. I have seen the same exact thing on this ranger [plugin](https://github.com/francoiscabrol/ranger.vim/) and I would like to emulate that behaviour with floating window. I find no info in the README, and knowing nothing about VimL I am not sure where to start. Could you integrate this function by default?

### Enviroment
 - OS Arch Linux
 - Version: 0.4.4

**Comment by voldikss** [comment]
Sorry but you couldn't. See #124
