### ISSUE TITLE
nnn wrapper linked from nnn project

### ISSUE THREAD

**Issue by jarun** [voldikss/vim-floaterm#151]
Author of nnn here.

This is not an issue. Just wanted to update that I found this awesome project today and [linked](https://github.com/jarun/nnn/commit/6069ecf1ac8c96820368e7434a1a33721cb15f31) the nnn wrapper from nnn README.

Thank you so much!

**Comment by voldikss** [comment]
> Author of nnn here.
> 
> This is not an issue. Just wanted to update that I found this awesome project today and [linked](https://github.com/jarun/nnn/commit/6069ecf1ac8c96820368e7434a1a33721cb15f31) the nnn wrapper from nnn README.
> 
> Thank you so much!

Thanks you very much for the link. nnn project is awesome!

**Comment by jarun** [comment]
My pleasure!

I have raised a PR to list `nnn` as one of the users.

Please take a look. Closing this defect. All the best!

**Comment by jarun** [comment]
Please ignore my note on the PR. That's on `icons-in-terminal` project.
