### ISSUE TITLE
Fonctionality request

### ISSUE THREAD

**Issue by manu0600** [voldikss/vim-floaterm#152]
Hi :) It would be nice when calling the FloatermNew command, to change directory to the current one (obtained from the vim command :expand('%:p:h') )
Thank you

**Comment by voldikss** [comment]
Hi, please check https://github.com/voldikss/vim-floaterm#gfloaterm_rootmarkers

**Comment by voldikss** [comment]
Is that are you looking for?

**Comment by voldikss** [comment]
By default floaterm would be opened at the current directory. Can you provider a gif?

**Comment by voldikss** [comment]
`set autochdir`

or 

use autocmd
```vim
augroup UserAutoChangeDir
  autocmd!
  autocmd BufEnter * silent! lcd %:p:h
augroup END
```
