### ISSUE TITLE
Navigating ranger up and down destroys the view

### ISSUE THREAD

**Issue by p0txky** [voldikss/vim-floaterm#158]

**Comment by voldikss** [comment]
Hi @p0txky Could you give more infomation? see https://github.com/voldikss/vim-floaterm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by p0txky** [comment]
same issue #120

**Comment by voldikss** [comment]
So you are using Vim8?

**Comment by voldikss** [comment]
In case this issue is duplicated with #120, let me close it now.

**Comment by p0txky** [comment]
vim 8.2, manjaro, zsh

**Comment by voldikss** [comment]
> vim 8.2, manjaro, zsh

That's right. Definitely the same as #120
