### ISSUE TITLE
Strange nnn behavior during scroll

### ISSUE THREAD

**Issue by timsofteng** [voldikss/vim-floaterm#171]
Hey. I catch a strange bug in NNN. It's better to look  at gif.
Bug reproduces when list in folder is longer than screen and after scroling to bottom of the list.

1. Open `nnn` by `:FloatermNew nnn`.
2. Open folder with long list of files or directories (should be longer than current sreen's height).
3. Scroll to bottom of the list by `j` or `k` keys.

![Peek 2020-09-05 17-48](https://user-images.githubusercontent.com/51912173/92307775-6a468100-efa1-11ea-8db1-d5789c0dbc9d.gif)

**Comment by adigitoleo** [comment]
I can't seem to reproduce this, using latest floaterm master and default nnn from arch repos. What is your `set scrolloff?` Does it happen in the normal `:terminal`?

**Comment by timsofteng** [comment]
> I can't seem to reproduce this, using latest floaterm master and default nnn from arch repos. @timsofteng What is your `set scrolloff?` Does it happen in the normal `:terminal`?

In normal `:teminal` this bug doesn't exist.
`set scrolloff` doesn't help.

**Comment by voldikss** [comment]
Yes, I can confirm this issue,  whereas it only occurs on Vim8.

**Comment by timsofteng** [comment]
> Yes, I can confirm this issue, whereas it only occurs on Vim8.

Yes. In neovim scroll works correctly.

**Comment by dmnks** [comment]
Same issue here (only when using the popup layout in Vim).

**Comment by voldikss** [comment]
vim/nnn bug

```vim
:let buf = term_start('nnn', #{hidden: 1})
<C-w>s
:execute 'buffer'.buf
```
