### ISSUE TITLE
Sync vim buffers after floaterm closing

### ISSUE THREAD

**Issue by timsofteng** [voldikss/vim-floaterm#172]
Can you explain please how i can sync all project in vim after closing floterm?

For example when I open lazygit in floaterm and then checkout to other branch. After this I close floaterm and want all my open buffers sync according to current branch.

Thanks.

**Comment by voldikss** [comment]
Use `autoread` or `checktime`

**Comment by timsofteng** [comment]
It is buggy when I closed lazygit by pressing `q`. In this way i have problems with buffers autoread. However if I closed lazygit by `g:floaterm_keymap_kill` it reads ok.
