### ISSUE TITLE
Ranger Colortheme doesnt work

### ISSUE THREAD

**Issue by joe23rep** [voldikss/vim-floaterm#173]
hey- first off- love this plugin. great work.

now to my question: is it possible to configure the colorthemes used inside floaterm? it somehow uses a different colortheme than configured inside rangers config.

**Comment by adigitoleo** [comment]
Did you try running ranger in a `:terminal` buffer? Are the colors what you expect? Are you running neovim or vim?

For vim, check help for `g:terminal_ansi_colors`. For neovim `:h terminal-configuration`. The embedded terminals do not inherit external colors in a simple way, maybe your vim colorscheme sets `:terminal` colors as well.

**Comment by voldikss** [comment]
Thank @adigitoleo for the explaination!

Let me close this~
