### ISSUE TITLE
FloatermSend discussion

### ISSUE THREAD

**Issue by adigitoleo** [voldikss/vim-floaterm#174]
Hi,

Thanks for the awesome plugin! I think it could be very convenient for REPLs, and `:terminal` was missing this kind of "toggle" feature.

This is not a bug report, but I was setting up some vim mappings and reading the docs and it seems to me that `:FloatermSend` does too many things. Specifically:

```
If there are no floaterms opened, :FloatermSend will open a floaterm and execute lines for you.
```

Is this really needed? I think this could have surprising effects. Maybe I forgot to set up a `:FloatermNew` beforehand, and now my shell is choking on python :) Would it be better to echo an error: "No floaterm available" or something? I think `:FloatermFirst` etc. already do this.

Example mappings, to help discussion:

```
    autocmd FileType python nnoremap <buffer> <silent> <LocalLeader><Cr>
                \ :FloatermNew --name=pyrepl ipython --no-autoindent<Cr>
    autocmd FileType python nnoremap <buffer> <silent> <Leader><Cr>
                \ :FloatermShow pyrepl<Cr>
    autocmd FileType python tnoremap <silent> <Leader><Cr>
                \ <C-\><C-n>:FloatermHide pyrepl<Cr>
    autocmd FileType python xnoremap <buffer> <silent> <LocalLeader><Cr>
                \ :FloatermSend --name=pyrepl<Cr>
```

So, the workflow would be:
1. Open python buffer.
2. `<LocalLeader><Cr>` to set up ipython REPL
3. Hide REPL using `<Leader><Cr>` (in this example `<Leader>` is different to `<LocalLeader>`)
4. Send code to REPL using `<LocalLeader><Cr>` over a visual range (or whole file, whatever)
5. Toggle REPL using the show/hide mappings
6. Repeat 3 + 4 as needed

Because step 2 is only needed once, it is easy to forget. Then, because there is nothing to hide, we skip to step 4 but now the code is sent to a new (!) terminal without ipython.

There is possibly one more problem: 

```
If --name=floaterm_name exists, send lines to the floaterm instance whose name is floaterm_name. Otherwise use the current floaterm.
```

Should it use the current floaterm, even if the user specified a `--name` ? Obviously, a bare `:FloatermSend` should do this, but I suggest also echoing an error here: "No floaterm called [name]" or something. To me at least, this behaviour would be less surprising.

Well, I hope that made sense :) I am excited to bring floaterms into my neovim workflow. Thanks for reading.

-Leon

**Comment by adigitoleo** [comment]
After further thought, something like a `b:unique_floaterm` boolean could be useful here. So mappings can be set up globally, and then the default action of `:FloatermSend` and other things could be made filetype-aware. That is probably more work to implement... I am willing to help as much as I can, but my vimscript is not so good yet :P

**Comment by voldikss** [comment]
>  Is this really needed? I think this could have surprising effects. Maybe I forgot to set up a :FloatermNew beforehand, and now my shell is choking on python :) Would it be better to echo an error: "No floaterm available" or something? I think :FloatermFirst etc. already do this.

Yes you are right, it should give a message like "There are no floaterms opend" rather than opening a new floaterm. I've changed the conresponding code.

> Should it use the current floaterm, even if the user specified a --name ? Obviously, a bare :FloatermSend should do this, but I suggest also echoing an error here: "No floaterm called [name]" or something. To me at least, this behaviour would be less surprising.

In this case, `--name` has higher priority. That's to say, only if it couldn't find a specific floaterm, the current floaterm would be used.

**Comment by voldikss** [comment]
> After further thought, something like a `b:unique_floaterm` boolean could be useful here. So mappings can be set up globally, and then the default action of `:FloatermSend` and other things could be made filetype-aware. That is probably more work to implement... I am willing to help as much as I can, but my vimscript is not so good yet :P

I do not understand this well. However, I prefer not to make it too complex for REPL feature in this plugin since it is not a complete-REPL plugin. Sorry for that.

**Comment by adigitoleo** [comment]
> I do not understand this well. However, I prefer not to make it too complex for REPL feature in this plugin since it is not a complete-REPL plugin. Sorry for that.

 You're right, this was not very clear. Basically I was thinking about having some sort of buftype-local settings (using the `b:` prefix) to control the behaviour of floaterms when invoked from specific filetypes. But I can understand that it is beyond the scope of this project.

> In this case, --name has higher priority. That's to say, only if it couldn't find a specific floaterm, the current floaterm would be used.

I'm still not convinced. From a user perspective, if I didn't care about what floaterm to use, I would not put a `--name` argument. If I include `--name`, then I expect it to send to that specific floaterm only. So I would expect an error if it doesn't exist. But it is probably too much to change it completely (maybe some people are used to this behaviour), so maybe it can be an option instead? Like `g:floaterm_send_fallback` where 0 means "do not fall back to unnamed floaterm"? 

Let me know what you think.

**Comment by voldikss** [comment]
> From a user perspective, if I didn't care about what floaterm to use, I would not put a --name argument.

Yes.

> If I include --name, then I expect it to send to that specific floaterm only. So I would expect an error if it doesn't exist. 

Yes, the plugin works just as you wish. If the named floaterm doesn't exist, it will throw a warning message and return rather than looking for another opened floaterm.

Sorry for the ambiguous description in README, here 

```
If --name=floaterm_name exists, send lines to the floaterm instance whose name is floaterm_name. Otherwise use the current floaterm.
```

`--name=floaterm_name` refers to the argument instead of the floaterm instance. So that's to say, if you do not pass `--name=floaterm_name`, it would use the current floaterm, Otherwise use the floaterm named `floaterm_name`.

**Comment by voldikss** [comment]
> You're right, this was not very clear. Basically I was thinking about having some sort of buftype-local settings (using the b: prefix) to control the behaviour of floaterms when invoked from specific filetypes. But I can understand that it is beyond the scope of this project.

IMO maybe it's better to make another plugin specifically for REPL. The plugin could use vim-floaterm's APIs(some functions or commands) to make it easier to develop. For example, some already have developped a plugin [vim-floaterm-repl](https://github.com/windwp/vim-floaterm-repl), but it doesn't have interactive operation...

**Comment by adigitoleo** [comment]
> Yes, the plugin works just as you wish.

Oops, I guess I should have tested it more :) That's nice.

> IMO maybe it's better to make another plugin specifically for REPL.

True, that makes sense. I'll need to use floaterms for a bit first to see if it is really necessary. I'll start by just using FileType autocommands for now. Since one of my concerns has been fixed and the other one was a misunderstanding, maybe this can be closed for now?

**Comment by adigitoleo** [comment]
> Sorry for the ambiguous description in README

Final suggestion: maybe change `If --name=floaterm_name exists [...]` to `If --name=floaterm_name is given [...]` for that line in the README?

**Comment by voldikss** [comment]
> > Sorry for the ambiguous description in README
> 
> Final suggestion: maybe change `If --name=floaterm_name exists [...]` to `If --name=floaterm_name is given [...]` for that line in the README?

Thanks! I'll update later.

**Comment by voldikss** [comment]
Updated(I think I should improve my English writing skill...).

Anyway, thanks for the suggestion. And let me close this issue.
