### ISSUE TITLE
Autoread buffers doesn't work

### ISSUE THREAD

**Issue by timsofteng** [voldikss/vim-floaterm#178]
Buffers autoread still works ucorrectly.

Look at the gif please.  I'm trying to switch to another branch, but buffers still has old state.

![Peek 2020-09-09 18-24](https://user-images.githubusercontent.com/51912173/92620089-ee16ab00-f2ca-11ea-8073-4c31aab4a30c.gif)

**Comment by voldikss** [comment]
Open lazygit in the normal vim terminal and do all your operations to see if the issue can be reproduced

**Comment by voldikss** [comment]
Open lazygit in the normal vim terminal and do all your operations to see if the issue can be reproduced

**Comment by voldikss** [comment]
> Open lazygit in the normal vim terminal and do all your operations to see if the issue can be reproduced

The issue still exists for normal neovim terminal. So it is not related to the vim-floaterm

**Comment by timsofteng** [comment]
Please don't close the issue.
My buffers update with this options.
But ALE plugin doesn't work before `:e`.
What can I do to trigger it automatically?

**Comment by voldikss** [comment]
> Please don't close the issue.
> My buffers update with this options.
> But ALE plugin doesn't work before `:e`.
> What can I do to trigger it automatically?

Sorry but I don't know... I am not using Ale, regret for that.

Since this issue also exists for normal neovim terminal, it's not the bug if this plugin.

**Comment by timsofteng** [comment]
![image](https://user-images.githubusercontent.com/51912173/92702186-91160600-f359-11ea-977c-1d0b634ec43a.png)

 How about this?
If you add it into this place `vim-floaterm/autoload/floaterm/window.vim` user dont need to do `autocmd BufEnter * checktime`

**Comment by voldikss** [comment]
Looks good. Would you like to draft a PR for that?

**Comment by timsofteng** [comment]
> Looks good. Would you like to draft a PR for that?

It doesn't matter for me. You may implement it by yourself.
I just don't know what can I do with ALE issue...
