### ISSUE TITLE
vim-floaterm append extra path to user's PATH env variable

### ISSUE THREAD

**Issue by xulongwu4** [voldikss/vim-floaterm#179]
I noticed that floaterm append `FLOATERM_PATH/bin` to user's PATH env variable, where `FLOATERM_PATH` is the location of the `vim-floaterm` directory. In my case, `FLOATERM_PATH` is `$HOME/.vim/pack/plugins/start/vim-floaterm`.

This causes some inconvenience to my workflow. My project uses a build tool that will check a few environment variables upon startup, `PATH` being one of them. If these env variables have changed since last build, it will rebuild the whole project from scratch. This means that if I built my project in a regular terminal, and then I try building it inside `vim` with `vim-floaterm`, it will rebuild everything again.

I am wondering what is the purpose of appending such a path to user's `PATH` variable. In addition, is this avoidable? Or, is it possible for users to undo this change? Thanks.

**Comment by voldikss** [comment]
This seems unresolvable. 

In order to use [`floaterm`](https://github.com/voldikss/vim-floaterm#floaterm) executable in the floaterm, I have to add [`path/to/vim-floaterm/bin`](https://github.com/voldikss/vim-floaterm/tree/master/bin) to the `$PATH`.

**Comment by xulongwu4** [comment]
Is it possible to define an alias for `floaterm` inside the newly opened floaterm and not append to $PATH?

**Comment by voldikss** [comment]
> Is it possible to define an alias for `floaterm` inside the newly opened floaterm and not append to $PATH?

In order to do that, I have to execute explicitily after every floaterm startup, which makes it very ugly.

Because `terminal` is another sub process, executing `!alias floaterm=...` won't work for it...

**Comment by ArcherN9** [comment]
I'm not sure if this is relevant, or if it will even work. I may not be experienced enough to weigh this recommendation, but there's something called `runtimepath` in vim. Can that be used?

**Comment by voldikss** [comment]
> I'm not sure if this is relevant, or if it will even work. I may not be experienced enough to weigh this recommendation, but there's something called `runtimepath` in vim. Can that be used?

Sadly `rtp` is not relevant to the retrieve of the system executable programs.

**Comment by voldikss** [comment]
Since there are no solutions for #184, this issue is also not possible to fix. Regreted so much.
