### ISSUE TITLE
Everytime I open the terminal, It is appending an `i` char

### ISSUE THREAD

**Issue by voldikss** [voldikss/vim-floaterm#18]
I think it should be another issue but everytime I open the terminal, It is appending an `i` char

_Originally posted by @mrprofessor in https://github.com/voldikss/vim-floaterm/issues/16#issuecomment-547739331_

**Comment by voldikss** [comment]
The solution is to use the new keymap config

change 
```vim
" Floating stuff
noremap  <leader>t  :FloatermToggle<CR>i
noremap! <leader>t  <Esc>:FloatermToggle<CR>i
tnoremap <leader>t  <C-\><C-n>:FloatermToggle<CR>
```
to 
```vim
let g:floaterm_keymap_toggle = '<F12>'
```

Also see https://github.com/voldikss/vim-floaterm#keymaps

**Comment by mrprofessor** [comment]
`<CR>i` was the problem. I would still prefer `<leader>t ` though. Thanks

**Comment by voldikss** [comment]
Yes, you may also use 
```vim
let g:floaterm_keymap_toggle = '<Leader>t'
```
