### ISSUE TITLE
Abnormal word completion

### ISSUE THREAD

**Issue by heguohui2018** [voldikss/vim-floaterm#181]
I have two css attributes in the html file

<img width="862" alt="截屏2020-09-15 07 31 33" src="https://user-images.githubusercontent.com/35359288/93148242-deadbc80-f725-11ea-8cd8-5bb102074d5f.png">

These two attributes cannot be completed when used

<img width="1440" alt="截屏2020-09-15 07 37 24" src="https://user-images.githubusercontent.com/35359288/93148435-5b409b00-f726-11ea-9fe5-fd80d8073b1d.png">

**Comment by voldikss** [comment]
Sorry but this is not the bug of this plugin.
