### ISSUE TITLE
Current directory expansion

### ISSUE THREAD

**Issue by jemag** [voldikss/vim-floaterm#183]
Currently it is possible to have the current file path expanded using "%".

Would it be possible to have something equivalent for the current file directory?

Basically, currently my directory is automatically set using the root of the git repository, which is the behavior that I want 90% of the time. However, I sometimes would like to open other floating terminals within the current file directory.

So basically, I would like to do something like
`:FloatermNew! cd %`

but instead of %, have something expand to the current directory. I know that for opening floaterm in current directory the following is proposed https://github.com/voldikss/vim-floaterm/issues/152, however I do not want to interfere with the default behavior of opening at the root of the git repo. I would only like to open in the current file directory some of the time.

Hope that makes sense.

**Comment by adigitoleo** [comment]
@jemag 
Try `FloatermNew! cd %:p:h`, check also `:help filename-modifiers`.

**Comment by jemag** [comment]
it works! Thanks a lot, I did not know about filename-modifiers within vim.
