### ISSUE TITLE
Prevent quit if float term is open and script is running

### ISSUE THREAD

**Issue by Rizhiy** [voldikss/vim-floaterm#185]
Hi, I like to set time-consuming tasks running in floaterm (data-processing, model-training, etc.), which is usually fine.
But when I finish work at the end of the day, I quit vim automatically, without checking if all tasks are finished.

Is it possible to prevent vim from quitting if any floaterms are open and scripts are running?

**Comment by voldikss** [comment]
The plugin doesn't provide this feature out of box. You have to hack by yourself. You may get the process id after starting your tasks and using `pgrep` to check the status before quit vim(`autocmd VimLeave ...`)...
