### ISSUE TITLE
Escape to quit floaterm

### ISSUE THREAD

**Issue by PezCoder** [voldikss/vim-floaterm#187]
#### What?
I've been using floaterm with `nnn` for browsing files in the current directory, one of the things I'm used to is quitting the opened terminal windows whether it's` fzf`, `c-p` or `nnn`, using the `Escape` key or `C-[`.

Researched a little bit in the issues here but couldn't find anything. Turned out it's quite easy to do with an `autocmd`.

```
autocmd FileType floaterm tnoremap <buffer> <Esc> q
```

where 'floaterm' filetype is set by this library.

Not sure if it's the best way to achieve this, but does the job for me.
Putting here for reference so anybody with a similar use case can find the solution.

Thanks for the library!. You guys make VIM stay awesome.

**Comment by v0idpwn** [comment]
Didn't work here. I added the autocmd line to my vimrc

Am I missing something?

**Comment by PezCoder** [comment]
@v0idpwn What VIM version are you using.?

I'm using NEOVIM, so I'm not sure how this can differ for VIM. I can help explain the command so you can tweak it to your usecase:

`autocmd` - Autocommand identifier. VIM reads this during launch & register them
`FileType floaterm` - for the file type floaterm you can check this by doing `:set filetype?` in vim
`tnoremap <buffer>` - For terminal normal mode add a mapping
`<Esc>` - of Esc key to
`q` - triggers this, for me usually 'q' quits floaterm without any mapping hence I mapped my Esc to q.

**Comment by v0idpwn** [comment]
@PezCoder I'm using vim 8.2, I managed to do it through:
autocmd FileType floaterm nnoremap <buffer> <Esc> :q<CR>

**Comment by PezCoder** [comment]
That makes sense, I think terminal mode is specific to Neovim.
