### ISSUE TITLE
Why is floaterm hidding when switching tabs?

### ISSUE THREAD

**Issue by matheusfillipe** [voldikss/vim-floaterm#188]
I have multiple tabs in neovim which I would like to have different terminals on each. The problem is that when I switch tabs the floating terminal or pane (split) terminal that was on the previous tab gets hidden. Not sure if this is intentional, I would like to keep both panes with open terminals.

Have I missed some configuration option or this is not possible??

**Comment by voldikss** [comment]
It is expected behavior since a tab contains windows.
