### ISSUE TITLE
Error on list create: request error nvim_call_function: Invalid scroll size

### ISSUE THREAD

**Issue by lioaslan** [voldikss/vim-floaterm#190]
## Describe the bug

`[coc.nvim] Error on list create: request error nvim_call_function - Vim(set):E49: Invalid scroll size: scroll = 10`

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Install vim-floatterm, coc.nvim
- Run command `CocInstall coc-floaterm`
- Run `:FloatermNew` x 5 times to create 5 floaterm
- Run `:FloatermToggle` to hide all floaterm
- Run `CocList floaterm` and then show that error. I can't press any key except killing terminal to close Vim.
You can see more about my neovim configure here:  https://github.com/lioaslan/nvim

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/24852182/95672096-134b5180-0bc8-11eb-8e76-a3bee6ae5801.png)

**Comment by voldikss** [comment]
Sorry but I can not reproduce it.

In addition, you should find where the conflict lies by partly comment out your vimrc rather than provide your whole vimrc here.
