### ISSUE TITLE
Open vim-floaterm in background on startup?

### ISSUE THREAD

**Issue by david-amirault** [voldikss/vim-floaterm#191]
I have several FloatermSend mappings in my vimrc to interact with the current buffer, but they do no work if I haven’t toggled the floaterm twice since starting vim. Floaterm does not seem to include the functionality of a command to create a floaterm in the background without viewing it. If this functionality existed, it would also be easier to have mappings to kick off slow commands in a new background floaterm. Would this be possible to add?

**Comment by voldikss** [comment]
Use either
```vim
function! StartFloatermSilently() abort
  FloatermNew
  call timer_start(1, {-> execute('FloatermHide!')})
endfunction
autocmd VimEnter * call StartFloatermSilently()
```

Or 
```vim
function! StartFloatermSilently() abort
  FloatermNew
  FloatermToggle
  stopinsert
  wincmd o
endfunction
autocmd VimEnter * call StartFloatermSilently()
```

**Comment by voldikss** [comment]
Now it's better to use

```vim
autocmd VimEnter * FloatermNew --silent=1
```

**Comment by tristone13th** [comment]
> Now it's better to use
> 
> ```viml
> autocmd VimEnter * FloatermNew --silent
> ```

This seems not working in neovim?

**Comment by voldikss** [comment]
> 

Yes, it's been silently broken.

**Comment by tristone13th** [comment]
> 

Kindly ask, will this be fixed?

**Comment by voldikss** [comment]
> Kindly ask, will this be fixed?

Yes, i will fix it.
