### ISSUE TITLE
Opening a file through vifm in a new tab or split

### ISSUE THREAD

**Issue by maxigaz** [voldikss/vim-floaterm#192]
### Describe the bug

When I run `:FloatermNew vifm` and select a file, it always opens in the current buffer. I’ve been looking for an option to open it in a new tab or a split, but I haven’t found any.

In the screencast on the [project page](https://github.com/voldikss/vim-floaterm#vifm), I can see that the first file is opened in the current (empty) buffer and the second in a new tab. I haven’t been able to reproduce this yet.

By the way, [vifm.vim](https://github.com/vifm/vifm.vim) provides additional commands like `:TabVifm` and `:SplitVifm`, which work fine for me, but this plugin doesn’t use floating windows.

### To Reproduce

1. Install vim-floaterm through vim-plug
1. Use the minimal vimrc

   ```vim
   set nocompatible
   set hidden
   set termguicolors
   set runtimepath^=/path/to/vim-floaterm
   filetype plugin indent on
   syntax on
   ```

1. Run `:FloatermNew vifm`
1. Select any file

### Enviroment
 - OS [e.g. Arch Linux]: Manjaro Linux
 - Version [e.g. NVIM v0.5.0-fa9b057]: NVIM v0.4.4
 - Checkhealth info [run `:checkhealth` and post the messages]:

	<details>
		<summary>Click here to expand</summary>

		health#floaterm#check
		========================================================================
		  - OK: Terminal feature is OK
		  - OK: Floating window feature is OK
		  - OK: nvr is OK

		health#nvim#check
		========================================================================
		## Configuration
		  - OK: no issues found

		## Performance
		  - OK: Build type: Release

		## Remote Plugins
		  - OK: Up to date

		## terminal
		  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
		  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
		  - INFO: $COLORTERM='truecolor'

		health#provider#check
		========================================================================
		## Clipboard (optional)
		  - OK: Clipboard tool found: xclip

		## Python 2 provider (optional)
		  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
		  - ERROR: Python provider error:
			 - ADVICE:
				- provider/pythonx: Could not load Python 2:
					 /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
					 /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
					 python2.6 not found in search path or not executable.
					 /usr/bin/python is Python 3.8 and cannot provide Python 2.
		  - INFO: Executable: Not found

		## Python 3 provider (optional)
		  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
		  - INFO: Executable: /usr/bin/python3
		  - INFO: Python version: 3.8.5
		  - INFO: pynvim version: 0.4.2
		  - OK: Latest pynvim is installed.

		## Ruby provider (optional)
		  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
		  - WARNING: `neovim-ruby-host` not found.
			 - ADVICE:
				- Run `gem install neovim` to ensure the neovim RubyGem is installed.
				- Run `gem environment` to ensure the gem bin directory is in $PATH.
				- If you are using rvm/rbenv/chruby, try "rehashing".
				- See :help |g:ruby_host_prog| for non-standard gem installations.

		## Node.js provider (optional)
		  - INFO: Node.js: v14.12.0
		  - WARNING: Missing "neovim" npm (or yarn) package.
			 - ADVICE:
				- Run in shell: npm install -g neovim
				- Run in shell (if you use yarn): yarn global add neovim

	</details>

**Comment by voldikss** [comment]
Sorry but this won't be supported as it only brings a lot of complexities both for implementing and usage.

**Comment by MartinVincent** [comment]
Not exactly what the OP wants, but this might be of some help to some, as it permits opening a file in a new tab when in a floaterm popup:

> To open each buffer in its own tabpage, add this to your vimrc:
> :au BufAdd,BufNewFile * nested tab sball

source: https://vim.fandom.com/wiki/Open_every_buffer_in_its_own_tabpage
