### ISSUE TITLE
Auto indenet plus when send to floaterm when debug python

### ISSUE THREAD

**Issue by leoatchina** [voldikss/vim-floaterm#193]
### Descibe
I use floaterm as repl tool for python when using neovim（when vim, using vim-repl), but affter send lines linked  with `\`, 
or  a list covers multiple lines, the indents mass which sended to floaterm `indent plus one` 

### How to reproduce
Juse to `:FloatermSend`, type in commandline or using self-defined shortcut

### Enviroment
 - OS [e.g. Arch Linux]: Linux, Windows, MacOS
 - Version [e.g. NVIM v0.5.0-fa9b057]: nvim0.4.4
 - Checkhealth info [run `:checkhealth` and post the messages]:

### Screenshots(Optional, GIF is better)
![image](https://user-images.githubusercontent.com/4470821/95741260-8df79800-0cc0-11eb-944d-47152b9e2e5d.png)

![image](https://user-images.githubusercontent.com/4470821/95740847-cea2e180-0cbf-11eb-952f-a21a72761bb9.png)

**Comment by voldikss** [comment]
https://github.com/voldikss/vim-floaterm#incorrect-indent-when-using-floatermsend-with-ipython 
and
https://github.com/voldikss/vim-floaterm/issues/150
may help.
