### ISSUE TITLE
Does not work FloatermKill(I got `E16: Invalid range: 2hide`)

### ISSUE THREAD

**Issue by maeda1150** [voldikss/vim-floaterm#195]
### To Reproduce

- Use the minimal vimrc

```vim
call plug#begin('~/.vim/plugged')
Plug 'voldikss/vim-floaterm'
Plug 'voldikss/fzf-floaterm'
call plug#end()

let g:floaterm_keymap_toggle = '<c-t>'
let g:floaterm_keymap_prev = '<S-left>'
let g:floaterm_keymap_next = '<S-right>'
let g:floaterm_keymap_new = '<F12>'
let g:floaterm_height = 0.9
let g:floaterm_width = 0.9
let g:floaterm_keymap_kill = '<c-q>'
```

- Steps to reproduce the behavior:
  1. call `:FloatermNew`
  2. call `:FloatermToggle`
  3. call `:FloatermKill`
  4. then I got `E16: Invalid range: 2hide`

<img width="880" alt="Screen_Shot_2020-10-17_at_22_45_42" src="https://user-images.githubusercontent.com/4811459/96339140-8a537f00-10cd-11eb-8979-3af5a585742b.png">

### Enviroment

 - OS [e.g. Arch Linux]: macOS Catalina version 10.15.7
 - Version [e.g. NVIM v0.5.0-fa9b057]: Vim version 8.2.1250

### Possible causes

I recently updated vim-floaterm.
After the commit below, the behavior described earlier started to occur in my environment.
72de62c5dd9cc6acb67bdf7a1252bb2ec8838606

I debugged it at hand, I found that it occurred in `execute a: bufnr.'hide'` on line 322 of `autoload/floaterm/window.vim`.

https://github.com/voldikss/vim-floaterm/blob/06b188a26decf42a8ec01fe55447c33471684d3d/autoload/floaterm/window.vim#L311-L333

Is there anyone else in trouble?

**Comment by vdedios** [comment]
I have the same Issue when reproducing your steps. Also, same error when:

1. call :FloatermNew
2. call :FloatermToggle
3. call :FloatermNew

**Comment by vdedios** [comment]
Also when, creating two new terms and trying to move to the next/previous twice I get a `Invalid range: 3hide`. To reproduce it:

1.  call :FloatermNew
2. call :FloatermNew
3. call :FloatermNext (with custom binding <C-l>
4 call :FloatermPrevious (with custom binding <C-h>

**Comment by maeda1150** [comment]
The `hide` function accepts` winnr` instead of `bufnr`.
Therefore, I implemented the logic to convert from `bufnr` to` winnr` as follows.
What about this approach?

https://github.com/voldikss/vim-floaterm/pull/196/commits/f7304f727f9bc647bc5003c021e7fd0567cd6d01

When `g: floaterm_wintype` is` normal`, it has been confirmed that it works normally.

- minimal vimrc

```vim
call plug#begin('~/.vim/plugged')
Plug 'maeda1150/vim-floaterm', { 'branch': 'patch-hide_floaterm' }
Plug 'voldikss/fzf-floaterm'
call plug#end()

let g:floaterm_keymap_toggle = '<c-t>'
let g:floaterm_height = 0.5
```

- Steps to reproduce the behavior:

  1. call `:FloatermNew`
  1. `ctrl-t`(toggle)
  1. call `:FoatermNew`
  1. `ctrl-t`(toggle)
  1. call `:Floaterms`
  1. call `:FloatermKill!`
  1. call `:Floaterms`

![terms](https://user-images.githubusercontent.com/4811459/96363984-e3c1b980-1172-11eb-9fb9-764cf317576b.gif)

**Comment by vdedios** [comment]
I have implemented your changes and now seems to works flawlessly 👌

**Comment by voldikss** [comment]
Sorry for the late response. It seems #196 fixed this issue.
