### ISSUE TITLE
Float term bugs out GUI in terminal/neovim when using toggle

### ISSUE THREAD

**Issue by bragjo** [voldikss/vim-floaterm#199]
### Describe the bug

First of all - absolutely love this plugin, cannot live without it, it makes my whole workflow so much easier! Really good job on the plugin.

Float term is bugging out the GUI in terminal/neovim.
Text inside neovim is getting either removed/inserting weird characters or pushed away from the GUI, some text even end up in the line numbers and overrides their place. This happens when I toggle between neovim and the floaterm using this in my .vimrc:

let g:floaterm_keymap_toggle = '<F12>'

### To Reproduce

- Use the minimal vimrc
Tried without anytihng in my vimrc, this still happens. 

  ```vim
  set nocompatible
  set hidden
  set termguicolors
  set runtimepath^=/path/to/vim-floaterm
  filetype plugin indent on
  syntax on
  ```

- Steps to reproduce the behavior:
1. Open floaterm by toggling it
2. Running my localserver with something like parcel (yarn run dev)
3. Toggle close the floaterm window
4. Navigate to another file in nvim
5. The bug is there 60% of the time

### Enviroment
 - OS [e.g. Arch Linux]: Windows 10 (WSL)
 - Version [e.g. NVIM v0.5.0-fa9b057]: nvim v.0.4.3
 - Checkhealth info [run `:checkhealth` and post the messages]:

Everything is marked as "OK" and green, including nvr executable etc.

### Screenshots(Optional, GIF is better)

<img width="371" alt="Screenshot_126" src="https://user-images.githubusercontent.com/17138968/97086422-6fc85b00-1623-11eb-893a-cca4d0f8f65c.png">
<img width="937" alt="Screenshot_125" src="https://user-images.githubusercontent.com/17138968/97086423-7060f180-1623-11eb-87fd-085472d5397e.png">
<img width="947" alt="Screenshot_124" src="https://user-images.githubusercontent.com/17138968/97086424-7060f180-1623-11eb-8803-702d119e9bca.png">

**Comment by voldikss** [comment]
@bragjo Still exists? I don't use wsl so I can not reproduce it.
