### ISSUE TITLE
errors on start

### ISSUE THREAD

**Issue by tex** [voldikss/vim-floaterm#2]
Hi,try to run the command to trigger when with clean neovim config. You'll see some errors.
Also the example recommended setting to map F12 doesn't work as there is no util#toggleWindows.

Otherwise interesting concept!

**Comment by voldikss** [comment]
Thank you so much for this!

**Comment by voldikss** [comment]
> try to run the command to trigger when with clean neovim config. You'll see some errors.

BTW, could you give me more info about this

**Comment by tex** [comment]
Something about variable 
floaterm_winblend=0 not set.

**Comment by voldikss** [comment]
Thanks! It was fixed just now.

**Comment by tex** [comment]
It is still there, unknown option: winblend=0

**Comment by voldikss** [comment]
I get it, it's because your Nvim is a little old so it doesn't have `winblend` option

**Comment by tex** [comment]
Ok. Thanks.
