### ISSUE TITLE
[PR] - Adding a GIF for ipython use

### ISSUE THREAD

**Issue by a-elhag** [voldikss/vim-floaterm#200]
I have been using Floaterm + ipython for a while now and it has been amazing. I noticed on the landing page that there was a couple of GIFs showcasing it's use but none with ipython. If you would like that included, I could open up a Pull Request with a recording of my basic use cases. It would include:

1. Opening ipython on the side
2. Running a full file
3. Running a block of text
4. Showing the variables in the kernel
5. Clearing the screen
6. Resetting the kernel

**Comment by voldikss** [comment]
Yes, PR is highly welcomed.

**Comment by a-elhag** [comment]
Awesome, I'll open up a PR this weekend

**Comment by voldikss** [comment]
You may replace this  old gif
https://github.com/voldikss/vim-floaterm#python

**Comment by a-elhag** [comment]
I must've missed that it was using iPython, could've sworn it was a simple python shell.

In any case, I'll show my workflow using iPython and if you think it adds more then the original GIF then merge it.

**Comment by voldikss** [comment]
Hi @a-elhag , are you still here?

**Comment by voldikss** [comment]
Let me closed this and consider to reopen in the future if necessary.
