### ISSUE TITLE
can't execute with %<

### ISSUE THREAD

**Issue by zdmgmail** [voldikss/vim-floaterm#202]
```
func! Run()
	exec "w"
	if &filetype == 'c'
		exec "!g++ % -o %<"
		:term ./%<
	endif
endfunc
```

I used this function .  if change `:term` to `:FloatermNew`, only can use % but can't use %<

```
zsh:1: parse error near `<'
```

**Comment by voldikss** [comment]
Fixed. Also notice that this is not recommended by vim, maybe `:r` is better.

> This is included for backwards compatibility with version 3.0, the
":r" form is preferred.
