### ISSUE TITLE
How to bind the hide-floaterm shortcut key only if the floaterm floating window is open?

### ISSUE THREAD

**Issue by orlandoxu** [voldikss/vim-floaterm#203]
- Please make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.
yes
- Please make sure you are using the latest version of the plugin.
yes
- Please use English as far as possible.

### Describe the bug
I want to use the same shortcut in other floating window plugin. like Ctrl-T
If I set Ctrl-T to toggle floaterm, It may cause conflict when I use Ctrl-T in other floating window.
If I set g:floaterm_keymap_hide = '\<C-T\>' only, I got the err like:
[vim-floaterm] The floaterm does not exist

### To Reproduce

- Use the minimal vimrc

  ```vim
let g:floaterm_is_open = 0
function! CheckFzfOpen()
  if g:floaterm_is_open == 0
    let g:floaterm_is_open = 1
    :FloatermToggle
  elseif g:floaterm_is_open == 1
    let g:floaterm_is_open = 0
    :FloatermHide
  endif
endfunction

" let g:floaterm_keymap_toggle = '\<C-t\>'
let g:floaterm_keymap_hide = '\<C-T\>'
let g:floaterm_width=0.94
let g:floaterm_height=0.92
nnoremap \<silent\> \<C-t\> :call CheckFzfOpen()\<CR\>
  ```

- Steps to reproduce the behavior:
  1.
  2.
  3.
  4.

### Enviroment
 - OS [e.g. Arch Linux]: Mac Os x
 - Version [e.g. NVIM v0.5.0-fa9b057]: 10.15.7 
 - Checkhealth info [run `:checkhealth` and post the messages]:
health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - ERROR: nvr executable is not found, run `pip install neovim-remote` to install

**Comment by voldikss** [comment]
Use the following code in your `init.vim`

```vim
function Settings() abort
  " set mappings when opening
  tnoremap <F10> <C-\><C-n>:FloatermHide<CR>
  nnoremap <F10> :FloatermHide<CR>

  " clear mappings after hiding
  augroup floaterm-mappings
    autocmd!
    autocmd BufLeave <buffer> tunmap <F10>
    autocmd BufLeave <buffer> nunmap <F10>
  augroup END
endfunction

autocmd FileType floaterm call Settings()
```

**Comment by 9mm** [comment]
Here was my simpler solution, but it currently doesnt work with multiple project roots in different tabs, so I will need to revisit the drawing board

```lua
local function toggleFloaterm(args)
  local name = args:match('--name=([^%s]+)')
  local status = 'toggleterm_open_' .. name

  if vim.g[status] == nil then
    vim.cmd('FloatermNew ' .. args)
    vim.g[status] = 1
  elseif vim.g[status] == 1 then
    vim.cmd('FloatermHide ' .. name)
    vim.g[status] = 0
  else
    vim.cmd('FloatermShow ' .. name)
    vim.g[status] = 1
  end
end

return {
  'voldikss/vim-floaterm',
  config = function()
    vim.g.floaterm_title = ''

    -- https://github.com/neovide/neovide/issues/1838
    vim.keymap.set('t', '<MouseMove>', '<NOP>')
  end,
  keys = {
    {
      '<Leader>x',
      function() toggleFloaterm('--name=zsh --title=ZSH --autoclose=2 --width=0.7 --height=0.4') end,
      mode = { 'n', 't' },
      desc = 'ZSH shell',
    },
    {
      '<Leader>z',
      function() toggleFloaterm('--name=lazygit --width=0.98 --height=0.95 lazygit') end,
      mode = { 'n', 't' },
      desc = 'LazyGit',
    },
  },
}
```
