### ISSUE TITLE
Leader key delay in terminal

### ISSUE THREAD

**Issue by cyh0** [voldikss/vim-floaterm#206]
when set keymaps with leader, input leader key in terminal, there's a delay of one second, maybe it is timeoutlen.
the two way to set keymaps, the same problem.
then I set timeoutlen=50, but some keymaps don't work.
When I use Fn, everything works.

remark: neovim 0.5,
 leader key is space, I try "," , the same problem.

Here is Chinese translation:
使用leader 设置keymap， 在终端输入这个键延迟1秒，timeoutlen设置太低会导致一些keymap失效，所以此路不通。
两种映射方式都是一样的问题。
映射Fn是没有问题的，但是Fn资源紧张。
备注:最新的neovim 0.5， leader键设置什么都是一样的问题。

**Comment by voldikss** [comment]
Give me your whole config related to vim-floaterm.

Execute `:map <Leader>, show me the output.

**Comment by cyh0** [comment]
[mymaps.txt](https://github.com/voldikss/vim-floaterm/files/5567585/mymaps.txt)
config:
let g:floaterm_keymap_toggle = '<F8>'
let g:floaterm_keymap_prev   = '<leader>fp'
let g:floaterm_keymap_next   = '<leader>fn'
let g:floaterm_keymap_new    = '<leader>ft'
let g:floaterm_autoclose     = 1

**Comment by cyh0** [comment]
> Sorry for the mistake.
> 
> Execute `:map f` and show me the output.

No mapping found, with `:map f`

**Comment by cyh0** [comment]
> Sorry for the mistake.
> 
> Execute `:map f` and show me the output.

if you means `:map \ f` , there is nothing in the output

**Comment by voldikss** [comment]
> [mymaps.txt](https://github.com/voldikss/vim-floaterm/files/5567585/mymaps.txt)
> config:
> let g:floaterm_keymap_toggle = '<F8>'
> let g:floaterm_keymap_prev = '<leader>fp'
> let g:floaterm_keymap_next = '<leader>fn'
> let g:floaterm_keymap_new = '<leader>ft'
> let g:floaterm_autoclose = 1

It's wired. I cannot find any problems in your mappings.

**Comment by voldikss** [comment]
> input leader key in terminal, there's a delay of one second,

I see. You mean input a single `<Leader>`? In that case, the delay is expected because vim is waiting for the remaining keys.

**Comment by cyh0** [comment]
> > input leader key in terminal, there's a delay of one second,
> 
> I see. You mean input a single `<Leader>`? In that case, the delay is expected because vim is waiting for the remaining keys.

yes

**Comment by voldikss** [comment]
Then the problem got solved since it's a normal behavior.

**Comment by cyh0** [comment]
> Then the problem got solved since it's a normal behavior.

Oh,yes, I suddenly know the cause of the problem.

**Comment by Leandros** [comment]
> Then the problem got solved since it's a normal behavior.

Sorry for reviving an old topic, but is there a way to fix this? I have `<Space>` as `<Leader>` and it's very confusing to not see my spaces appear.

**Comment by voldikss** [comment]
> > Then the problem got solved since it's a normal behavior.
> 
> Sorry for reviving an old topic, but is there a way to fix this? I have `<Space>` as `<Leader>` and it's very confusing to not see my spaces appear.

`:help map-buffer` and `:help map-nowait` may helps

**Comment by Pheon-Dev** [comment]
For those still having the same problem try disabling the `tnoremap` keybindings and just use `nnoremap`
  ```vim
nnoremap   <silent>   <leader>;    :FloatermNew! lf<CR>
  " tnoremap   <silent>   <leader>;    <C-\><C-n>:FloatermNew! lf<CR>
```
