### ISSUE TITLE
Keep the cursor style inside the floating window

### ISSUE THREAD

**Issue by nikolalsvk** [voldikss/vim-floaterm#207]
Hello there, nice plugin, I love it!

I was wondering if there is a possibility to keep the cursor style inside the floating window? For example, my cursor is a blinking bar but when I open the floating window with fzf's `:Ag`, it changes to a steady block.

For example, my bar bursor:
<img width="816" alt="Screenshot 2020-11-19 at 17 01 45" src="https://user-images.githubusercontent.com/3028124/99691155-33084c00-2a89-11eb-934d-8b475e9dd9fa.png">

And cursor when I open the window:
<img width="817" alt="Screenshot 2020-11-19 at 17 01 29" src="https://user-images.githubusercontent.com/3028124/99691204-40bdd180-2a89-11eb-8fc3-0615dfcdb853.png">

Right now, I am using some hacky solution which resets my cursor bar after I get back to Vim:

```vim
let &t_SI = "\e[6 q"
let &t_EI = "\e[6 q"

" Optionally reset the cursor on start:
augroup myCmds
au!
autocmd VimEnter * silent !echo -ne "\e[6 q"
augroup END
```

I use Vim `8.2.654` in iTerm2 `3.4.1`.

Thanks for the work here!

**Comment by voldikss** [comment]
Sorry but I don't know how to achieve that. Maybe your should go to vim official repo's issue region to look for the answer.
