### ISSUE TITLE
[feature request] support error format

### ISSUE THREAD

**Issue by MaiLunJiye** [voldikss/vim-floaterm#211]
Thanks for your plugin making terminal graceful.
I hope it can support `errorformat` and jump to the code by `Ctrl-]` in normal mode, like vscode using ctrl+left mouse on the  terminal.
It is usefull to locate the error when running the code and rasing errors.

If it can, it will replace quickfix, and do better than quickfix.

**Comment by voldikss** [comment]
Sounds like the same demand as #208

**Comment by voldikss** [comment]
closed by 4691f3b. I think #208 covers this case.

**Comment by voldikss** [comment]
Please see https://github.com/voldikss/vim-floaterm/issues/208#issuecomment-747829311
