### ISSUE TITLE
bug with line numbers turned on in vim

### ISSUE THREAD

**Issue by stokhos** [voldikss/vim-floaterm#212]
- Please make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

- Please make sure you are using the latest version of the plugin.

- Please use English as far as possible.

### Describe the bug
I have relative line numbers turned on.

1. toggle on floaterm, there is no line numbers in floaterm.
2. change focus to firefox, then change focus back to neovim. line numbers shows up in floaterm.

### To Reproduce

- Use the minimal vimrc

  ```vim
  set nocompatible
  set hidden
  set termguicolors
  set runtimepath^=/path/to/vim-floaterm
  filetype plugin indent on
  syntax on
  set number
  set relativenumber
  ```

- Steps to reproduce the behavior:
  1. toggle on floaterm, there is no line numbers in floaterm.
  2. change focus to firefox, then change focus back to neovim. line numbers shows up in floaterm.

### Enviroment
 - OS [e.g. fedora 33]:
 - Version [e.g. NVIM v0.4.4.0]:
 - Checkhealth info [run `:checkhealth` and post the messages]:

health#coc#check
  2 ========================================================================
  3   - OK: Environment check passed
  4
  5   - OK: Javascript bundle build/index.js found
  6   - OK: Service started
  7
  8 health#floaterm#check
  9 ========================================================================
 10   - OK: Terminal feature is OK
 11   - OK: Floating window feature is OK
 12   - OK: nvr is OK
 13
 14 health#nvim#check
 15 ========================================================================
 16 ## Configuration
 17   - OK: no issues found
 18
 19 ## Performance
 20   - OK: Build type: RelWithDebInfo
 21
 22 ## Remote Plugins
 23   - OK: Up to date
 24
 25 ## terminal
 26   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
 27   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
 28   - INFO: $COLORTERM='truecolor'
 29
 30 health#provider#check
 31 ========================================================================
 32 ## Clipboard (optional)
 33   - OK: Clipboard tool found: wl-clipboard
 34
 35 ## Python 2 provider (optional)
 36   - INFO: Using: g:python_host_prog = "/usr/bin/python2"
 37   - ERROR: "/usr/bin/python2" was not found.
 38   - INFO: Executable: Not found
 39   - ERROR: Detected pip upgrade failure: Python executable can import "pynvim" but not "neovim": /usr/      bin/python2
 40     - ADVICE:
 41       - Use that Python version to reinstall "pynvim" and optionally "neovim".
 42           pip uninstall pynvim neovim
 43           pip install pynvim
 44           pip install neovim  # only if needed by third-party software
 45
 46 ## Python 3 provider (optional)
 47   - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
 48   - INFO: Executable: /usr/bin/python3
 49   - INFO: Python version: 3.9.0
 50   - INFO: pynvim version: 0.4.2
 51   - OK: Latest pynvim is installed.
 52
 53 ## Ruby provider (optional)
 54   - WARNING: `ruby` and `gem` must be in $PATH.

**Comment by voldikss** [comment]
Can not reproduce. There must be a `FocusGained` auto command setting in your config.

What's the output of `autocmd FocusGained`?

**Comment by voldikss** [comment]
I am going to close this and you can keep on comment if you get that output.

**Comment by stokhos** [comment]
Yes I do have FocusGained in my vimrc. Thank you very much.

**Comment by stokhos** [comment]
```vim
augroup numbertoggle   
  autocmd!                                                   
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber                       
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END 
```
Is there a way to have these turned off in vim-floaterm?
@voldikss

**Comment by voldikss** [comment]
![Screenshot_20201201-074717](https://user-images.githubusercontent.com/20282795/100679236-08cc5d80-33aa-11eb-95da-74a3b450b91f.png)
