### ISSUE TITLE
[bug] FloatermSend %

### ISSUE THREAD

**Issue by Freed-Wu** [voldikss/vim-floaterm#216]
### Describe the bug

Some language, like matlab/octave, use % as comment character. however, `:FloatermSend` will convert % to the filename.

This is an example:

new a file named 'foobar.m'. open a floatterm

```{.vim}
FloatermSend % this is a comment of matlab
```

the terminal will display 

```
parse error:

  syntax error

>>> foobar.m this is a comment of matlab
```

**Comment by Freed-Wu** [comment]
i recommend to add a preprocess: convert % to %%, because vim will convert %% to %.

**Comment by voldikss** [comment]
As is pointed out in the readme, you could use `\%`

**Comment by Freed-Wu** [comment]
i try `:FloatermSend \%` and it sends '\%' to the terminal. execuse me, how
can i send only a '%' to terminal?

**Comment by voldikss** [comment]
> i try `:FloatermSend \%` and it sends '%' to the terminal. execuse me, how
> can i send only a '%' to terminal?

Sorry? I don’t quite understand

**Comment by Freed-Wu** [comment]
Sorry for my typo QAQ

After

```{.vim}
FloatermSend \%
```

the result is

```
\%
```

not

```
%
```

how can i get `%`?

**Comment by voldikss** [comment]
> Sorry for my typo QAQ
> 
> After
> 
> ```
> FloatermSend \%
> ```
> 
> the result is
> 
> ```
> \%
> ```
> 
> not
> 
> ```
> %
> ```
> 
> how can i get `%`?

Really?! Hmmm, that might be a bug. I'll look into this after my laptop gets repaired.

**Comment by Freed-Wu** [comment]
this is a screenshot. i have deleted all comment contains % of my matlab code to avoid it.
![image](https://user-images.githubusercontent.com/32936898/101179704-8bdd0480-3685-11eb-95eb-16426631053f.png)
