### ISSUE TITLE
TUI apps glitch in floaterm when sidescrolloff option is set in neovim

### ISSUE THREAD

**Issue by laszloszurok** [voldikss/vim-floaterm#218]
Hi! I would like to report an issue that I found during using this plugin.

### Description
When opening TUI apps, such as vifm, lazygit, ncspot, etc., the interface inside the terminal window will behave weirdly if the vim option 'sidescrolloff' is set to a number greater than 3. For example in the case of vifm, if you move through files, the interface will randomly jump to the left and you only will be able to see the right side of vifm. If you move through directories, everything is fine tough. I also tried the process viewer called bottom. In the case of bottom, the whole interface is shifted to the left when I open it. Same with ncspot. The greater sidescrolloff is set to, the more the applications inside the floaterm window are shifted to the left. If I turn off sidescrolloff the issue is gone.

### To Reproduce
1. execute these command inside neovim:
```vim
set nowrap
set siso=999
```
(nowrap is needed becouse siso(=sidescrolloff) is only turned on if nowrap is set)

2. then open vifm in a floaterm window (or any other TUI application):
```vim
FloatermNew vifm
```
3. in case of vifm scroll through files with j and k

### Enviroment
 - Arch Linux:
 - NVIM v0.4.4
 - Checkhealth info:

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - ERROR: nvr executable is not found, run `pip3 install neovim-remote` to install

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.9.1
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v15.4.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Screenshots

![example](https://user-images.githubusercontent.com/48314396/102687107-fc8b3180-41ec-11eb-8786-6e4e043ece63.gif)

![2020-12-19-103053_1920x1080_scrot](https://user-images.githubusercontent.com/48314396/102687120-188ed300-41ed-11eb-8346-c65803694007.png)

**Comment by gennaro-tedesco** [comment]
I observe the exact same behaviour as described above, therefore I endorse this issue. 

# Environment

- macOS Big Sur
- NVIM v0.4.4
- checkhealth as given by user above

# Screenshots

https://user-images.githubusercontent.com/15387611/103044313-5d659180-4580-11eb-9307-c3d536719bd3.mov
