### ISSUE TITLE
shell keyboard type <C-w> to delete word, error: E994: Not allowed in a popup window

### ISSUE THREAD

**Issue by seanzxg** [voldikss/vim-floaterm#220]
### Describe the bug
Open floaterm, type a few words, and use <C-w> delete the word, error：E994: Not allowed in a popup window

### To Reproduce

- Use the minimal vimrc

  ```vim
" floaterm config
let g:floaterm_keymap_toggle = '<leader>\'
let g:floaterm_height = 0.8
let g:floaterm_width = 0.8
let g:floaterm_height = 0.8
let g:floaterm_rootmarkers = ['.git', '.gitignore']
let g:floaterm_autoclose = 2

  ```

- Steps to reproduce the behavior:
  1.FloatermToggle
  2. type 'yarn add name'
  3.c-w 
  4. error: Not allowed in a popup window

### Enviroment
 - macos 0.15.7
 - mvim Vi IMproved 8.2 (2019 Dec 12, compiled Dec 19 2020 21:23:05)

**Comment by voldikss** [comment]
Hi, solved? This seems  a issue of vim.

**Comment by alps2006** [comment]
You can change the `termwinkey` to other .

```vim
" Resoving `E994: Not allowed in a popup window only in vim.`
autocmd User FloatermOpen if exists('&termwinkey') | call setbufvar(bufnr('%'), '&termwinkey', '<c-z>') | endif

```
