### ISSUE TITLE
open floaterm with sourced .zshrc 

### ISSUE THREAD

**Issue by joe23rep** [voldikss/vim-floaterm#221]
hi, id like to ask if it would be possible that floaterm reads the .zshrc file before it opens?

the thing is ive set up my fzf and preview fzf via my .zshrc file. floaterm doesnt seem to read these parameters at all. it must read something because the prompt theme is correct but somehow the fzf stuff isnt. 

ive set up my files this way that they open via neovim. for that i created a neovim.desktop file and added this command:

/usr/bin/alacritty -e zsh -c '. ~/.zshrc; nvim %f' 2>/dev/null

using that i force it to open my terminal but source the .zshrc file first. would something like this be possible with floaterm as well?

**Comment by voldikss** [comment]
If you have set `g:floaterm_shell` to `zsh`, when floaterm opens it should reads and loads your `.zshrc`.

**Comment by voldikss** [comment]
> the thing is ive set up my fzf and preview fzf via my .zshrc file. floaterm doesnt seem to read these parameters at all.

What if you just using the builtin command `:terminal` or `split term://zsh`?

**Comment by joe23rep** [comment]
the more i think about it the more i think its not the issue of flaterm. tried to set it to ...shell='zsh' but the behaviour stays the same. 

BUT its only this way when im at the dashboard plugin (basically a startpage plugin like startify but its directly combined with fzf).

the  ore i think about it i have the feeling it has something to do with that plugin, cuz when i dont press enter on the options but use the corrosponding shortcuts floaterm shows me the correct colors again. the issue only seems to happen when im not using the shortcuts but click enter on one of the options. but then it stays the same for the whole session. if i do that one floaterm never comes back to the .zshrc file config. 

i think the easiest method would be to use the shortcuts instead of manually selecting an option. 

i had hoped there would be an easy fix i could implement within 2 minutes but its not this important that id now start going threw the dashboard plugin files.

**Comment by voldikss** [comment]
Ok, so remove dashboard and the issue gets solved? I'll close this issue.
