### ISSUE TITLE
CMD executes with $SHELL but not otherwise

### ISSUE THREAD

**Issue by ArcherN9** [voldikss/vim-floaterm#222]
- [x] Please make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first. 
- [x] Please make sure you are using the latest version of the plugin.
- [x] Please use English as far as possible.

### Describe the bug
The project ReadMe provides a tiny example of compiling a C program like so:
```
" The following command allows you to compile and run your C code in the floaterm window:
:FloatermNew --autoclose=0 gcc % -o %< && ./%<
```
I'm attempting to create something similar using a key binding. F4 should execute my single Kotlin file that has already been compiled through the inbuilt `:make` command. To support some extra information during runtime, I want to display out which file is being executed, making use of ANSI escape codes (or `tput`). Its quite useful when working on multiple files and they need to be executed individually during debug.

An excerpt from my `.vimrc`:
```vim
    execute 'FloatermNew --title=Executing\ '.expand('%').'\ ($1/$2) --autoclose=0
                \ GREEN="\033[0;32m" &&
                \ NC="\033[0m\" &&
                \ echo ${GREEN}\[Executing\]${NC} '.expand('%:p').' && 
                \ echo ----------------------------------- &&
                \ java -jar '.expand('%').'.jar'
```
However, this is the output.
<img width="1317" alt="Screenshot 2020-12-31 at 7 02 11 PM" src="https://user-images.githubusercontent.com/8784713/103412352-b940a380-4b9a-11eb-8ee5-7fa3b952fc9c.png">

If I add an `!` and execute it in $SHELL, the output is as expected. However, A repition on Line 1 is a bit of a turnoff. So is when it appears against my Karat (Carat?).

<img width="897" alt="Screenshot 2020-12-31 at 7 07 39 PM" src="https://user-images.githubusercontent.com/8784713/103412513-792df080-4b9b-11eb-8015-f9702bf1387c.png">

1. In an ideal scenario, I should be able to execute it without an `!`. That's not working.
2. I could tolerate this with `!` and the verbosity against the Karat, but a redundancy with line 1 is aggrevating. How do we remove that?

### To Reproduce

- I've provided my .vimrc excerpt. Please add that in yours to test and replace `java -jar xxx` execution line. That is not really important to recreate this.
- Try the excerpt with and without `!`

A more plug and play .vimrc to this may be used as follows:

```vim
augroup kotlin
   autocmd!
   autocmd FileType kotlin nnoremap <F4> :call <SID>KotlinExecute() <CR>
augroup END

function! s:KotlinExecute()
    execute 'FloatermNew! --title=Executing\ '.expand('%').'\ ($1/$2) --autoclose=1
                \ GREEN="\033[0;32m" &&
                \ NC="\033[0m" &&
                \ echo ${GREEN}\[Executing\]${NC} '.expand('%').' && 
                \ echo -----------------------------------'
endfunction

```

### Enviroment
 - OS: Mac OS 10.14.6 [Let me know if I should try this on Arch/Raspi. I can do that]
 - Version: Vim 8.2, Included patches: 1-2105
 - Checkhealth info: Unavailable on vim.

### Screenshots

1. Don't know if its relevant. But anyway.
<img width="543" alt="Screenshot 2020-12-31 at 7 14 08 PM" src="https://user-images.githubusercontent.com/8784713/103412698-6a940900-4b9c-11eb-9265-50f96da74cf8.png">

**Comment by voldikss** [comment]
1. I've tested neovim, both `:FloatermNew` and `:FloatermNew!` works fine
2. For vim8, `:FloatermNew` won't work, that's not a bug of the plugin, because if you run `call term_start('GREEN="\033[0;32m"', {})` and you will get the same error as shown above. However, `:FloatermNew!` works

**Comment by voldikss** [comment]
Maybe you could try using nvim but it's OK if you insist on vim8. Both are fine but in some specific cases one does better than another.

**Comment by ArcherN9** [comment]
I see. Well, I haven't used Nvim. Its unchartered territory right now. I'll just use it with `!` in that case.

On a different note, My current key bind is:
```vim
    execute 'FloatermNew! --title=Executing\ '.expand('%').'\ ($1/$2) --autoclose=0
                \ GREEN="\033[0;32m" && 
                \ YELLOW="\033[1;33m" &&
                \ L_GREY="\033[0;37m" &&
                \ clear &&
                \ echo \\\n\\\n${GREEN}\[Executing\]${YELLOW} '.expand('%:p').' &&
                \ echo ${L_GREY}----------------------------------- &&
                \ java -jar '.expand('%').'.jar'
```

I keep receiving `Too many arguments for function floaterm#run` when I execute it. However, If I remove `\clear &&`, it runs perfectly fine. If I replace it with `\ echo test execution &&`, I receive the same error. 

Comments?

**Comment by voldikss** [comment]
Sorry but I have no idea for this, either.
