### ISSUE TITLE
Floaterm text all jumbled after toggle

### ISSUE THREAD

**Issue by D3REKZHANG** [voldikss/vim-floaterm#229]
### Describe the bug
Floaterm gets messed up after using FloatermToggle.

### To Reproduce

- Use the minimal vimrc

```vim
" Vim Plug
call plug#begin('~/AppData/Local/nvim-data/plugged')
    Plug 'voldikss/vim-floaterm'
call plug#end()

let g:floaterm_autoclose=1
let g:floaterm_title=""
let g:floaterm_shell="powershell.exe -NoLogo"

tnoremap <silent> <F12> <C-\><C-n>:FloatermToggle<CR>
noremap <silent> <F12> :FloatermToggle<CR>
```

- Steps to reproduce the behavior:
  1. map any key with tnoremap to <C-\\>\<C-N>:FloatermToggle\<CR>
  2. open floaterm with :FloatermToggle
  3. run any command that produces output with lines wrapped.
  4. toggle it off with the remap key (F12 in my case)
  5. Reopen with :FloatermToggle

### Enviroment
 - Windows 10, PowerShell on Windows Terminal
 - NVIM v0.4.0:
 - Checkhealth info [run `:checkhealth` and post the messages]:
 Everything is good except for missing optional Python 2 dependancy.

### Screenshots(Optional, GIF is better)
![example](https://user-images.githubusercontent.com/20462187/103851203-2eb6e300-5077-11eb-8d07-1d25e5cd8542.gif)
Weird because it works fine if I don't use the keybind:
![example2](https://user-images.githubusercontent.com/20462187/103854893-7a6d8a80-507f-11eb-95a6-cec95733a0f2.gif)

**Comment by voldikss** [comment]
What if using normal floaterm? i.e., `let g:floaterm_wintype = 'normal'`

**Comment by D3REKZHANG** [comment]
It seems to work fine with wintype normal

**Comment by voldikss** [comment]
Then I feel that is the problem of the incompability between terminal and nvim. Sadly I have no workaround right now.

**Comment by D3REKZHANG** [comment]
Alright thanks anyways.

**Comment by voldikss** [comment]
~~

**Comment by D3REKZHANG** [comment]
Actually do you have any idea why it specifically doesn't work when I bind it to a keybind. It behaves normally if i manually do 
<C-\\>\<C-N>:FloatermToggle\<CR>

**Comment by voldikss** [comment]
You mean 
```vim
tnoremap <silent> <F12> <C-\><C-n>:FloatermToggle<CR>
noremap <silent> <F12> :FloatermToggle<CR>
```
doesn't work for you?

**Comment by D3REKZHANG** [comment]
The jumbled output only happens when I use the F12 keybind. If I manually type ctrl \ ctrl n then type :FloatermToggle it does not mess up the text. You can see in the second gif.

**Comment by voldikss** [comment]
No idea about that.

**Comment by kalvinpearce** [comment]
Interestingly I get this issue even with `let g:floaterm_wintype = 'normal'` set 🤔 I am also using windows and powershell and also working correctly only when manually escaping/toggling
