### ISSUE TITLE
退出VIM的时候会提示终端还有任务没完成

### ISSUE THREAD

**Issue by gVimer** [voldikss/vim-floaterm#230]
WIN10+gVim8.2+最新版插件
先执行FloatermToggle打开一个终端 再次执行FloatermToggle隐藏终端 然后关闭VIM会弹出如下提示
![image](https://user-images.githubusercontent.com/6241431/104114049-07903800-533b-11eb-869a-27e5eca07a29.png)
可以不弹这个提示吗

**Comment by voldikss** [comment]
是更新后出现的还是一直就有呢

**Comment by gVimer** [comment]
之前没怎么用 昨天更新了做了些配置 挺好的  就是每次退出VIM的时候就弹这个 有点烦

**Comment by voldikss** [comment]
Windows 上面好像 kill stop 的时候就会弹窗，这个无解。

**Comment by danjian** [comment]
NERDTree & floaterm works for me and I have the same problem too,finally it works by the below codes in my .vimrc
```
function! s:kill_all_floaterm() abort
    for bufnr in floaterm#buflist#gather()
      call floaterm#terminal#kill(bufnr)
    endfor
    return
endfunction

autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree()  | call s:kill_all_floaterm() | quit | endif
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | call s:kill_all_floaterm() | quit | endif
```
it means that floaterm proccess should be killed before quit . the code above do something more then kill all floaterm proccess just as the document NERDTree says

**Comment by gVimer** [comment]
哦 没怎么用这个插件了 因为我是在Win下面用的gVim 这个悬浮终端支持不是很好 等VIM9.0的版本出来以后再看
目前用的是这个插件 SKYWIND3000/VIM-TERMINAL-HELP

**Comment by danjian** [comment]
嗯嗯，希望能给遇到的人一点帮助。

**Comment by voldikss** [comment]
Thanks @danjian 

Actually `:FloatermKill!`(it means kill all floaterm instances) should be prefered
