### ISSUE TITLE
Getting Error:  Funcref variable Name must start with capital : val in gvim8.2

### ISSUE THREAD

**Issue by oaabhilash** [voldikss/vim-floaterm#233]
#### Steps to reproduce
Toggle the terminal couple of times

I was able to fix this by updating the floaterm#buffer#get_config_dict function's "val" variable to start with upper case "Val" in my local instance

FileName: autoload\floaterm\Buffer.vim

Function after update

```
function! floaterm#buffer#get_config_dict(bufnr) abort
  let config = {}
  for [key, Val] in items(getbufvar(a:bufnr, ''))
    if key =~ 'floaterm_'
      let config[key[9:]] = Val
    endif
  endfor
  return config
endfunction
```
I am not experienced in vimscript to check if there are any other side effects for this. 

Thank you for this great plugin

**Comment by voldikss** [comment]
This must be caused by another plugin

**Comment by voldikss** [comment]
Fixed.

**Comment by oaabhilash** [comment]
Thank you.
