### ISSUE TITLE
Incorrect error message when an integer height value is used

### ISSUE THREAD

**Issue by Keating950** [voldikss/vim-floaterm#235]
### Describe the bug
When `g:floaterm_height` is set to an integer value, the error message states that an integer value is required, when in fact, a float is required.

### Error output

```
Error detected while processing function floaterm#toggle[30]..floaterm#curr[3]..floaterm#new[22]..floaterm#terminal#open[24]..<SNR>53_spawn_terminal[8]..floaterm#window#open[6]..<SNR>50_open_float:
line   10:
E5555: API call: 'height' key must be a positive Integer  
```

- Steps to reproduce the behavior:
1. Set  `g:floaterm_height` to `1`
2. Open floaterm

**Comment by voldikss** [comment]
floaterm height includes both the terminal height and the border height. So it should be given at least 3(1 for terminal + 1 for top border + 1 for bottom border).
