### ISSUE TITLE
Ctrl-C kill job and floaterm

### ISSUE THREAD

**Issue by grimgort** [voldikss/vim-floaterm#236]
### Describe the bug
Ctrl-C keymap kill terminal (floaterm) with the current job. I was hoping it would only kill the job.
shel usedl is posershell
Great plugin ! Thanks

### Enviroment
 - OS [e.g. Arch Linux]: windows10 
 - Version [e.g. NVIM v0.5.0-fa9b057]: nvim 0.4.0
 - Checkhealth info [run `:checkhealth` and post the messages]:

### Screenshots(Optional, GIF is better)
![image](https://user-images.githubusercontent.com/44238325/105335173-059a6480-5bd8-11eb-821f-dd0c8d2d3913.png)

**Comment by voldikss** [comment]
What's g:floaterm_autoclose

**Comment by voldikss** [comment]
Set g:floaterm_autoclose to 1 or 2
