### ISSUE TITLE
Not an editor command: bottom10split

### ISSUE THREAD

**Issue by bergtholdt** [voldikss/vim-floaterm#238]
After updating to the latest version using VimPlug (:PlugUpdate) I get the following error:

```
:FloatermNew --wintype=normal --position=bottom --height=10

Error detected while processing function floaterm#run[3]..floaterm#new[21]..floaterm#terminal#open[19]..<SNR>197_spawn_terminal[8]..floaterm#window#open[12]
..<SNR>199_open_split:
line    2:
E492: Not an editor command: bottom10split
```

Before the update today (last update last week) it worked without error.

`NVIM v0.5.0-dev+950-g5ce328df4`

**Comment by voldikss** [comment]
Fixed. 

P.S. Sorry I recently made some breaking change. There are a little changes for the values for `--wintype` and `--position`. You could use `<Tab>` to get command arguments completion and learn about that.
