### ISSUE TITLE
Duplicated lines when using FloatermSend with a range

### ISSUE THREAD

**Issue by strboul** [voldikss/vim-floaterm#241]
I use floaterm as REPL to send lines from the source to the terminal. `:FloatermSend` works great to send lines, but the selection send with range behaves weird as it duplicates the lines.

I have a script:
```vim
function! s:REPLSendLine()
  FloatermSend --name=REPL
endfunction

function! s:REPLSendSelection()
  '<,'>FloatermSend --name=REPL
endfunction

nnoremap <silent><leader><CR> :call <SID>REPLSendLine()<CR>
vnoremap <silent><leader><CR> :call <SID>REPLSendSelection()<CR>
```

Thanks for floaterm, it's great :heart:

**Comment by voldikss** [comment]
@strboul I can not reproduce the issue, could you supply a gif or example?

**Comment by strboul** [comment]
@voldikss First, I sent lines via `<SID>REPLSendLine()` one by one, and it worked just fine. Second, I sent the visual selection via `<SID>REPLSendSelection()`. As you see in the GIF, each line was duplicated 3 times, which is equal to the number of lines in the visual selection, and that resulted in a total of 9 lines were sent to the terminal, whereas only 3 lines were visually selected.

![floaterm](https://user-images.githubusercontent.com/25015317/106281587-b390b900-623f-11eb-86d3-7a02fc0be024.gif)

**Comment by voldikss** [comment]
It's caused by your function.


```diff
 function! s:REPLSendSelection()
-  '<,'>FloatermSend --name=REPL
+ FloatermSend --name=REPL
 endfunction
```

**Comment by voldikss** [comment]
If the above patch doesn't solve you can reopen the issue.

**Comment by strboul** [comment]
Thanks for the response again. Unfortunately, that doesn't solve it because I still need the ability to run the text partially e.g. `var = 5`, and I want to be able to select `var` by moving the cursor onto it, type `viw`, and then call `REPLSendSelection()` to send `var` to the terminal.

So I need the selection `'<,'>FloatermSend`, which works well with the partial text, but weird duplicates happen if multiple lines are selected as shown in the GIF.

**Comment by voldikss** [comment]
`s:REPLSendSelection` should still works like before.

**Comment by strboul** [comment]
It works just fine if I change the mapping to:

```diff
- vnoremap <silent><leader><CR> :call <SID>REPLSendSelection()<CR>
+ vnoremap <silent><leader><CR> :'<,'>FloatermSend --name=s:repl_toggle_term_name<CR>
```

No idea why it does weird duplication if the it's call via the function `REPLSendSelection()`.

**Comment by voldikss** [comment]
It's caused by `'<,'>` in the function `s:REPLSendSelection`

When you use this mapping 

```vim
vnoremap <silent><leader><CR> :call <SID>REPLSendSelection()<CR>
```

It will generate 2  `'<,'>`.

But if you use this
```vim
vnoremap <silent><leader><CR> :<C-u>call <SID>REPLSendSelection()<CR>
```

I guess it will be fine.

**Comment by voldikss** [comment]
Anyway, no need to stick to this issue anymore since it gets fixed.

**Comment by strboul** [comment]
@voldikss Thanks, adding `<C-u>` definitely solved it!
