### ISSUE TITLE
Can't use <C-f>, <C-b>, <C-e>, <C-a> in floaterm

### ISSUE THREAD

**Issue by tomato-300yen** [voldikss/vim-floaterm#242]
### Describe the bug
I can use `<C-h>` key-binding, however, can't use `<C-f>`, `<C-b>`, `<C-e>`, `<C-a>` key-bindings to move around in floaterm.

Is there any reason for that?

### To Reproduce

- Steps to reproduce the behavior:
  1. Execute ':FloatermNew --floaterm_wintype="popup"' in NVIM

### Enviroment
 - OS : macOS Big Sur 11.1
 - Version : NVIM v0.4.0
 - Checkhealth info: listed below

> health#coc#check
> ========================================================================
>   - OK: Environment check passed
> 
>   - OK: Javascript bundle build/index.js found
>   - OK: Service started
> 
> health#rnvimr#check
> ========================================================================
> ## OS
>   - OK: Name: Mac
> 
> ## Ranger
>   - OK: Version: ranger 1.9.3
> 
> ## Python
>   - OK: Version: 3.8.2 (default, Jul 17 2020, 16:45:41) [Clang 11.0.3 (clang-1103.0.32.62)]
> 
> ## Pynvim
>   - OK: Version: 0.4.2
> 
> ## Ueberzug (optional)
>   - INFO: Ueberzug is not support for Mac
> 
> ## RPC
> --- サイン ---
> 
>   - OK: RPC echo: Neovim send "Give me five!" and receive "Give me five!"
> 
> health#floaterm#check
> ========================================================================
>   - OK: Terminal feature is OK
>   - OK: Floating window feature is OK
>   - ERROR: nvr executable is not found, run `pip3 install neovim-remote` to install
> 
> health#nvim#check
> ========================================================================
> ## Configuration
>   - OK: no issues found
> 
> ## Performance
>   - OK: Build type: Release
> 
> ## Remote Plugins
>   - OK: Up to date
> 
> ## terminal
>   - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
>   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
>   - INFO: $COLORTERM='truecolor'
> 
> health#provider#check
> ========================================================================
> ## Clipboard (optional)
>   - OK: Clipboard tool found: pbcopy
> 
> ## Python 2 provider (optional)
>   - INFO: pyenv: Path: /usr/local/Cellar/pyenv/1.2.21/libexec/pyenv
>   - INFO: pyenv: Root: /Users/uu/.pyenv
>   - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
>   - ERROR: Python provider error:
>     - ADVICE:
>       - provider/pythonx: Could not load Python 2:
>           /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
>           /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
>           python2.6 not found in search path or not executable.
>           /Users/uu/.pyenv/shims/python is Python 3.8 and cannot provide Python 2.
>   - INFO: Executable: Not found
> 
> ## Python 3 provider (optional)
>   - INFO: pyenv: Path: /usr/local/Cellar/pyenv/1.2.21/libexec/pyenv
>   - INFO: pyenv: Root: /Users/uu/.pyenv
>   - INFO: Using: g:python3_host_prog = "/Users/uu/.pyenv/shims/python"
>   - INFO: Executable: /Users/uu/.pyenv/shims/python
>   - INFO: Python version: 3.8.2
>   - INFO: pynvim version: 0.4.2
>   - OK: Latest pynvim is installed.
> 
> ## Ruby provider (optional)
>   - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
>   - WARNING: `neovim-ruby-host` not found.
>     - ADVICE:
>       - Run `gem install neovim` to ensure the neovim RubyGem is installed.
>       - Run `gem environment` to ensure the gem bin directory is in $PATH.
>       - If you are using rvm/rbenv/chruby, try "rehashing".
>       - See :help |g:ruby_host_prog| for non-standard gem installations.
> 
> ## Node.js provider (optional)
>   - INFO: Node.js: v15.3.0
>   - INFO: Neovim node.js host: /Users/uu/.anyenv/envs/nodenv/versions/15.3.0/lib/node_modules/neovim/bin/cli.js
>   - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

### Screenshots(Optional, GIF is better)
<img width="1486" alt="スクリーンショット 2021-02-02 22 46 52" src="https://user-images.githubusercontent.com/51429010/106609090-8c701980-65a8-11eb-8cdf-b759cca1eeef.png">

**Comment by voldikss** [comment]
What is the output of `tmap <C-f>`

**Comment by voldikss** [comment]
BTW, `:FloatermNew --floaterm_wintype="popup"` should be `:FloatermNew --wintype=float`

**Comment by tomato-300yen** [comment]
> What is the output of :tmap <C-f>
that says, "No mapping was found"...

<img width="321" alt="スクリーンショット 2021-02-02 23 07 54" src="https://user-images.githubusercontent.com/51429010/106611580-7d3e9b00-65ab-11eb-9a78-c3b972c63acb.png">

**Comment by voldikss** [comment]
Does `<C-f>` works normally in `:terminal`?

**Comment by tomato-300yen** [comment]
Not working...?

<img width="1486" alt="スクリーンショット 2021-02-02 23 14 53" src="https://user-images.githubusercontent.com/51429010/106612467-76645800-65ac-11eb-9144-9506dde356d4.png">

**Comment by voldikss** [comment]
Hmmm then you should check your vim configuration or your terminal stuffs...

**Comment by voldikss** [comment]
Sorry but I have no idea what caused this problem. But let me close this issue...

**Comment by tomato-300yen** [comment]
I can use `<C-h>`, `<C-c>`, `<C-l>`, but can't use `<C-a>`, `<C-f>`, and so on...what's the differences...?

BTW, thank you for thinking about this!

**Comment by tomato-300yen** [comment]
Checking out in commit "74d33de", which I started to use, solved me this issue.

I'll be checking what caused this problem.

Thanks.
