### ISSUE TITLE
FloatermToggle command arguments

### ISSUE THREAD

**Issue by mxlang** [voldikss/vim-floaterm#243]
Hi! First, thanks for this great plugin! I'd like to make a suggestion which I would find really useful and I feel would ease the workflow of working with named terminal instances.

I think it would be great that the `FloatermToggle` command would be able to take the same arguments as the `FloatermNew` command. Currently, the `FloatermToggle` command is able to fire a named terminal instance if it does not exist, yet you can't specify what to run in that instance or what is the desired window's position or size. Therefore it is currently required to run `FloatermNew` with the desired arguments before being able to use the `FloatermToggle` command to toggle this instance.

In the background, the `floaterm#toggle` function is effectively calling the `floaterm#new` command if no instance is found, so I think it makes sense to allow one to supply the args that could be passed on to the `floaterm#new` command.

If the `FloatermToggle` command could take the additional arguments, one could make a single keyboard mapping to fire an on demand named terminal instance with the desired arguments.

For example:

    " Floaterm instance for running lazygit
    nnoremap <silent> <C-g> :FloatermToggle --name=lazygit --wintype=float --position=center --width=0.8 --height=0.8 lazygit<CR>

**Comment by voldikss** [comment]
Hi @mxlang 

I respect your suggestion. However, it will make the command somehow obscure and more complex. I recognize that workflow but I don't have a good prospect for changing the arguments of `:FloatermToggle`. Moreover, the logic of `:FloatermToggle` is quite complex for me as it has so many `if-else` corresponding to so many cases. Therefore I tend not to touch it unless for bugs fixing :(

Currently a good solution would be define a user function which wraps `:FloatermToggle` and `:FloatermNew` to cover the workflow.

**Comment by voldikss** [comment]
Closing this issue.

**Comment by Bekaboo** [comment]
Hi, I've come up with a solution (sort of), you can add this to your config so that you can use different keys to toggle terminals with different purposes 😄:

```viml
    function! GetBufnrUnnamed() abort
      let buflist = floaterm#buflist#gather()
      for bufnr in buflist
        let name = getbufvar(bufnr, 'floaterm_name')
        if empty(name)
          return bufnr
        endif
      endfor
      return -1
    endfunction

    function! ToggleTool(tool, count) abort
      " find bufnr according to the tool name
      let bufnr = empty(a:tool) ?
        \ GetBufnrUnnamed() : floaterm#terminal#get_bufnr(a:tool)

      if bufnr == -1
        if empty(a:tool)
          " ToggleTool should only be called from
          " normal mode or terminal mode without bang
          call floaterm#run('new', 0, [visualmode(), 0, 0, 0], '')
        else
          call floaterm#run('new', 0, [visualmode(), 0, 0, 0],
            \ printf('--title=%s($1/$2) --name=%s %s', a:tool, a:tool, a:tool))
        endif
      else
        call floaterm#toggle(0, a:count ? a:count : bufnr, '')
        " workaround to prevent lazygit shift left;
        " another workaround here is to use sidlent!
        " to ignore can't re-enter normal mode error
        execute('silent! normal! 0')
      endif
    endfunction

    command! -nargs=? -count=0 ToggleTool call ToggleTool(<q-args>, <count>)
    nnoremap <silent> <M-e> <Cmd>execute v:count . 'ToggleTool ranger'<CR>
    tnoremap <silent> <M-e> <Cmd>execute v:count . 'ToggleTool ranger'<CR>
    nnoremap <silent> <M-i> <Cmd>execute v:count . 'ToggleTool lazygit'<CR>
    tnoremap <silent> <M-i> <Cmd>execute v:count . 'ToggleTool lazygit'<CR>
    nnoremap <silent> <C-\> <Cmd>execute v:count . 'ToggleTool'<CR>
    tnoremap <silent> <C-\> <Cmd>execute v:count . 'ToggleTool'<CR>
```

**Comment by 9mm** [comment]
Heres my lua version, which is slightly more simple.

The only current problem is it doesnt account for multiple lazygit's per git project but thats not a part of this issue, but still in case anyone wants my code

```lua
local function get_bufnr_from_name(name)
  local buflist = vim.fn['floaterm#buflist#gather']()
  for _, bufnr in ipairs(buflist) do
    local bufname = vim.fn.getbufvar(bufnr, 'floaterm_name')
    if bufname == name then
      return bufnr
    end
  end
  return -1
end

local function toggleFloaterm(args)
  local name = args:match('--name=([^%s]+)')
  local bufnr = get_bufnr_from_name(name)

  if bufnr == -1 then
    vim.cmd('FloatermNew ' .. args)
  else
    vim.cmd('FloatermToggle ' .. name)
  end
end

return {
  'voldikss/vim-floaterm',
  config = function()
    vim.g.floaterm_title = ''

    -- https://github.com/neovide/neovide/issues/1838
    vim.keymap.set('t', '<MouseMove>', '<NOP>')
  end,
  keys = {
    {
      '<Leader>x',
      function() toggleFloaterm('--name=zsh --title=ZSH --autoclose=2 --width=0.7 --height=0.4') end,
      mode = { 'n', 't' },
      desc = 'ZSH shell',
    },
    {
      '<Leader>z',
      function() toggleFloaterm('--name=lazygit --width=0.98 --height=0.95 lazygit') end,
      mode = { 'n', 't' },
      desc = 'LazyGit',
    },
  },
}
```
