### ISSUE TITLE
两个问题请教（请原谅我使用中文提问）

### ISSUE THREAD

**Issue by yllr78** [voldikss/vim-floaterm#244]
非编程从业人员，年龄偏大，喜爱vim，英文差，还是个颜值控看到您的大作欣喜若狂，因为听说作者是国人，才敢提问题。。。。。废话不多说，上问题

环境是vim，非nvim，平时就是学习python和用python写点自己用的小东西（英文水平差，高级活也干不了）

问题1：
当repl用的时候按您的demo来开启floaterm窗口，但是left和right都不起作用，left和top功能一样，只能开上边窗口，bottom和right功能一样只能开下面窗口。AsyncTask中的设置right起作用，可以将窗口显示在右边，vim-repl中也是同样问题。平时用的win7，虚拟机里的archlinux环境测试也是相同问题。
命令是:FloatermNew --width=0.5 --wintype=normal --name=repl --position=right ipython

问题2：
我也使用AsyncRun 和 AsyncTask，看到你的你的demo里用AsyncTask start指令来调用感觉很好，不知是怎么写的调用代码？能分享一下吗？我自己只会用在AsyncTask中设置asynctasks_term_pos = 'floaterm' 来实现，想用你的方式。

我没有用最小配置来测试，很不好意思，希望大神能在百忙之中抽出时间回答我的问题，一定不吝赐教。谢谢！

刚刚使用了最小配置，配置如下：
set nocompatible
set hidden
set termguicolors
set runtimepath^=$VIN\vimfiles\plugged\vim-floaterm
filetype plugin indent on
syntax on
set clipboard+=unnamed

这样配置后floaterm的命令并不识别，:checkhealth命令同样不识别。

- Please make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

- Please make sure you are using the latest version of the plugin.

- Please use English as far as possible.

### To Reproduce

- Use the minimal vimrc

  ```vim
  set nocompatible
  set hidden
  set termguicolors
  set runtimepath^=/path/to/vim-floaterm
  filetype plugin indent on
  syntax on
  ```

- Steps to reproduce the behavior:
  1.
  2.
  3.
  4.

### Enviroment
 - OS [e.g. Arch Linux]:
 - Version [e.g. NVIM v0.5.0-fa9b057]:
 - Checkhealth info [run `:checkhealth` and post the messages]:

**Comment by voldikss** [comment]
> 问题1：
当repl用的时候按您的demo来开启floaterm窗口，但是left和right都不起作用，left和top功能一样，只能开上边窗口，bottom和right功能一样只能开下面窗口。AsyncTask中的设置right起作用，可以将窗口显示在右边，vim-repl中也是同样问题。平时用的win7，虚拟机里的archlinux环境测试也是相同问题。
命令是:FloatermNew --width=0.5 --wintype=normal --name=repl --position=right ipython

一些命令参数我最近有改动，你应该使用下面对的命令（你在下方输入的时候可以使用 TAB 键来补全各种参数，这样不容易出错）

```vim
:FloatermNew --width=0.5 --wintype=vsplit --name=repl --position=rightbelow ipython
```

> 问题2：
我也使用AsyncRun 和 AsyncTask，看到你的你的demo里用AsyncTask start指令来调用感觉很好，不知是怎么写的调用代码？能分享一下吗？我自己只会用在AsyncTask中设置asynctasks_term_pos = 'floaterm' 来实现，想用你的方式。

安装 asynctasks.extra 就可以了， 我在 README 里面有提到。如果你是说 tasks.ini 文件的话可以参考这里：https://github.com/voldikss/dotfiles/blob/dev/home/.config/nvim/tasks.ini

> 这样配置后floaterm的命令并不识别，:checkhealth命令同样不识别。

vim 没有 checkhealth 这个命令，只有 nvim 有。个人建议使用 nvim，包括 coc.nvim 在内的好多插件在 nvim 上的使用体验更好（个人观点）。

**Comment by yllr78** [comment]
换到nvim也考虑过，但考虑到自己一般都在win上工作，听说nvim只支持utf-8编码，并不支持老的中文编码，害怕万一要编辑个旧编码的文件啥的有问题，一直没决定。

**Comment by voldikss** [comment]
哦哦，nvim 确实不支持 set encoding=cp936

**Comment by yllr78** [comment]
我编辑第三个问题的时候你已经回答了，能帮我看看第三个问题能否解决吗？谢谢

**Comment by yllr78** [comment]
:FloatermNew --width=0.5 --wintype=vsplit --name=repl --position=rightbelow ipython
这个命令起效了！！！！感谢大神

**Comment by voldikss** [comment]
> 我编辑第三个问题的时候你已经回答了，能帮我看看第三个问题能否解决吗？谢谢

给我个截图我看看

**Comment by voldikss** [comment]
是不是缩进的问题，如果是的话可以参考

https://github.com/voldikss/vim-floaterm/issues/193

https://github.com/voldikss/vim-floaterm/issues/150

**Comment by yllr78** [comment]
![2021-02-03_124005](https://user-images.githubusercontent.com/20411331/106699020-f9bd9200-661c-11eb-9a9d-d5e52e0205c3.png)

**Comment by yllr78** [comment]
Async的扩展我已经安装了，只是自己不知道怎么使用AsycnTask start这种命令形式，默认应该不能这么用。。。。

**Comment by voldikss** [comment]
> AsyncRun的扩展我已经安装了，只是自己不知道怎么使用AsycnTask start这种命令形式，默认应该不能这么用。。。。

如果你是说 tasks.ini 文件的话可以参考这里：https://github.com/voldikss/dotfiles/blob/dev/home/.config/nvim/tasks.ini

**Comment by yllr78** [comment]
这个文件内容好多，看起来是涵盖了主流语言了，应该是这个问题，我测试一下，谢谢。

**Comment by voldikss** [comment]
问题3我暂时没头绪，等我有空用 Windows gvim 测试一下

**Comment by yllr78** [comment]
1，2两个问题已解决，感谢大神的细心帮助，期待你的测试结果。再次感谢。

**Comment by yllr78** [comment]
建议看一下张翼腾的vim-repl的代码，他的没有这个问题。

**Comment by yllr78** [comment]
又出现个问题，用AsyncTask start运行以后，在运行窗口移动光标会出现vim整个窗口闪屏，请看gif。录制的效果不太好，但是闪屏就是这个样子。
![GIF 2021-2-3 13-55-32](https://user-images.githubusercontent.com/20411331/106704833-b87eaf80-6627-11eb-972f-774cebf266d2.gif)

**Comment by yllr78** [comment]
现在发现不是floaterm的问题，是任何情况下只要光标到了屏幕边缘继续移动的话就会屏闪，原来没有这个问题，最近修改了不少配置，不知道是哪里的问题。如果你见过的话不吝赐教，我继续寻找答案。

**Comment by voldikss** [comment]
没见过，感觉是在换主题

**Comment by yllr78** [comment]
set noerrorbells visualbell t_vb=           就是这条配置引起的，这是我昨天加上的配置。删掉就好了，网上找到答案了。

**Comment by yllr78** [comment]
生命不息，折腾不止，吼吼～～～～：）

**Comment by yllr78** [comment]
你demo里的命令行补全是什么实现的？是coc吗？我用vim自带的命令补全设置，显示出来不是一列，而是很多列，感觉很不爽。我用的补全插件是completor，这货好久没更新了，lsp好像也是骗人的，python补全还不错，不想搞那么多依赖node.js，不然就上coc了。

**Comment by voldikss** [comment]
> 你demo里的命令行补全是什么实现的？是coc吗？我用vim自带的命令补全设置，显示出来不是一列，而是很多列，感觉很不爽。我用的补全插件是completor，好像不能补全命令行。这货好久没更新了，lsp好像也是骗人的，python补全还不错，不想搞那么多依赖node.js，不然就上coc了。

这个功能只有 nvim 有，vim 就是很多列

**Comment by yllr78** [comment]
好不容易能与大神直接交流对话，请原谅我过多的问问题，毕竟周围能闻到的人太少。当然我顺路再问个小问题。

我根据韦一笑大神的文章使用vim-gutentags来管理tags，使用的是u-ctags软件，文章里说通过配置可以让这个插件自动生成tags文件，但是我经常编辑的python目录里从来也没有产生过tags文件，不知道是怎么实现的。

另外，使用了你的task.ini文件，最后面貌似有ctags的设置，但是我通过vim内部执行AsyncTask ctags命令并没有在当前目录生成tags文件，这是怎么回事呢？

**Comment by yllr78** [comment]
floaterm窗口靠右时，右边的边框变成了>符号，能否美化成正常的样子？

![2021-02-03_150311](https://user-images.githubusercontent.com/20411331/106710504-00560480-6631-11eb-8b48-c5ad43d278a3.png)

**Comment by voldikss** [comment]
> 好不容易能与大神直接交流对话，请原谅我过多的问问题，毕竟周围能闻到的人太少。当然我顺路再问个小问题。
> 
> 我根据韦一笑大神的文章使用vim-gutentags来管理tags，使用的是u-ctags软件，文章里说通过配置可以让这个插件自动生成tags文件，但是我经常编辑的python目录里从来也没有产生过tags文件，不知道是怎么实现的。
> 
> 另外，使用了你的task.ini文件，最后面貌似有ctags的设置，但是我通过vim内部执行AsyncTask ctags命令并没有在当前目录生成tags文件，这是怎么回事呢？
> 
> 经过测试，打开_vimrc文件时没法生成tags文件，其他目录可以。

这个不是自动生成的，和 skywind3000 在知乎上说的不是一个东西。

> floaterm窗口靠右时，右边的边框变成了>符号，能否美化成正常的样子？

不了解为啥会这个样子，我这边用的 Linux 没这问题，我有空在 Windows 上 gvim 试下再说

**Comment by yllr78** [comment]
好的，目前就剩下这两个问题了，我今天一股脑的把我存在的疑问都处理了，对我帮助很大，谢谢。等待那两个问题的好消息 ：）

**Comment by yllr78** [comment]
请允许我弱弱的再请教一个问题，我编辑一些带括号语句的文件经常会出现光标到不了一行的最右边，但是删除就会删除最右边的字符，行内也是一样，实际显示的光标位置和操作的位置不一样。一般是光标在左边，实际操作的位置延后两个字符左右。
我自己感觉是某个插件引起的，一直没找到问题的原因。不知大神你遇到过这个问题没？

**Comment by voldikss** [comment]
没有遇到过

**Comment by yllr78** [comment]
看到你的配置文件中使用了模板功能，感觉挺好的，想拿过来用，但是配置方面有点看不懂
比如：
augroup AutoTemplate
  autocmd!
  autocmd BufNewFile .gitignore,.npmignore,.tasks,.clang-format,Solution.cpp Template
augroup END

这条语句能干点啥？也没看看到设置模板目录的语句，有点迷茫。麻烦解答，谢谢。

我一般也就接触到的就是html,python,js,markdown这类文件，想打开的时候自动在文件头部加上点内容。看你好像没有用插件来干这个事情，就是看不懂啊。  ：（

**Comment by yllr78** [comment]
那两个小问题已经解决了吗？看到你更新了两次。

**Comment by yllr78** [comment]
windows下floatterm窗口靠右边的>符号没有了，显示正常了。
但是FloatermSend命令发送python语句到ipython还是会发送那个^[符号。上图：
![2021-02-14_024019](https://user-images.githubusercontent.com/20411331/107858333-9a5a5000-6e6e-11eb-8d94-81d012db099e.png)

**Comment by voldikss** [comment]
> 但是FloatermSend命令发送python语句到ipython还是会发送那个^[符号

这个只在 Windows Gvim 上出现，原因我没找到。之前试着修了但是又引入了其他 bug 所以我又回退了。实在找不到啥原因，很惭愧，暂时不打算修了。

**Comment by yllr78** [comment]
大神可否参考一下vim-repl的代码？他没这个问题。。。。，

**Comment by voldikss** [comment]
修复了

**Comment by yllr78** [comment]
不愧是大神，已在本机测试，效果完美。感谢这段时间以来帮我解答了这么多问题。当然，我还将一如既往的请教问题，请不要觉得烦  ：）

**Comment by yllr78** [comment]
当然了，我又发现一个问题，在floaterm中使用floaterm命令将一个文本文件交给vim打开，会弹出一个告警按钮，但是内容看不清，有图有真相！
![2021-02-19_005804](https://user-images.githubusercontent.com/20411331/108392583-d23a0c80-724d-11eb-9863-11ad0716120d.png)

**Comment by voldikss** [comment]
> 当然了，我又发现一个问题，在floaterm中使用floaterm命令将一个文本文件交给vim打开，会弹出一个告警按钮，有图有真相！

已修复

**Comment by voldikss** [comment]
> 另外，你的dotfiles是个金矿，我得好好学习下，就是内容太多，功能太强，看得我脑仁儿疼。。。。。。，回头肯定还得请教点vim配置方面的问题，请不吝赐教，谢谢！

我的 dotfiles 不建议多参考，很多我自己的设置你并不一定用得到，会造成误导。还有，我也没时间答疑... 😢

**Comment by yllr78** [comment]
我尽量不打扰大神工作，一般我都会自己查资料来学习，实在搞不定的问题才请教，估计不会过多占用你的时间。你的vim配置很高大上，我第一次见到配置的这么详细的，请同意我向你学习。：）

**Comment by yllr78** [comment]
最近正在学习大神的.vimrc的配置，有一个地方看不懂，不得不请教个问题，麻烦大神抽空解答一下，谢谢。

fn#lightline#AsyncRunStatus  这种类型的函数调用时怎么实现的？   fn我理解的是前面定义的缩写，但是后面的部分我就理解不了了。我在命令行试着运行call lightline#AsyncRunStatus() 和 #AsyncRunStatus()都不起作用，根本找不到这个函数。
这种写法是什么目的？实现了什么功能呢？  

请大神百忙之中抽一点点时间帮我答疑解惑，谢谢了。

**Comment by yllr78** [comment]
lightline上显示git信息竟然被我搞定了，自己琢磨出来的，上图：
![2021-03-18_115058](https://user-images.githubusercontent.com/20411331/111570738-6319ee80-87e0-11eb-8035-ea7549b5bce9.png)

感谢大神授人以渔的工作态度，不然我永远还是个伸手党。您的vim配置文件启发了我很多，让我见识到了真正vim高手。
但是最后还得请教那个模板的问题，我实在是找不到模板的相关内容，怎么能根据文件类型来自动调用模板呢？你的配置看了很长时间实在是看不懂了。   请一定不吝赐教啊。

**Comment by voldikss** [comment]
很不推荐我自己的配置，会误导的。

我推荐你用 https://github.com/aperezdc/vim-template

**Comment by voldikss** [comment]
对不起啊，我实在是没空，你加几个 vim 群我觉得是更好的选择。

关于相关学习资源，推荐 https://github.com/wsdjeg/vim-galore-zh_cn

**Comment by yllr78** [comment]
十分感谢您的悉心帮助！
