### ISSUE TITLE
Bottom is not working anymore

### ISSUE THREAD

**Issue by matheusfillipe** [voldikss/vim-floaterm#245]
I am on commit  671f2aa87731ddeefe6573e4596c9f0d806e3b11 and running `:FloatermNew --wintype='normal' --position='bottom' --height=0.25` no longer result in a floating window attached to the bottom. Tried other options and a fresh install and still didn't work.

**Comment by voldikss** [comment]
I've made some changes recently.

:FloatermNew --wintype='normal' --position='bottom' --height=0.25

should be 

:FloatermNew --wintype=split --position=belowright --height=0.25

**Comment by matheusfillipe** [comment]
Oh! sorry I didn't catch that up 😅
