### ISSUE TITLE
FloatermNew seems to be broken

### ISSUE THREAD

**Issue by SuperCuber** [voldikss/vim-floaterm#247]
### Environment
If you are using neovim, run `:checkhealth floaterm` and post the content
below.
```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Nvim: NVIM v0.5.0-610-g326b87feb
  - INFO: Platform: win

## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

## neovim-remote
  - WARNING: nvr executable is not found
    - ADVICE:
      - install it via `pip3 install neovim-remote`
```

Configurations related to vim-floaterm in vimrc:

```vim
command! -nargs=* Cargo :FloatermNew cargo <args>
```

### Steps to reproduce the behavior
use `:FloatermNew echo hi`

### Actual behaviour
Error: 
```
Error detected while processing function floaterm#run
line 3:
E714: List Required
```

### Expected behaviour
Run the command in a terminal

**Comment by voldikss** [comment]
Strange. It works normally on my laptop (windows neovim-qt)

**Comment by voldikss** [comment]
Are you using the latest version of the plugin?

**Comment by SuperCuber** [comment]
Yes, just updated (last time before that was a couple days ago) and this issue appeared

**Comment by SuperCuber** [comment]
Oh, never mind. I just restarted vim and it works, I guess it just needed that.
