### ISSUE TITLE
Wrappers not working when &shell is powershell

### ISSUE THREAD

**Issue by sitiom** [voldikss/vim-floaterm#249]
### Environment

```
NVIM v0.5.0-dev+1075-g02a3c4179
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-971

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```
  - [x] Windows

If you are using neovim, run `:checkhealth floaterm` and post the content
below.

```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: win
  - INFO: Nvim: NVIM v0.5.0-dev+1075-g02a3c4179
  - INFO: Plugin: a8787bc


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

## neovim-remote
  - OK: Version: nvr 2.4.0
```

Configurations related to vim-floaterm in vimrc:

```vim
let &shell = has('win32') ? 'powershell' : 'pwsh'
set shellquote= shellpipe=\| shellxquote=
set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
set shellredir=\|\ Out-File\ -Encoding\ UTF8
```

### Describe your question, feature request, or bug.
I don't know when this bug appeared, as it used to work fine. `FloatermNew` opens the default shell (cmd) instead of the set `powershell` or `pwsh`. Another thing is that I cannot use floaterm wrappers like lf or fzf when I set my shell to powershell, as this error appears:
```
The argument '-NoLogo -NoProfile -ExecutionPolicy RemoteSigned -Command' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
![image](https://user-images.githubusercontent.com/56180050/107640097-bd3d0680-6cac-11eb-923b-daa54ed18ac8.png)

**Comment by sitiom** [comment]
Disregard. Reinstalling the plugins fixed it.

**Comment by sitiom** [comment]
Disregard. Reinstalling the plugins fixed it.

**Comment by sitiom** [comment]
Nvm. It was the old version that worked.

**Comment by sitiom** [comment]
Reverting https://github.com/voldikss/vim-floaterm/commit/d67f3a734c6badc45e5a836b0d7c1629b1515d86 worked.

**Comment by sitiom** [comment]
`packadd` should be called after the shell is set. This solves the first problem.

**Comment by voldikss** [comment]
Sorry I do not understand what's wrong here... Could you describe it more specifically?

**Comment by sitiom** [comment]
When &shell is set to `powershell` or `pwsh`, wrappers do not work. This happens:
![image](https://user-images.githubusercontent.com/56180050/107653040-2c6e2700-6cbc-11eb-9986-4f79e743ff6b.png)

Reverting https://github.com/voldikss/vim-floaterm/commit/d67f3a734c6badc45e5a836b0d7c1629b1515d86 fixes this problem.

**Comment by voldikss** [comment]
Should be fixed.
