### ISSUE TITLE
FloatTerm-only mapping or autocmd

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#25]
It would be great to have a feature where we can add custom keymaps or commands that work on the floating terminal only. Using `tmap` or something might work but I would want to not affect other normal terminal buffers --- it should be only applicable to the floating terminal buffer.

Autocmd would be one option to implement this. Alternatively, if there is a vimscript API that would tell if the current buffer is a FloatTerm buffer (maybe exposing `b:` variable would work). Or do we already have this feature?

**Comment by wookayin** [comment]
Oh, I figured out. There is a buffer-specific variable `b:floaterm_window`.

https://github.com/voldikss/vim-floaterm/blob/cfd20e082c226fffbb074924c6966a83d32dc199/autoload/floaterm.vim#L215

**Comment by voldikss** [comment]
Hi, are you looking for something like [this](https://github.com/voldikss/vim-floaterm#i-would-like-to-customize-the-style-of-the-floating-terminal-window)?

Since 

> but I would want to not affect other normal terminal buffers

So would you think the following `autocmd` is a good way to do that?

```vim
autocmd BufEnter * if exists('b:floaterm_window') | call s:floatermSettings() | endif
```

**Comment by wookayin** [comment]
Oh yes, this is what we need. Autocmd+FileType should be better than one that uses `b:floaterm_window`. Could we have a dedicated FileType name? How about `floaterm`? 

I actually had thought `terminal` is for all terminals (because of its general name) but seems not; normal terminal buffers seem to have empty ft. For example, [fzf](https://github.com/junegunn/fzf.vim#hide-statusline) has `fzf`, `fugitive` has `gitcommit`, `git`, etc. [git-messenger](https://github.com/rhysd/git-messenger.vim) has `gitmessengerpopup`, etc.

**Comment by voldikss** [comment]
Thanks for your suggestion. `floaterm` si great.

**Comment by wookayin** [comment]
Thank you for your quick follow-up! Looks great and customization works well for me.
