### ISSUE TITLE
[nnn] is it possible to configure keys for opening files?

### ISSUE THREAD

**Issue by divramod** [voldikss/vim-floaterm#250]
Hey, 

i really like the floatterm nnn wrapper!
can anyone give me a hint on where to start configuring the keys for opening files from nnn?

i like to use
- ctrl-t to open in a new tab
- ctrl-x to open in a split
- ctrl-v to open in a vsplit

thx for the plugin!

**Comment by voldikss** [comment]
It seems possible according the implementation of nnn.vim

https://github.com/mcchrish/nnn.vim#action

https://github.com/mcchrish/nnn.vim/blob/12a376646f05f71fb111892d07f84b94a47dbac5/autoload/nnn.vim#L9

**Comment by voldikss** [comment]
I don't have much time and intention for this now. Therefore closing.

This seems not a very diffcult to implement, I would like to mark it as `reopen` and `help wanted` and see if there are any people interested in it could make a PR.
