### ISSUE TITLE
Add a reference ptzz/lf.vim as a lf floaterm wrapper plugin

### ISSUE THREAD

**Issue by sitiom** [voldikss/vim-floaterm#251]
With https://github.com/ptzz/lf.vim/pull/10 merged, [lf.vim](https://github.com/ptzz/lf.vim) has essentially become an lf floaterm wrapper with the extra features that it has.

**Comment by voldikss** [comment]
Awesome work! Does it conflict with vim-floaterm's builtin lf wrapper?

**Comment by sitiom** [comment]
> Awesome work! Does it conflict with vim-floaterm's builtin lf wrapper?

No, It overrides it. You can delete the builtin lf wrapper and point to that of you want.

**Comment by voldikss** [comment]
> You can delete the builtin lf wrapper and point to that of you want.

It might be not a good idea to tell users to modify the plugin.

> It overrides it

But this is happy.

**Comment by voldikss** [comment]
Would you like to add a reference link to lf.vim in README.md of this plugin? If so, could you create a PR? I am away from my PC right now.

**Comment by sitiom** [comment]
> I am away from my PC right now.

Same. I would be able to do in a few hours.

**Comment by sitiom** [comment]
> I am away from my PC right now.

Same. I would be able to do in a few hours.
