### ISSUE TITLE
Recent commit introduces ranger bug (Neovim)

### ISSUE THREAD

**Issue by kirsa** [voldikss/vim-floaterm#254]
Hello

After a recent commit (I suspect this one : commit 63c2197646de7905538e8830bd5ffd7d3607ac51, "Complete! Remove nvr dependency" which modifies the ranger.vim wrapper) opening files from ranger in floaterm opens files in vertical splits instead of a new buffer without splits like it used to do previously.

Usage
:FloatermNew ranger
Then select file and press enter

I am running on Neovim with no configuration changes to vim-floaterm other than let g:floaterm_autoclose=1

**Comment by voldikss** [comment]
set `g; floaterm_opener` to 'edit' should fix that.

**Comment by kirsa** [comment]
Thanks a lot!
