### ISSUE TITLE
floaterm command is broken after update.

### ISSUE THREAD

**Issue by lkhphuc** [voldikss/vim-floaterm#256]
### Environment

If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version` or `nvim --version`: `NVIM v0.5.0-dev+nightly-18-g971e0ca90`
- Platform: 

  - [x] Linux
  - [x] Mac OS X
  - [ ] Windows

If you are using neovim, run `:checkhealth floaterm` and post the content
below.

```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: macos
  - INFO: Nvim: NVIM v0.5.0-dev+nightly-18-g971e0ca90
  - INFO: Plugin: fatal: not a git repository (or any of the parent directories): .git


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

```

Configurations related to vim-floaterm in vimrc:

### Describe your question, feature request, or bug.
`floaterm` command to open file from within the floaterm is broken after update to the latest version, both on Mac and Linux, both stable and nightly build.

### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

### Actual behaviour
The command hang for a while and output a bunch of `/Users/phuc/.local/share/nvim/plugged/vim-floaterm/bin/floaterm: fork: Resource temporarily unavailable`

### Expected behaviour
Open file.

![Screenshot 2021-02-17 at 01 36 53](https://user-images.githubusercontent.com/12573521/108143977-9e7dac00-70c0-11eb-9e2b-a6f8b092aeca.png)

**Comment by voldikss** [comment]
Hmmm I do not use Mac, could you also show the command output in Linux?

**Comment by voldikss** [comment]
In the floaterm, please run the shell command (not ex command) `echo $EDITOR` and give me feedback.

**Comment by lkhphuc** [comment]
Same thing on Ubuntu: `/home/phuc/.local/share/nvim/plugged/vim-floaterm/bin/floaterm: 5: Cannot fork
/home/phuc/.local/share/nvim/plugged/vim-floaterm/bin/floaterm: 29: Cannot fork`

Oh and I have a config in my zsh that if $NVIM_LISTEN_ADDRESS is populated, $EDITOR='floaterm' (and afterward I `alias v=$EDITOR` so I can just type `v` inside and outside `floaterm`).
After I change the `export EDITOR=nvim`, floaterm runs again but open file in the floaterm buffer, not in `g:floaterm_opener=vsplit`.
If I `export EDITOR=nvr`, floaterm open file in the floaterm buffer, but removing the floaterm border.

**Comment by lkhphuc** [comment]
An additional issue if you can help me out: How to define $EDITOR in your .zshrc without overwrite $EDITOR in floaterm.
Currently if I set $EDITOR to anything in my zshrc, it will overwrite $EDITOR inside floaterm as well, hence leads to the error above.
But if I don't specify $EDITOR, I cannot set the same alias to $EDITOR inside and outside of floaterm, or use $EDITOR for other terminal application such as `lazygit` or `lf`.

**Comment by voldikss** [comment]
Good to hear that.

**Comment by voldikss** [comment]
This issue gets fixed, now you can remove `if [ -z $EDITOR ]; then`stuff.
