### ISSUE TITLE
why is the floating terminal window‘s border broken？

### ISSUE THREAD

**Issue by suncg1985** [voldikss/vim-floaterm#257]
my vim setting for floaterm is above：  
      let g:floaterm_width = 0.8
      let g:floaterm_height = 0.4
      let g:floaterm_wintype = 'float'
and i found that the border is imcomplete, whats wrong with my configuration?
![微信截图_20210217170033](https://user-images.githubusercontent.com/48081705/108180461-c2cd9d00-7141-11eb-8b29-1b3b2b618232.png)

**Comment by voldikss** [comment]
Hi @suncg1985 

- Please provide more info (at least vim/nvim version) required in the ISSUE_TEMPLATE because it's pretty helpful for figuring out the cause of the problem.
- Does this issue occurs after an upgrading recently or you just installed the plugin and found that issue?

**Comment by voldikss** [comment]
Closing due to no response, but you can still comment here at your leisure.

**Comment by suncg1985** [comment]
os: Manjaro 21.0 Ornara
nvim: 0.4.4-1
and all my config for floaterm is below:
        set shell=/usr/bin/fish  " use oh-my fish as shell
        let g:floaterm_keymap_new = '<Leader>fn'
        let g:floaterm_keymap_toggle = '<Leader>fo'
        nmap <LEADER>fp :FloatermNew python<CR> 
        let g:floaterm_width = 0.8
        let g:floaterm_height = 0.4
        let g:floaterm_wintype = 'float'
        let g:floaterm_borderchars = '─│─│┌┐┘└'

**Comment by voldikss** [comment]
Sorry but still can not reproduce that. Tested with Arch + nvim-0.4.4 + fish

**Comment by balazser** [comment]
I've just installed this awesome plugin, and I experience the same. I have no config other than the `Plug` install command.
What kind of additional details scan I provide? :thinking: 
![image](https://user-images.githubusercontent.com/20303564/152446595-5b149f20-1845-4a1b-97c1-7fa4c4b2a396.png)

**Comment by Euler-37** [comment]
This situation caused by the `(neo)vim` option
`set ambiwidth=double`,and then the non-ascii characters (such as :digraphs) width is 1 ,so the borad chars just show half. if set it as `single`, it will be solved.
