### ISSUE TITLE
The --cwd option does not work with the ranger plugin

### ISSUE THREAD

**Issue by gbcreation** [voldikss/vim-floaterm#258]
### Describe your bug.

The `--cwd` option is not taken into account by the ranger plugin.

### Steps to reproduce

Use `:FloatermNew --cwd=/home/me ranger` or `:FloatermNew --cwd=<root> ranger`

### Actual behaviour

Ranger displays the content for the folder of the current edited buffer.

### Expected behaviour

Ranger must display the folder specify by the `--cwd` option.

**Comment by voldikss** [comment]
Use FloatermNew ... ranger /home/me

**Comment by voldikss** [comment]
Can be fixed by #261
