### ISSUE TITLE
[Feature request] Enhance the --opener option to pass a function

### ISSUE THREAD

**Issue by gbcreation** [voldikss/vim-floaterm#259]
### Describe your feature request

Could you please enhance the `--opener` option so that we can set a Vim function?

It would be a generic way to do any operation on the selected files. On my end, my goal is to use the ranger plugin to insert the path of the selected file to the edited buffer at the current cursor position.

**Comment by voldikss** [comment]
Passing a function would be not a sensible choice. Actually you can define a command which accepts a filename just like built in `edit` command.

```vim
command! MyEdit -nargs=1 ....
```

**Comment by gbcreation** [comment]
Thank you for your suggestion. Defining a command is a very good solution. Here is the one I created to insert the relative path of the file selected in Ranger:

```
function! InsertRelativePath(path)
    let filedir = expand('%:h')
    let tailingPart = substitute(a:path, filedir, '', '')
    if tailingPart != a:path
        exec 'normal i.' . tailingPart
    else
        let pathItems = split(a:path, '/')
        let filedirItems = split(filedir, '/')
        while len(pathItems) && pathItems[0] == filedirItems[0]
            call remove(pathItems, 0)
            call remove(filedirItems, 0)
        endwhile
        exec 'normal i' . join(map(copy(filedirItems), string('..')) + pathItems, '/')
    endif
endfunction

command! -nargs=1 InsertRelativePath call InsertRelativePath(<q-args>)
```
Then, I can use

```
:FloatermNew --opener=InsertRelativePath ranger
```

The path of the selected file is correctly inserted at the position of the cursor, but the selected file is also opened. It seems to be related to [those lines](https://github.com/voldikss/vim-floaterm/blob/master/autoload/floaterm/util.vim#L44-L52) in the `floaterm#util#open()` function. Could you please fix that behavior?

**Comment by voldikss** [comment]
The problem lies in this line, but I don't have any good solutions for this.

https://github.com/voldikss/vim-floaterm/blob/3610b8a4f479fba680d0e7bfce478d9f41eb44f0/autoload/floaterm/util.vim#L45

Do you have some ideas?

**Comment by gbcreation** [comment]
A possible solution could be to process `lnum`, `text` and `zz` only if the current buffer matches `loc.filename`:

```
function! floaterm#util#open(locations, ...) abort
  let opener = get(a:000, 0, g:floaterm_opener)
  for loc in a:locations
    execute opener loc.filename
    " check if the 'opener' opened filename.
    " If so, proceed to lnum, text, ss
    if expand('%') == loc.filename
        if has_key(loc, 'lnum')
          execute loc.lnum
        elseif has_key(loc, 'text')
          execute '/' . loc.text
        endif
        normal! zz
    endif
  endfor
endfunction
```

**Comment by voldikss** [comment]
Thanks. I've fixed it.

**Comment by noib3** [comment]
@voldikss What if one wants to use the custom opener passed as argument to the `--opener` flag for more than one file? Right now only the first one is opened in that way, all the other selected files are still opened with `execute 'edit ' loc.filename `.

**Comment by voldikss** [comment]
> @voldikss What if one wants to use the custom opener passed as argument to the `--opener` flag for more than one file? Right now only the first one is opened in that way, all the other selected files are still opened with `execute 'edit ' loc.filename `.

It's expected. We must use 'edit' after 'vsplit'(for example). Otherwise there will be a lot of splitting windows

**Comment by noib3** [comment]
But the files being selected could be anything, not just text files. In my personal use case I'm trying to write a command that checks what kind of file I'm trying to open, and then opens it accordingly. For example I could have selected 3 files: a text file, a pdf and an image. Even if I implemented a custom opener that does what I need, only the first file I select will be opened with that custom opener. The other two will always be opened in neovim. Could it be possible to pass *all* the selected files to that `--opener` function at once (say within a list)? Or maybe call the `--opener` for all the files, not just the first one?

**Comment by voldikss** [comment]
Sense reasonable. However if the `opener` is `split`, `vsplit` etc., only one split window should be opened, which means we shouldn't pass all files into `split` or `vsplit`. But in your case described above, we should pass all files into the `opener`, that custom opener.

I could not come up with an idea how to do that elegantly... 

Sorry for... PR welcome and I don't have much time for now.

**Comment by voldikss** [comment]
> Even if I implemented a custom opener that does what I need, only the first file I select will be opened with that custom opener. The other two will always be opened in neovim. 

Use `  autocmd BufEnter *.png,*.jpg,*.gif,*.pdf execute 'ExternalOpen'|bw`, you can define `ExternalOpen` by yourself.

Refer: https://github.com/voldikss/dotfiles/blob/79803efb0af19e56508abf241d27babc01eeb214/home/.config/nvim/init.vim#L248
