### ISSUE TITLE
`hiGroup` not follow `g:floaterm_border_highlight`

### ISSUE THREAD

**Issue by icefed** [voldikss/vim-floaterm#26]
`NormalFloat` will cause some color problem here I dont know why, and `Normal` is OK.
Then i found `hiGroup` not follow `g:floaterm_border_highlight`, this could be a forgotten work.

https://github.com/voldikss/vim-floaterm/blob/bddc6ffc0cb0d6bdd45f2f3f3962635fad70edbc/autoload/floaterm.vim#L224-L236

My config：
```
map <leader>m :FloatermToggle<CR>
tnoremap <Esc> <C-\><C-n>:FloatermToggle<CR>
let g:floaterm_winblend = 10
let g:floaterm_position = 'center'
let g:floaterm_border_highlight = 'Normal'
```

**Comment by voldikss** [comment]
Hi @icefed,
Actually the code you posted above is used to configure the background of the translation window. While the border's hightlight was affected by this code
https://github.com/voldikss/vim-floaterm/blob/bddc6ffc0cb0d6bdd45f2f3f3962635fad70edbc/autoload/floaterm.vim#L284

> NormalFloat will cause some color problem here

Could you give me more details or post a screenshot?

**Comment by icefed** [comment]
`let g:floaterm_border_highlight = 'Normal'NormalFloat `
![image](https://user-images.githubusercontent.com/3964419/72235299-52824d00-360c-11ea-92dc-dab26ce0c4c0.png)
`let g:floaterm_border_highlight = 'Normal'`
![image](https://user-images.githubusercontent.com/3964419/72235337-8cebea00-360c-11ea-884e-95d7c9677884.png)

**Comment by voldikss** [comment]
`let g:floaterm_border_highlight = 'Normal'` seems better, I'll fix it. Thank you for the advice!

**Comment by icefed** [comment]
`let g:floaterm_border_highlight = 'Normal'` and if not set `let g:floaterm_background = '#282828'` manually. Change `hiGroup` to `Normal` is OK.
![image](https://user-images.githubusercontent.com/3964419/72235507-7eea9900-360d-11ea-8244-f620c384100a.png)

**Comment by voldikss** [comment]
Option `g:floaterm_border_highlight` was replaced by `g:floaterm_border_color`.
