### ISSUE TITLE
`floaterm` does not open file in the host neovim process.

### ISSUE THREAD

**Issue by szsdk** [voldikss/vim-floaterm#260]
#### vim version
- Output of `vim --version`:
```
NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimpli
cit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3
-I/tmp/neovim-20201208-12195-1catj9q/build/config -I/tmp/neovim-20201208-12195-1catj9q/src -I/usr/local/include -I/tmp/neovim-20201208-12195-1catj9q/deps-build/include -I/Library/Developer/CommandLineTo
ols/SDKs/MacOSX11.0.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201208-12195-1catj9q/build/src/nvim/auto -I/tmp/neovim-20201208-12195-1catj9q/build/include
Compiled by sz@SZMacAir.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-4383c0f/share/nvim"

Run :checkhealth for more info
```
- Platform: 

  - [x] Linux
  - [x] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```

health#floaterm#check
========================================================================
## common
  - INFO: Platform: macos
  - INFO: Nvim: NVIM v0.5.0-dev+nightly
  - INFO: Plugin: 6b5da6a


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

1. `:FloatermToggle`
2. `floaterm a.txt`

### Actual behaviour
The `a.txt` opened in the floating terminal.

### Expected behaviour
Open `a.txt` in the host neovim process.

**Comment by voldikss** [comment]
Can not reproduce, but does the discussion in #256 helps?

If not, then open a floaterm and run the shell command (not ex command) `echo $EDITOR` and give me feedback.

**Comment by szsdk** [comment]
Yes, #256 helps me out. Please feel free to close this issue.

**Comment by voldikss** [comment]
> Yes, #256 helps me out. Please feel free to close this issue.

Great!. I would like to know about the detail.

**Comment by szsdk** [comment]
Same reason as #256. I have set the `$EDITOR` in my zshrc file. So I added this
```bash
    if [ -z $EDITOR ]; then
        export EDITOR="nvim"
    fi
```
to avoid overwriting. But I was wondering whether it is a good idea that vim-floaterm could use a more rare variable name to avoid such trouble.

**Comment by voldikss** [comment]
Thanks. That looks like the `EDITOR` was overrided.

> But I was wondering whether it is a good idea that vim-floaterm could use a more rare variable name to avoid such trouble.

Yes, I'm considering using `$FLOATERM`.

**Comment by voldikss** [comment]
Fixed. Now you can remove `    if [ -z $EDITOR ]; then...` stuff.

**Comment by szsdk** [comment]
So fast. Thanks.
