### ISSUE TITLE
make the terminal mode or normal mode easy to distinguish  for an opened floaterm

### ISSUE THREAD

**Issue by iqxd** [voldikss/vim-floaterm#264]
the builtin terminal shows its mode at status line , however floaterm don't have status line,
when running terminal tools with lots of shortkeys such as lazygit on floaterm，and forget what mode is ,
brings unexpected key press errors .
So could some distinguish colors or makers be added to floaterm between different modes?

**Comment by voldikss** [comment]
Sorry but no plan for this currently.

**Comment by voldikss** [comment]
There is a `--TERMINAL--` below the statusline if you've enabled `showmode`
![Screenshot_20210221_083246](https://user-images.githubusercontent.com/20282795/108612022-9fe00900-741f-11eb-9df4-6a4629601691.png)
