### ISSUE TITLE
Is it possible to to create a Floaterm only if it does not exist and open it elsewise?

### ISSUE THREAD

**Issue by divramod** [voldikss/vim-floaterm#265]
Hey, 

i really like floaterm more and more!
thx for developing it!

i have a usecase i couldn't find the right combination of functions for.

i like to assign a specifically named floaterm to a shortcut (i use whichkey).
for example: 
```
:FloatermNew --title=k9s k9s
```
creates the floatterm i want.
now i do some stuff there and after that i toggle-close it.
some time later i like to reopen/toggle the floaterm named k9s.
i can now use ```FloatermToggle k9s``` to reopen it.

my question now is, is it somehow possible to use ```FloatermToggle``` in a way like floatermNew, so that FloatermToggle could accept a command or the other way around, can i somehow say :FloatermNew to only open a new term if it not already exists?

i realized, that FloatermNew deletes the old term and creates a new one.

Maybe a new command like :FloatermNewOrOpen, which accepts all inputs which FloatermNew already accepts?

thx in advance for a hint into the right direction!

**Comment by voldikss** [comment]
Though it's not recommended behavior, you have to use some built in functions to satisfy your requirement.

https://github.com/voldikss/vim-floaterm/blob/c66412d238bd2e6c7b84c01a7e92b399bfbf1915/autoload/floaterm.vim#L30

https://github.com/voldikss/vim-floaterm/blob/c66412d238bd2e6c7b84c01a7e92b399bfbf1915/autoload/floaterm/terminal.vim#L174

**Comment by voldikss** [comment]
The `title` of a floaterm can be get using `b:floaterm_title` or `floaterm#config#get(bufnr, 'title')`, but I recommend using `name` attribute.

Function floaterm#buflist#gather() returns a list contains all the floaterm buffers.

Function floaterm#terminal#open_existing({bufnr}) opens the floaterm whose buffer number is {bufnr}.

**Comment by Pezhvak** [comment]
Here is my solution:

```
function ToggleK9s()
	local floatTermBufnr = vim.fn["floaterm#terminal#get_bufnr"]("k9s")

	if floatTermBufnr ~= -1 then
		vim.cmd(":FloatermToggle k9s")
	else
		vim.cmd(":FloatermNew --width=0.99 --height=0.99 --silent --name=k9s --title=k9s($1/$2) k9s")
		vim.cmd(":FloatermToggle k9s")
	end
end

vim.keymap.set("n", "<leader>tk", ":lua ToggleK9s()<CR>", { desc = "[T]oggle [K]9s" })
```
