### ISSUE TITLE
option to always open with --cwd=<root>

### ISSUE THREAD

**Issue by gennaro-tedesco** [voldikss/vim-floaterm#266]
#### If you are using neovim, just run `:checkhealth floaterm` and post the content below.

```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: macos
  - INFO: Nvim: NVIM v0.5.0-dev+1083-g1aec5ba85
  - INFO: Plugin: c66412d


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
let g:floaterm_autoclose = 2
let g:floaterm_keymap_toggle = '<F2>'
let g:floaterm_rootmarkers = ['.git']
let g:floaterm_opener = 'edit'
```

### Describe your question, feature request, or bug.

Given the above configuration, Floaterm does not toggle in the project root. Is it possible to have an option specify it, instead of having to always manually call it with `:FloatermNew --cmd=<root>`? Something along the lines of
```
let g:floaterm_dir = '<root>'
```
unless this option already exists and I overlooked it foolishly?

**Comment by voldikss** [comment]
I think the best approach is to define a new command by yourself to wrapp the `:FloatermNew`, e.g.

```vim
command! FloatermNewRoot FloatermNew --cwd=<root>
```

**Comment by voldikss** [comment]
Or bind `:FloatermNew --cwd=<root>` to a key mapping
