### ISSUE TITLE
:FloattermNew is resetting some of nvim config

### ISSUE THREAD

**Issue by rodhash** [voldikss/vim-floaterm#267]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first. `yep did that`

- Please make sure you are using the latest version of this plugin. `yep`

- It's better to use English as it's more friendly to other non-Chinese native users. `sure agree, lets use english`

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 

  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.4.4
  - INFO: Plugin: e4d5a5b


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):
- Nothing special here, I customized only border / color
- Also I ran the tests with minimal setup, with zero customization and the same issue happens.

```vim
hi Floaterm ctermbg=235
hi FloatermBorder ctermbg=235 ctermfg=cyan

```

### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

**Summary of the issue:** After using `:FloatermNew` either to run my Python code or just running purely `:FoatermNew` some config gets reset like I show in the GIF the parameter **sidescrolloff** gets reset.

In the first try I run my python code and in the 2nd try I run simply `:FloatermNew`. In both cases the value gets reset to zero.

### Actual behaviour
1. Open some Python code with nvim (or perhaps any filetype will behave the same not only Python code)
2. Check some nvim parameter's value like: `:set sidescrolloff?`
2. run `:FloatermNew`
3. Check again the same parameter, it'll be reset to default's value (zero) `:set sidescrolloff?`

### Expected behaviour
1. Run `:FloatermNew` without changing nvim's configs

### Screenshots(Optional, GIF is better)

![Peek 2021-02-27 15-46](https://user-images.githubusercontent.com/29671981/109397224-79850680-7914-11eb-9c6d-3314ad8ada37.gif)

ps: sorry for the laggy GIF, it's hard to record in Wayland. My gif is really lagging but I think it's possible to see the issue I refer to.

**Comment by voldikss** [comment]
Hi @rodhash In nvim 0.4, `sidescrolloff` option is a global variable while it can be a window local variable in nvim 0.5.

In nvim 0.4, if I set `sidescrolloff` option of floaterm window to `0`, then the global value of `sidescrolloff` will also be changed. But why I have to modify that option? Because I have to set sidescrolloff to `0` to resolve #96 and #218. 

So, I am sorry but there seems no solutions for this issue except upgrading your nvim to v0.5.

**Comment by rodhash** [comment]
> Hi @rodhash In nvim 0.4, `sidescrolloff` option is a global variable while it can be a window local variable in nvim 0.5.
> 
> In nvim 0.4, if I set `sidescrolloff` option of floaterm window to `0`, then the global value of `sidescrolloff` will also be changed. But why I have to modify that option? Because I have to set sidescrolloff to `0` to resolve #96 and #218.
> 
> So, I am sorry but there seems no solutions for this issue except upgrading your nvim to v0.5.

Hi @voldikss, alright thanks for the prompt feedback.

0.5 is the dev version right? Ok np I'll give it a try.

Thank you

**Comment by voldikss** [comment]
> > Hi @rodhash In nvim 0.4, `sidescrolloff` option is a global variable while it can be a window local variable in nvim 0.5.
> > In nvim 0.4, if I set `sidescrolloff` option of floaterm window to `0`, then the global value of `sidescrolloff` will also be changed. But why I have to modify that option? Because I have to set sidescrolloff to `0` to resolve #96 and #218.
> > So, I am sorry but there seems no solutions for this issue except upgrading your nvim to v0.5.
> 
> Hi @voldikss, alright thanks for the prompt feedback.
> 
> 0.5 is the dev version right? Ok np I'll give it a try.
> 
> Thank you

Yes, and 0.5 stable version might be released soon.

**Comment by rodhash** [comment]
Hello again!

Any idea if we have other values being changed? I mean, anything other than sidescrolloff?

**Comment by voldikss** [comment]
> Any idea if we have other values being changed? I mean, anything other than sidescrolloff is also changed?

Sorry but I do not know other than `sidescrolloff`.
