### ISSUE TITLE
Strange color in part of the border when changing floating background

### ISSUE THREAD

**Issue by oblitum** [voldikss/vim-floaterm#27]
![12:38:09_13-01-2020](https://user-images.githubusercontent.com/1269815/72270148-77be8d80-3603-11ea-8315-cbb8caa4130f.png)

```vim
autocmd vimrc VimEnter * let g:floaterm_background = g:color_backup_normal.bg
```

(I have to do it on `VimEnter` due to late variable)

**Comment by oblitum** [comment]
The strange color looks like the original float background color, so it seems two sections of the border didn't change.

**Comment by oblitum** [comment]
I'm using NeoVim 0.4.3.

**Comment by voldikss** [comment]
I can not reproduced this issue. What colorscheme are you using? Can you put all configuration of this plugin?

**Comment by oblitum** [comment]
I could not reproduce it with a minimal setting, only with my full `.vimrc`. I'll close it for now while I dig it locally.

**Comment by oblitum** [comment]
Ah, this happens because I set `set synmaxcol=250` in my `.vimrc`. I'm not sure whether there's a fix for the plugin if that is set? If not, then I think it should be mentioned in README.

**Comment by oblitum** [comment]
I have to set it to a minimum of around `set synmaxcol=500` to fix the problem.
