### ISSUE TITLE
Strange behavior for `git add -p` 

### ISSUE THREAD

**Issue by vanppo** [voldikss/vim-floaterm#270]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 

  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: macos
  - INFO: Nvim: NVIM v0.4.4
  - INFO: Plugin: d65d2aa


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
let g:floaterm_autoclose = 2
let g:floaterm_height = 0.9
let g:floaterm_width = 0.9
```

### Steps to reproduce

Using the minimal vimrc

```vim
call plug#begin(stdpath('data') . '/site/plugins')
Plug 'voldikss/vim-floaterm'
call plug#end()

set number

" Floaterm
let g:floaterm_autoclose = 2
let g:floaterm_height = 0.9
let g:floaterm_width = 0.9
nnoremap <silent> <leader>t :FloatermToggle<CR>
autocmd! FileType floaterm call s:floaterm_settings()
function! s:floaterm_settings() abort
  tnoremap <silent><buffer> <C-T> <C-\><C-N>:FloatermNew<CR>
  tnoremap <silent><buffer> <C-J> <C-\><C-N>:FloatermNext<CR>
  tnoremap <silent><buffer> <C-K> <C-\><C-N>:FloatermPrev<CR>
  tnoremap <silent><buffer> <ESC> <C-\><C-N>:FloatermToggle<CR>
endfunction
```

* execute `git add -p` in float terminal
* edit a hunk
* save the changes

### Actual behaviour
All changes I made were ignored and the whole hunk was added to the index

### Expected behaviour
Should add my edited changes to the index only

### Screenshots(Optional, GIF is better)
![image](https://user-images.githubusercontent.com/7381804/110081370-cbbba100-7dc6-11eb-96fd-3b29fc00ca74.png)
![image](https://user-images.githubusercontent.com/7381804/110081419-db3aea00-7dc6-11eb-987d-e781de41e490.png)
![image](https://user-images.githubusercontent.com/7381804/110081447-e68e1580-7dc6-11eb-92b7-8e376fd4b453.png)
![image](https://user-images.githubusercontent.com/7381804/110081478-f4439b00-7dc6-11eb-830f-0815a6397f06.png)

**Comment by voldikss** [comment]
Fixed, thanks.

**Comment by vanppo** [comment]
> Fixed, thanks.

Thanks for the quick fix. Is there any chance to edit the hunk with a new vim instance in the terminal window, like the old way. I've checked the option `g:floaterm_opener`, but none of the values can archieve that way.

**Comment by voldikss** [comment]
> Is there any chance to edit the hunk with a new vim instance in the terminal window, like the old way.

No options for this but you can override `$GIT_EDITOR` variable of the terminal. e.g. `export GIT_EDITOR=nvim`.

**Comment by vanppo** [comment]
> > Is there any chance to edit the hunk with a new vim instance in the terminal window, like the old way.
> 
> No such options for that but you can override `$GIT_EDITOR` variable of the floating terminal. e.g. `export GIT_EDITOR=nvim`.

Thanks for your suggestion. Or is there a way to show the terminal window again automaticly when I save the hunk.

**Comment by voldikss** [comment]
No. You have to define an `autocmd` by youself.

**Comment by voldikss** [comment]
This seems useful in some cases so I am going to add the feature into the plugin.

**Comment by vanppo** [comment]
Thanks, it works perfectly!
