### ISSUE TITLE
E740: Too many arguments for function floaterm#run

### ISSUE THREAD

**Issue by davidvalaz** [voldikss/vim-floaterm#274]
When I try and trigger a test with FloatermNew, via Neovim, I receive the following error:

```
E740: Too many arguments for function floaterm#run
```

The specific command is:

```
:FloatermNew node_modules/.bin/jest --color=always --no-coverage -t '^SearchFilter Ability to add/remove search criteria Allows a user to add a specific search criterion below the search box$' -- specs/components/SearchFilter.spec.js
```

When I open up a FloatermNew window and paste in the command, it works just fine. For reference this is a Javascript Jest test

### Environment
Neovim:

```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: macos
  - INFO: Nvim: NVIM v0.5.0-dev+1157-g0ab88c2ea
  - INFO: Plugin: 2d9107b


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

Lua config file:

```lua
g.floaterm_width = 0.8
g.floaterm_height = 0.8
g.floaterm_autoinsert = false
```

### Steps to reproduce

Run the command as above

### Actual behaviour
```
E740: Too many arguments for function floaterm#run
```

### Expected behaviour
No error

### Screenshots(Optional, GIF is better)
![Screen Shot 2021-03-19 at 10 05 23](https://user-images.githubusercontent.com/80173369/111764065-b9e3fe80-889a-11eb-9352-ba4afd3ce02a.gif)

**Comment by davidvalaz** [comment]
@voldikss let me know if you need me to provide any more information

**Comment by voldikss** [comment]
Hi @davidvalaz thanks for the bug report. 

I added the label `reproduce:pending` just because I got busy these days and have no time to testing this. Will try fixing this soon.

**Comment by voldikss** [comment]
Finally fixed it. A little hard for me.

**Comment by davidvalaz** [comment]
Can confirm this works like a dream. Appreciate this was a super nuanced issue so thank you. Floaterm continues to be core to my development life

**Comment by academo** [comment]
Thanks for the fix I was just coming to report this issue. It is working fine now.
