### ISSUE TITLE
Broot wrapper `create` verb issue

### ISSUE THREAD

**Issue by jalberto** [voldikss/vim-floaterm#277]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 

  - [ ] Linux
  - [ ] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.4.4
  - INFO: Plugin: ae7eea5


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available

```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim

```

### Describe your question, feature request, or bug.

When using verb `create` to add a new file, it opens the blank file in nested vim, this makes it harder to actually create the file as is hard to access command mode in the nested vim

### Steps to reproduce

- invoke broot
- use `create foo.txt`

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

### Actual behaviour

new file is opened in nested vim

### Expected behaviour

open new file in "parent2 vim

### Screenshots(Optional, GIF is better)

![image](https://user-images.githubusercontent.com/99927/113018788-2f947800-9181-11eb-9e71-d495bd3addb9.png)

**Comment by voldikss** [comment]
Sorry but this won't be supported. I do not use broot very often so I do not how to solve it. Maybe resolved in the future.
