### ISSUE TITLE
Open file from ranger without creating new pane

### ISSUE THREAD

**Issue by litearc** [voldikss/vim-floaterm#278]
I want to select a file from ranger and have it open in the current pane. I think it did this in a previous version, but currently, it creates a new pane. I couldn't find an option to do this in the key bindings or command list. Please help, thanks!

**Comment by voldikss** [comment]
Give me your config related to vim-floaterm. Also a gif would be better.

**Comment by litearc** [comment]
Just found the option - it was  `let g:floaterm_opener = 'edit'`. Sorry, should have read the documentation more closely. Closing this.
