### ISSUE TITLE
support float position use offset?

### ISSUE THREAD

**Issue by zdmgmail** [voldikss/vim-floaterm#280]
fzf.vim can set float position use offset : (https://github.com/junegunn/fzf.vim)

```
let g:fzf_layout = { 'window': { 'width': 0.7, 'height': 0.6 , 'yoffset':0.3}}
```

could you also support offset postion in floaterm?

**Comment by voldikss** [comment]
Sorry but no such plan as it would be conflict with `g:floaterm_position`.
