### ISSUE TITLE
`--autoclose=2` does not works when execute command in `$SHELL`

### ISSUE THREAD

**Issue by mattbui** [voldikss/vim-floaterm#281]
#### If you are using neovim, just run `:checkhealth floaterm` and post the content below.

```markdown

health#floaterm#check
========================================================================
## common
  - INFO: Platform: macos
  - INFO: Nvim: NVIM v0.4.4
  - INFO: Plugin: a4c834b


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
let g:floaterm_opener = 'edit'
let g:floaterm_width = 0.8

autocmd  FileType floaterm set nonumber norelativenumber

" Key mappings for floaterm
nnoremap   <silent>   <C-t>   :FloatermToggle<CR>
tnoremap   <silent>   <C-t>   <C-\><C-n>:FloatermToggle<CR>
tnoremap   <silent>   <C-q>   <C-\><C-n>:FloatermKill<CR>
tnoremap   <silent>   <M-Tab>   <C-\><C-n>:FloatermNext<CR>
tnoremap   <silent>   <M-n>   <C-\><C-n>:FloatermNew<CR>

" Navigate with ctrl+hjkl (required tmux-vim-nav)
autocmd  FileType floaterm tnoremap <buffer> <silent> <C-h> <C-\><C-n>:TmuxNavigateLeft<CR>
autocmd  FileType floaterm tnoremap <buffer> <silent> <C-j> <C-\><C-n>:TmuxNavigateDown<CR>
autocmd  FileType floaterm tnoremap <buffer> <silent> <C-k> <C-\><C-n>:TmuxNavigateUp<CR>
autocmd  FileType floaterm tnoremap <buffer> <silent> <C-l> <C-\><C-n>:TmuxNavigateRight<CR>
```

### Describe your question, feature request, or bug.

I need to execute command/job in `$SHELL` and autoclose it when it finished. But seem like the autoclose option does not work when using the `!` option for `$SHELL` mode.

### Steps to reproduce

- `:FloatermNew --autoclose=2 echo "hello"` will autoclose the terminal
- `:FloatermNew! --autoclose=2 echo "hello"` the terminal will stay

### Expected behaviour
`:FloatermNew! --autoclose=2 echo "hello"` will close the terminal

**Comment by mattbui** [comment]
My current workaround for this: `:FloatermNew! --autoclose=2 echo "hello" && exit`

**Comment by voldikss** [comment]
Can not reproduce. Have you tried using minimal vimrc?
