### ISSUE TITLE
`floaterm#edita#neovim#util#mode` returns wrong mode if `address` matches `localhost:<port>`

### ISSUE THREAD

**Issue by jdeut** [voldikss/vim-floaterm#284]
```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.5.0-dev+1249-ge652b2987
  - INFO: Plugin: b774770


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

If `NVIM_LISTEN_ADDRESS` matches the pattern `localhost:<port>` invoking ` $ floaterm <file>` inside a floating Floaterm window fails to open `<file>` because mode is not set to `tcp` .

`tcp` mode is only set if address is given as a series of tuples.

**Comment by voldikss** [comment]
Hi @jdeut I can not reproduce this, could you provide steps to produce the issue?

**Comment by voldikss** [comment]
`echo floaterm#edita#neovim#util#mode('127.0.0.1:9999')` returns `1`.

**Comment by jdeut** [comment]
If you start nvim with
```
$ NVIM_LISTEN_ADDRESS=localhost:9999 nvim     # mode is not set to tcp
```
instead of
```
$ NVIM_LISTEN_ADDRESS=127.0.0.1:9999 nvim     # mode is set to tcp
```
`floaterm` loses some of its functionality because mode is not set to tcp. I wouldn't name it a bug if it weren't so common to regard directly accessible computers as `localhost` and not as `127.0.0.1` as you name it.

**Comment by voldikss** [comment]
Thanks, that makes sense. I'll fix it.
