### ISSUE TITLE
an artifact of the floating window is left behind if the current terminal is moved to a new tab page

### ISSUE THREAD

**Issue by jdeut** [voldikss/vim-floaterm#285]
```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: linuxartifacts
  - INFO: Nvim: NVIM v0.5.0-dev+1249-ge652b2987
  - INFO: Plugin: b774770


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

If i invoke `:wincmd T` from the current floating terminal residing in an initial tab page the terminal is moved to a new tab page as expected. At the same time an artifact of the floating window is left behind on the initial tab. The following images illustrates the process and the artifact.

#### Initial tab page with floating terminal

![Screenshot-20210417150301-1922x1048](https://user-images.githubusercontent.com/1739296/115114388-5c24fe00-9f8f-11eb-9791-b674bba58689.png)

#### Artifact of floating window on initial tab page
![Screenshot-20210417150351-1922x1048](https://user-images.githubusercontent.com/1739296/115114306-dd2fc580-9f8e-11eb-940c-7925617279db.png)

#### Terminal in new tab page
![Screenshot-20210417150335-1922x1048](https://user-images.githubusercontent.com/1739296/115114346-15370880-9f8f-11eb-95ad-b6cd97aa8662.png)

**Comment by voldikss** [comment]
Sorry but I can not fix this because the current implementation of the floating border is tricky. This could not be fixed until using the buint in `border` from `nvim_open_win()`.

**Comment by jdeut** [comment]
Thank you for your answer!!

If i understand you correct the artifact would go away if floaterm would use the native border implementation of nvim!?

Best regards and thank you for all your efforts

**Comment by voldikss** [comment]
> If i understand you correct the artifact would go away if floaterm would use the native border implementation of nvim!?

Yes.
