### ISSUE TITLE
Opening Floaterm changes all the other tabs pwd to the current one

### ISSUE THREAD

**Issue by baldore** [voldikss/vim-floaterm#287]
#### Environment

```
NVIM v0.5.0-dev+91cdc1198
Build type: Release
LuaJIT 2.1.0-beta3
```

  - [ ] Linux
  - [X] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content below.

```markdown
health#floaterm#check
========================================================================
## common
  - INFO: Platform: macos
  - INFO: Nvim: NVIM v0.5.0-dev+91cdc1198
  - INFO: Plugin: b774770


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
let g:floaterm_autoclose = 1
let g:floaterm_width = 0.95
let g:floaterm_height = 0.95

nnoremap <leader>gl :<C-u>FloatermNew lazygit<cr>

command Conf FloatermNew lazygit --git-dir=$HOME/.cfg/ --work-tree=$HOME
```

### Steps to reproduce

Using the minimal vimrc

```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'voldikss/vim-floaterm'

call plug#end()
```

### Actual behaviour
There's a bug when working with multiple tabs. If each tab has its own working directory using `tcd` and you call `FloatermNew`, it changes other tabs working directory to the current one.

Tried with a minimal setup and it still happens.

### Expected behaviour
It should not change the current working directory of the other tabs.

### Screenshots(Optional, GIF is better)
![demo](https://user-images.githubusercontent.com/3131037/115433287-3c265200-a1bc-11eb-9e49-e473b9b21768.gif)

**Comment by thenewvu** [comment]
@voldikss I believe this [commit](https://github.com/voldikss/vim-floaterm/commit/eeb3f6b5c98bde26752ebe0fbe1359fc974cbdcd) causes this bug again sometime
