### ISSUE TITLE
Lua configuration with floats doesnt't work for floats (eg. 1.0)

### ISSUE THREAD

**Issue by matthis-k** [voldikss/vim-floaterm#289]
When adding `vim.g.floaterm_width = 1.0` the width is a fixed 1, instead of the relative 1.0 * width (because lua only uses floats?). Maybe add a value check and just do it relative for all numbers <= 1, because noone wants a fixed width of 1 anyway :P
`vmi.cmd("let g:floaterm_width=1.0")` works, but it's ugly

**Comment by voldikss** [comment]
Then use 0.99 may help.

**Comment by matthis-k** [comment]
Then it covers everything exept one or two columns

**Comment by matthis-k** [comment]
ok then i'll roll with the ungly solution :P
