### ISSUE TITLE
Opening a new floaterm with command line

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#29]
For example, some commands like the following would be handy:

```
:FloatermNew ls
:FloatermToggle ls -alh
```

which should open a floating terminal window and execute the command after the shell startup. If there is an user-defined event or callback, one can use autocmd to emulate keyboard input but not sure if this is possible.

We can also consider extending the vimscript APIs (e.g. `call g:floaterm.new(command string or argv)`). What would be the best way for this?

**Comment by Olical** [comment]
I'd love this so I can open lazygit within Neovim: https://github.com/jesseduffield/lazygit

I was going to write that as a plugin myself but adding it here would make a lot of sense :smile:

**Comment by voldikss** [comment]
Currently the code structure is quite terrible, I plan to refactor the code first. After that, I will try to implement this feature.

**Comment by Olical** [comment]
Sounds great! If I end up hacking together my own thing I'll let you know here, might be some things you can take from it :smile: (I'd be writing it in Fennel with https://github.com/Olical/aniseed though :grimacing:)

**Comment by voldikss** [comment]
> For example, some commands like the following would be handy:
> 
> ```
> :FloatermNew ls
> :FloatermToggle ls -alh
> ```
> 
> which should open a floating terminal window and execute the command after the shell startup. If there is an user-defined event or callback, one can use autocmd to emulate keyboard input but not sure if this is possible.
> 
> We can also consider extending the vimscript APIs (e.g. `call g:floaterm.new(command string or argv)`). What would be the best way for this?

I read the doc and found a built in function `chansend()` to handle this. So this is easy. I plan to make `flaoterm#new()` receive an argument `cmd` to do execute some commands after `TermOpen`.

**Comment by voldikss** [comment]
> For example, some commands like the following would be handy:
> 
> ```
> :FloatermNew ls
> :FloatermToggle ls -alh
> ```
> 
> which should open a floating terminal window and execute the command after the shell startup. If there is an user-defined event or callback, one can use autocmd to emulate keyboard input but not sure if this is possible.
> 
> We can also consider extending the vimscript APIs (e.g. `call g:floaterm.new(command string or argv)`). What would be the best way for this?

I read the doc and found a built in function `chansend()` to handle this. So this is easy. I plan to make `flaoterm#new()` receive an argument `cmd` to do execute some commands after `TermOpen`.

**Comment by voldikss** [comment]
Hi all, I've drafted a PR for this feature. Currently only add command argument for `FloatermNew`. Is there any necessary to make for other commands(`FloatermNext`, `FloatermPrev`, `FloatermToggle`)? 

Typical use cases such as `FloatermNew lazygit` works normally.

**Comment by voldikss** [comment]
I also want to add `fzf`/`ranger` support, but it would be a more complicated work since it depends on rpc-communication which I'm not familiar with. But suggestions about anything are welcomed.
