### ISSUE TITLE
Broot's wrapper does not override enter key

### ISSUE THREAD

**Issue by talw** [voldikss/vim-floaterm#291]
### Describe bug

It looks like the order of configs passed to `--conf` in broot's wrapper is
reversed.  That means that the default broot configuration overrides
floaterm's broot wrapper's configuration.  But since all that floaterm is doing to the
configuration is binding to the enter key, it would make sense for it to
override the enter key binding from the default configuration.

Currently with how things are, users who did not bind the enter key to anything in
their default configuration will have no problem.  But users who did change
the enter key in their default configuration to do something else, this
something else will override broot's wrapper which is not desirable because
when I'm opening broot through floaterm, I expect the wrapper to take
precedence (so that enter key opens the file in the parent editor).

Changing
```
let s:broot_confpath = s:broot_default_confpath . ';' . s:broot_wrapper_confpath
```
to
```
let s:broot_confpath = s:broot_wrapper_confpath . ';' . s:broot_default_confpath
```

Fixed the issue.

Apologies if I misunderstood, and that order was by design.

If it's OK and I haven't misunderstood the design, I have a pull request for this one line change.

### Steps to reproduce

In your default broot config, have some binding to the enter key

```
{
  verbs:
    {
      invocation: edit
      key: enter
      shortcut: e
      execution: "$EDITOR +{line} {file}"
      leave_broot: false
    }
}
```

Run broot with floaterm and try to open a file

### Actual behaviour

The enter key from the default configuration takes precedence so floaterm's wrapper's enter key is ignored and the file is opened in a nested editor.

### Expected behaviour

The enter key from the default configuration is overridden by floaterm's wrapper's enter key so that the file is opened in the parent editor.

**Comment by voldikss** [comment]
Closed by #292
