### ISSUE TITLE
floaterm command doesn't work with sudoedit

### ISSUE THREAD

**Issue by the10thWiz** [voldikss/vim-floaterm#298]
The `floaterm` script works for git commit, but not sudoedit

In order to make `floaterm` work with sudoedit, the editor process needs to wait for the file to be closed,
just like the way it works with git commits.

This would be very handy, but I'm not familiar enough with vim-floaterm to make it work.

Thanks!

**Comment by voldikss** [comment]
What's `sudoedit` exactly?
