### ISSUE TITLE
Error on vim8: No such group or event TermClose

### ISSUE THREAD

**Issue by silvioprog** [voldikss/vim-floaterm#3]
Hello.

On vim8, this error is raised as soon as `:FloatermToggle` is performed.

Sorry for sending a screen shot, but the message desapear before I could copy it.

![image](https://user-images.githubusercontent.com/1456829/64440703-d34f9c00-d0a2-11e9-9210-523b3ce9daa8.png)

Thank you!

**Comment by voldikss** [comment]
This is not available on Vim8 because the popup won't let your cursor in the window.

**Comment by voldikss** [comment]
Maybe I should add a note in README that this plugin is only nvim-usable.

**Comment by silvioprog** [comment]
Oh, sorry. I misunderstood it cause its name is `vim-floaterm`, so I though it could work on VIM. ^^'

**Comment by voldikss** [comment]
BTW, next time if you want to copy the message in the bottom, use this function
```vim
function! TabMessage(cmd) abort
  redir => message
  silent execute a:cmd
  redir END
  if empty(message)
    echohl Error
    echo "no output"
    echohl None
  else
    new
    setlocal buftype=nofile bufhidden=wipe noswapfile nobuflisted nomodified
    silent put=message
  endif
endfunction
command! -nargs=+ -complete=command  TabMessage call TabMessage(<q-args>)
```
Then you can use `:TabMessage message` and get that message
