### ISSUE TITLE
Switch modes without mouse.

### ISSUE THREAD

**Issue by Deshdeepak1** [voldikss/vim-floaterm#301]
How to leave insert mode and enter normal mode without mouse in floaterm?
Esc doesn't do the job.

**Comment by voldikss** [comment]
<C-\><C-n>

**Comment by Deshdeepak1** [comment]
It changes font size

**Comment by voldikss** [comment]
update: `<C-\>`

**Comment by Deshdeepak1** [comment]
Tried, still in insert mode.

**Comment by voldikss** [comment]
update: <C-\\>\<C-n>

**Comment by Deshdeepak1** [comment]
Thanks for the patience.
