### ISSUE TITLE
rg can't open a floaterm

### ISSUE THREAD

**Issue by zombo** [voldikss/vim-floaterm#306]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`: 8.2.2366
- Platform: 

  - [ ] Linux
  - [ ] Mac OS X
  - [ x] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown

```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
command! Broot FloatermNew --width=0.8 --height=0.8 Broot
command! Rg FloatermNew --width=0.8 --height=0.8 rg
```

### Describe your question, feature request, or bug.
the rg.exe and bat.exe have been placed into the system path.

:Rg or :FloatermNew rg

no term showed

Broot is OK

### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

**Comment by voldikss** [comment]
Can you try `:term rg`?

**Comment by ChanthMiao** [comment]
Well, here is the reason:
https://github.com/voldikss/vim-floaterm/blob/399cb86a15b7f3ef32ba40edda0ee00f2bdb842b/autoload/floaterm/wrapper/rg.vim#L36

The fzf add this option support in
https://github.com/junegunn/fzf/commit/0f9cb5590ec0a397143a7a4caf003a54885f4375

If you install fzf from system package manger, it may be too old (< 0.22.0).
