### ISSUE TITLE
The cursor did not reach the original window after Ranger exited

### ISSUE THREAD

**Issue by 13396433778** [voldikss/vim-floaterm#308]
#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:NVIM v0.6.0-dev  
- Platform: 

  - [ ] Linux
  - [ ] Mac OS X
  - [x] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown
## common
    - INFO: Platform: linux                                                                                    
    - INFO: Nvim: NVIM v0.6.0-dev                                                                              
    - INFO: Plugin: daf9389                            
## terminal
    - OK: Terminal emulator is available                
## floating
    - OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
let g:floaterm_opener = 'tabe'                   
let g:floaterm_autoclose = 0                                                                 
let g:floaterm_height = 0.7                                                                         
let g:floaterm_width = 0.7
```

### Describe your question, feature request, or bug.
When I run Ranger with FloatTerm. Exit from Ranger without opening files.The cursor in the file moves to the window of another plug-in.
another plug is wfxr/code-minimap
### Steps to reproduce

Using the minimal vimrc

```vim
set hidden
filetype plugin indent on
syntax on
```

1.perform: FloatermNew ranger
2.After opening the Ranger, press Q to exit

### Screenshots(Optional, GIF is better)

https://user-images.githubusercontent.com/69684715/127169670-2cb07259-fbdc-4ab5-b030-b134fa013a01.mp4

**Comment by voldikss** [comment]
Sorry but this can not be controlled by vim-floaterm. This problem is unfixable.
