### ISSUE TITLE
ls show in result

### ISSUE THREAD

**Issue by zxf4399** [voldikss/vim-floaterm#309]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 

  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown

health#floaterm#check
========================================================================
## common
  - INFO: Platform: macos
  - INFO: Nvim: NVIM v0.5.0
  - INFO: Plugin: daf9389


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
" ===
" === vim-floaterm
" ===

let g:floaterm_keymap_prev   = '<Leader>fp'
let g:floaterm_keymap_next   = '<Leader>fn'
let g:floaterm_keymap_toggle = '<Leader>ft'
let g:floaterm_keymap_kill   = '<Leader>fk'
```

### Describe your question, feature request, or bug.

ls will show in result

### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
filetype plugin indent on
syntax on

call plug#begin('~/.config/nvim/plugged')

Plug 'voldikss/vim-floaterm'

call plug#end()

" ===
" === vim-floaterm
" ===

let g:floaterm_keymap_prev   = '<Leader>fp'
let g:floaterm_keymap_next   = '<Leader>fn'
let g:floaterm_keymap_toggle = '<Leader>ft'
let g:floaterm_keymap_kill   = '<Leader>fk'

```

### Actual behaviour

ls will show in result 

### Expected behaviour

ls will not show in result 

### Screenshots(Optional, GIF is better)

![image](https://user-images.githubusercontent.com/55656772/127796607-c10d89fd-5f6e-4c1a-a3a0-e1ff7b682cb6.png)

**Comment by voldikss** [comment]
This might be related to your terminal.

**Comment by zxf4399** [comment]
> This might be related to your terminal.

I found this error in tmux

**Comment by voldikss** [comment]
So this was resolved right. I will close the issue. If it still exists feel free to open.
