### ISSUE TITLE
FloatermNew doesn't listen to my options

### ISSUE THREAD

**Issue by jackiboi307** [voldikss/vim-floaterm#310]
I am trying to run the following command:

`FloatermNew --floaterm_wintype='split' --floaterm_position='botright' --floaterm_autoclose=1 python %`

I've tried both " and ', vsplit and split, no quotation marks but nothing works. It still opens a floating window in the center that shows a "[Process exited 0]" when the program exits and quits the terminal after any key press.

I've used autoclose=0, 1 and 2 but it does the same thing.

Thanks in advance

**Comment by voldikss** [comment]
```
FloatermNew --floaterm_wintype='split' --floaterm_position='botright' --floaterm_autoclose=1 python %
```
to
```
FloatermNew --wintype='split' --position='botright' --autoclose=1 python %
```
