### ISSUE TITLE
Change working directory using Vifm

### ISSUE THREAD

**Issue by rashil2000** [voldikss/vim-floaterm#313]
Hi!

(This isn't a bug report so sorry if I'm ignoring the issue template.)

The Vifm wrapper is just plain awesome - it has made opening random files a literal breeze.

However, I couldn't find a way to open _directories_ using the vifm wrapper. Currently I manually go to the desired directory and run `nvim .` there from my shell so that neovim opens in that directory. Is there a way to do this using the wrapper, inside neovim itself?

Thanks in advance.

**Edit:** I just saw a similar issue for ranger here #273. Wondering if it's the same case with Vifm 🤔

**Comment by rashil2000** [comment]
Reading the source of Vifm wrapper, I saw that it uses the `--choose-files` option to open the files.
Vifm has a similar option called `--choose-dir` that prints the last visited directory. Can that be used?

**Comment by rashil2000** [comment]
I wrote a wrapper for this (very similar to vifm wrapper):

**vifm_dir.vim**

```vim
" vim:sw=2:
  " ============================================================================
  " FileName: vifm_dir.vim
  " Author: rashil2000 <mail@rashil2000.me>
  " GitHub: https://github.com/rashil2000
  " ============================================================================

  function! floaterm#wrapper#vifm_dir#(cmd, jobopts, config) abort
    let s:vifm_tmpfile = tempname()
    let original_dir = getcwd()
    lcd %:p:h

    let cmdlist = split(a:cmd)
    let cmd = 'vifm --choose-dir "' . s:vifm_tmpfile . '"'
    if len(cmdlist) > 1
      let cmd .= ' ' . join(cmdlist[1:], ' ')
    else
      let cmd .= ' "' . getcwd() . '"'
    endif

    exe "lcd " . original_dir
    let cmd = [&shell, &shellcmdflag, cmd]
    let jobopts = {'on_exit': funcref('s:vifm_dir_callback')}
    call floaterm#util#deep_extend(a:jobopts, jobopts)
    return [v:false, cmd]
  endfunction

  function! s:vifm_dir_callback(job, data, event, opener) abort
    if filereadable(s:vifm_tmpfile)
      let foldernames = readfile(s:vifm_tmpfile)
      if !empty(foldernames)
        if has('nvim')
          call floaterm#window#hide(bufnr('%'))
        endif
        exe "cd " . foldernames[0]
      endif
    endif
  endfunction
```

Is it okay if I send a PR?

**Comment by voldikss** [comment]
Sorry for the late response. I think we should modify vifm.vim instead is adding another wrapper. 

Maybe isditectory function helps

**Comment by rashil2000** [comment]
> I think we should modify vifm.vim instead is adding another wrapper.

That was my initial thought too. But how would we determine whether the command `:Floaterm vifm` wants to select files or wants to select directories? Of course we would want to determine this in a way so that breaking changes are minimized.

**Comment by rashil2000** [comment]
> ...wants to select files or wants to select directories...

Do wrappers support additional arguments? Something like `:Floaterm vifm` for files (current behaviour) and `:Floaterm vifm --dir` for selecting directories. If this is possible, then we can implement both functionalities in the same file vifm.vim

**Comment by voldikss** [comment]
> Edit: I just saw a similar issue for ranger here #273. Wondering if it's the same case with Vifm thinking

Hmm I it's not.

**Comment by voldikss** [comment]
I still don't understand what "open a directory" means... Could you supply a gif let me know what you want?

**Comment by rashil2000** [comment]
By opening a directory I mean changing the current working directory inside vim. It can be manually done by typing `cd /your/path/here` in  Command mode too, but it's slightly cumbersome to type out the path everytime.

**Comment by voldikss** [comment]
> By opening a directory I mean changing the current working directory inside vim

Oh, you mean this..... I see.

You want to change the cwd automatically as soon as you pick a file in vifm and open that file? Am i right?

**Comment by rashil2000** [comment]
It's not necessary that the directory would be the same as that of the file I pick (it should be the file's VCS root in that case, but this will introduce much complexities).

So it's not related to any files. I just want the working directory to change, independent f any files in it.

**Comment by rashil2000** [comment]
> Maybe isdirectory function helps

I have used this and sent a PR.

**Comment by rashil2000** [comment]
What do you mean? I didn't understand the question.
