### ISSUE TITLE
[Feature Request] Treat 1 as 100% for width and height

### ISSUE THREAD

**Issue by francisco285** [voldikss/vim-floaterm#316]
Setting `g:floaterm_width` and `g:floaterm_height` to 0.99 makes floaterm use screen_height - 1 and screen_width - 1, setting them to 1 makes floaterm try to use only one line and one column. Since it has no practical usage and floaterm shows a warning when we do this, it'd be better if 1 was treated as 100% so floaterm takes the whole screen.

**Comment by voldikss** [comment]
Thanks for the suggestion.

But I feel it makes sense to preserve `1` and show warning. Treating `1` and `2` as 100% for width and height adding unneccessary complexity for the plugin.
