### ISSUE TITLE
[Feature request] Support for jupyter-like cell sending to REPL

### ISSUE THREAD

**Issue by paniash** [voldikss/vim-floaterm#317]
#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 

  - [X] Linux

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown

health#floaterm#check
========================================================================
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.5.0
  - INFO: Plugin: 9716765


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
let g:floaterm_wintype = 'split'
let g:floaterm_position = 'belowright'
let g:floaterm_height = 15
let g:floaterm_keymap_toggle = '<Space>f'
```

### Describe your question, feature request, or bug.

It would be nice to have support for jupyter-cell like functionality (for e.g. present in vim-slime. See [here](https://github.com/jpalardy/vim-slime#advanced-configuration)) in the form of delimiters specifying the cells.

**Comment by voldikss** [comment]
Thanks for the suggestion however the plugin is not focused on the REPL feature. You should consider using vim-slime for a better REPL usage. Sorry about that.
