### ISSUE TITLE
Support for Packer Plugin management

### ISSUE THREAD

**Issue by gmcusaro** [voldikss/vim-floaterm#320]
Support for [Packer](https://github.com/wbthomason/packer.nvim) would be nice.

**Comment by voldikss** [comment]
The support for packer plugin should have existed. Why and what should I do to support packer? 

As far as I know, we can use packer.nvim to install and manage vim-floaterm without do other stuff, right?

**Comment by gmcusaro** [comment]
It may have been a packer problem, with the latest update the installation works. I am also investigating whether it affected neovim v0.5.1.

Anyway, you can add this in README  ## Installation:

- Packer

```lua
  use {
    'nvim-telescope/telescope.nvim',
    requires = { {'nvim-lua/plenary.nvim'} }
  }
```

**Comment by gmcusaro** [comment]
It may have been a packer problem, with the latest update the installation works. I am also investigating whether it affected neovim v0.5.1.

Anyway, you can add this in README ## Installation:

	•	Packer

```lua
  use {
    'voldikss/vim-floaterm'
  }
```

**Comment by RaZ0rr-Two** [comment]
But isn't this pretty straigtforward? I don't think there's any need for that.
