### ISSUE TITLE
Open in a tmux popup

### ISSUE THREAD

**Issue by farzadmf** [voldikss/vim-floaterm#321]
#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown

health#floaterm#check
========================================================================
## common
  - INFO: Platform: linux
  - INFO: Nvim: NVIM v0.6.0-dev+43-g02bf251bb
  - INFO: Plugin: 9716765


## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

Not putting anything here since it's a question rather than a bug

### Describe your question, feature request, or bug.

Hi, `fzf` has a helper script called [`fzf-tmux`](https://github.com/junegunn/fzf/blob/master/bin/fzf-tmux), which allows opening the `fzf` window in a `tmux` popup window (if I'm not mistaken, this was introduced in `tmux >= 3.2`)

For example, if I set these options:
```vim
if exists('$TMUX')
  let g:fzf_layout = { 'tmux': '-p90%,90%' }
else
  let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.9 } }
endif
```

when I try to open `fzf`, it will open in my `tmux` popup window (according to the help, the options passed to `fzf_layout ... tmux` is passed to the `fzf-tmux` script I mentioned.

I was wondering if a similar thing can be implemented in `floaterm`, which, for me personally, would be AMAZING!

### Steps to reproduce

Using the minimal vimrc

Not putting a `vimrc` here since it's a question rather than a bug

### Actual behaviour

N/A

### Expected behaviour

N/A

**Comment by voldikss** [comment]
> I was wondering if a similar thing can be implemented in floaterm, which, for me personally, would be AMAZING!

Sorry but this seems imposibble. And a vim plugin should not touch tmux related stuff.
