### ISSUE TITLE
floaterm_opener breaks with neovim 0.6.0

### ISSUE THREAD

**Issue by rmagillxyz** [voldikss/vim-floaterm#322]
fyi `floaterm_opener` with the `tabe` option seems to be broken on neovim version 0.6.0. I just reverted to version 0.5.0 and it's working again. You can close this issue, but I just wanted to give you a head's up. I only tested this with lf.vim.

**Comment by voldikss** [comment]
I tested with the newest nvim but can not reproduced it.

```
:FloatermNew --opener=tabe lf
```

Can you test it again? thanks.
