### ISSUE TITLE
[Feature Request] position relative to focus window

### ISSUE THREAD

**Issue by zdmgmail** [voldikss/vim-floaterm#323]
`FloatermNew --width=winwidth(0) --position=bottom`

this `position=bottom` will relative to vim,  hope have position relative to current focus window

(I know can use  `--wintype=split`) , but want to use float window

**Comment by voldikss** [comment]
Thanks for the suggestion, however this exceeds my technique scope, also I am considering reduce the complexity of the plugin to make it less redundant. So sorry about that but this won't be implemented.
