### ISSUE TITLE
error: No Matching autocommand for acwrite buffer

### ISSUE THREAD

**Issue by zhaogangang** [voldikss/vim-floaterm#325]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 

  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown

```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim

```

### Describe your question, feature request, or bug.
when i execute command wqa occur error
### Steps to reproduce
open a floaterm and execute command wqa
Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

**Comment by voldikss** [comment]
Hi @zhaogangang sorry for the late response. I'm pretty busy recently.....

The problem got resolved?

**Comment by zhaogangang** [comment]
> Hi @zhaogangang sorry for the late response. I'm pretty busy recently.....
> 
> The problem got resolved?

not yet, i found same to issue #230
