### ISSUE TITLE
How to exit floaterm directly by entering `exit`?

### ISSUE THREAD

**Issue by zetatez** [voldikss/vim-floaterm#326]

**Comment by voldikss** [comment]
Just enter `exit` in the terminal and floaterm exits.

**Comment by zetatez** [comment]
I entered exit, but can not exit.

best !
J.

**Comment by zetatez** [comment]
﻿I entered exit, but can not exit.

best !
J.

**Comment by voldikss** [comment]
Could you provider a screenshot?

**Comment by zetatez** [comment]
best !
J.
