### ISSUE TITLE
Truncated when output is too long

### ISSUE THREAD

**Issue by ssssimplesss** [voldikss/vim-floaterm#330]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 

  - [ ] Linux
  - [ ] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown
## common
INFO: Platform: linux
INFO: Nvim: NVIM v0.6.0
INFO: Plugin: 399cb86

## terminal
OK: Terminal emulator is available
OK: Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim
let g:floaterm_keymap_new = 'tt'
let g:floaterm_keymap_new = 'tj'
let g:floaterm_keymap_new = 'tk'
let g:floaterm_keymap_new = '<Space>t'
let g:floaterm_keymap_new = '<Space>k'
let g:floaterm_width = 0.8
let g:floaterm_height = 0.8
```

### Describe your question, feature request, or bug.

The output will be truncated when it is too long. Such as when I use _ps -aux_ the output is incomplete as shown in the pic
![屏幕截图 2021-12-28 000354](https://user-images.githubusercontent.com/93849612/147488564-e1cfb705-2591-4692-ac13-b221440192d3.png)

**Comment by adigitoleo** [comment]
Unable to reproduce this on neovim 0.6. I suspect the issue is with your shell, or neovim.
