### ISSUE TITLE
I want to open floaterm with path of current file,the param of options won't expand.

### ISSUE THREAD

**Issue by jqhr** [voldikss/vim-floaterm#334]
### Environment

- vim 8.2.2434
- Platform: 
  - [x ] Linux (Debian in wsl)
  - [ ] Mac OS X
  - [ ] Windows

## Question
I want to open floaterm with current file path, I try the follow cmd, but not work.
```vim
:FloatermNew --cwd=%:h
```
but the result was
![屏幕截图 2022-01-12 091042](https://user-images.githubusercontent.com/23305067/149046272-bd759279-c474-47ad-8e9f-ca185a5d4580.png)

How can I do?

**Comment by adigitoleo** [comment]
You can work around this by adding a `cd` in the command: https://github.com/voldikss/vim-floaterm/issues/183#issuecomment-700412596

If I recall correctly, floaterm parses command arguments manually, so we would need to add filename modifier parsing.

**Comment by adigitoleo** [comment]
Nevermind, it's already implemented.

`FloatermNew --cwd=<buffer>`

Use literal `<buffer>`. Documented in README but not in helpfile I believe.

**Comment by voldikss** [comment]
Expansion only works for the **command** part, it does't work for **options**. 

https://github.com/voldikss/vim-floaterm/issues/334#issuecomment-1030508983 is the right solution. Thanks adigitoleo!

**Comment by jqhr** [comment]
Great!. Thank you very much
