### ISSUE TITLE
Vim 下面使用 floaterm+ranger 乱码

### ISSUE THREAD

**Issue by skywind3000** [voldikss/vim-floaterm#335]
```VimL
:FloatermNew ranger
```

一开始 ranger 正常显示，然后稍微一动下 ranger 的光标屏幕就乱了：

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/3035071/149892114-41ca394a-cb15-42c9-9a84-1ec4d71cfa62.png">

或者

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/3035071/149891419-d4bca7c4-5776-460c-9385-a23d9baa68f3.png">

我自己在 popup 里跑 ranger 没问题：

<img width="677" alt="image" src="https://user-images.githubusercontent.com/3035071/149891683-16b3cf9e-4553-4a38-bd8a-3e5f47b6527b.png">

经过调查后发现 term_start 里指定 term_rows, term_cols 以后，ranger 就正常了。

floaterm 能否确认一下？

**Comment by voldikss** [comment]
修复了，感谢
