### ISSUE TITLE
rg terminal is not responsive when accidently suspended with ctrl+z / ^Z

### ISSUE THREAD

**Issue by balazser** [voldikss/vim-floaterm#346]
1. run any command using `rg`
2. press ctrl+z to suspend
3. interpreter is not responsive

### Actual behaviour
Terminal does not response

### Expected behaviour
Terminal responses

### Screenshots(Optional, GIF is better)
![image](https://user-images.githubusercontent.com/20303564/152991572-5f4085f4-16d1-4faf-b132-fec51db1255a.png)

**Comment by voldikss** [comment]
This seems a neovim terminal bug, it also occurs in `:terminal`
