### ISSUE TITLE
floaterm open gvim

### ISSUE THREAD

**Issue by jqhr** [voldikss/vim-floaterm#349]
### Environment
OS:
  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows
vim verison:
 8.2
terminal:
 gnome terminal, kitty, urxvt or alacritty

### Question
I use vim in terminal, but floaterm command open file with gvim, not current vim editor.
I find [here](https://github.com/voldikss/vim-floaterm/blob/6244d1739aad6682c6c1d5db18c846c342af6e3e/autoload/floaterm/edita/vim/client.vim#L25). That line use v:progpath, not v:progname.  For linux environment, the vim preinstalled not include clipboard feature, If I want that feature, I need to install gvim. By installed gvim, in terminal,  I see "v:progname" was "vim", and "v:progpath" was "/usr/bin/gvim". So, when I execute floaterm command, it opened an new gvim window, not current vim instance.
I change "v:progpath" to "v:progname", and it works.
I just wonder if there are any other solutions?

**Comment by Konfekt** [comment]
I have the same problem that at https://github.com/voldikss/vim-floaterm/blob/fe61226f8990bb4d36fa274fdc5f6079535cedeb/autoload/floaterm/edita/vim/client.vim#L3 v:progpath is always set to `gvim`, opening a new gvim instance. @jqhr would you mind sharing how you solved it? @voldikss, would you consider a check for v:progname differing and opting for `exepath(v:progname)`?
