### ISSUE TITLE
Invalid link?

### ISSUE THREAD

**Issue by rodhash** [voldikss/vim-floaterm#358]
Hello,

I really wanted to add a second command to run after FloatermNew finishes, but it seems impossible and also found it described in the readme:

> Note that <bar>(i.e., |) will be seen as an argument of the command, therefore it can not be followed by another Vim command.

So is it really impossible?

For instance:

1. Runs Floatermnew
2. Once it finishes, run something else like `:source`

And while reading the help for this plugin (`:h FloatermNew`) I guess I found an invalid link:

This link doesn't exist:
https://github.com/voldikss/vim-floaterm/blob/ab7876f86c05c1935eb23a193f4f276132902ac1/doc/floaterm.txt#L319

Apparently it was changed to:
https://github.com/voldikss/vim-floaterm#use-with-command-line-tools

Should I raise a PR?

Thanks

**Comment by voldikss** [comment]
Oh I even forgot this, a PR is appreciated.

**Comment by voldikss** [comment]
closed by #359
