### ISSUE TITLE
zsh-autosuggestions work in floating window, but not in 'normal' mode / quickfix window

### ISSUE THREAD

**Issue by benwoodward** [voldikss/vim-floaterm#36]
Hopefully this is clear from the screenshots. When Floatterm is invoked with default `floaterm_type`, i.e. this global variable is not set, the terminal appears in a floating window, and suggestions from `zsh-autosuggestions` are visible. 
![image](https://user-images.githubusercontent.com/1472981/74093106-58e3e600-4b32-11ea-8e83-a5cfd117c48e.png)

However, if `g:floaterm_type` is set to `'normal'`, then they are not visible. 
![image](https://user-images.githubusercontent.com/1472981/74093110-6dc07980-4b32-11ea-95bb-343aa9ae32e3.png)

Another issue that is visible in these screenshots is that when the window type is set to `'normal'` then the colorscheme is inherited from whatever has been set in my `init.vim`. However, in floating window mode the colorscheme is something else. I can create a separate issue for this if not answered here. 

EDIT: Ideally I'd like a terminal in a fullscreen buffer with no borders that I can toggle with a shortcut. Is setting `g:floaterm_width`, and `g:floaterm_height` to `1` the best way to do that, or is there a better way? Do I even need this plugin to do that?

**Comment by voldikss** [comment]
> EDIT: Ideally I'd like a terminal in a fullscreen buffer with no borders that I can toggle with a shortcut. Is setting g:floaterm_width, and g:floaterm_height to 1 the best way to do that, or is there a better way? Do I even need this plugin to do that?

You can use`: terminal` directly.

**Comment by voldikss** [comment]
BTW, `g:floaterm_type` will be deprecated in the future. The wines l window type will be set to 'floating' by default. If floating window is not supported, or will fall back to 'normal'

**Comment by benwoodward** [comment]
Same issue when I use `:terminal`, so maybe it's not an issue with `vim-floaterm`? 



<img width="610" alt="Screen Shot 2020-02-09 at 12 24 40 pm" src="https://user-images.githubusercontent.com/1472981/74093611-35706980-4b39-11ea-810a-2eda51550f3a.png">

**Comment by voldikss** [comment]
> Same issue when I use :terminal, so maybe it's not an issue with vim-floaterm?

It might be caused by the theme of your terminal app. Auto-suggestion works on my laptop when I use `:terminal`

![Screenshot_20200209_085548](https://user-images.githubusercontent.com/20282795/74094312-4f4e8400-4b1a-11ea-9ab6-12c2ac6a32c8.png)

**Comment by benwoodward** [comment]
I'm putting it down to this issue: https://github.com/neovim/neovim/issues/7018

**Comment by benwoodward** [comment]
For anyone else with this issue, it's actually caused by iTerm color settings as described here: https://github.com/zsh-users/zsh-autosuggestions/issues/416#issuecomment-486516333
