### ISSUE TITLE
floaterm.cmd has wrong string not-equal comparison

### ISSUE THREAD

**Issue by yantongl** [voldikss/vim-floaterm#361]
### The problem

When running `floaterm <filename>` in the float term window, I saw this error message: `!= was unexpected at this time.`. After some digging, apparently in `floaterm.cmd`, the string not-equal comparison is incorrect. 

In the current version, the script is written as:
```cmd
IF "%NVIM_LISTEN_ADDRESS%" != "" GOTO neovim
IF "%NVIM%" != "" GOTO neovim
```

Based on my testing and [this page](https://stackoverflow.com/questions/1421441/batch-not-equal-inequality-operator), string not-equal comparison should be written as `IF NOT "something" == "something"` or `IF "something" NEQ "something"`. 

### My Environment

Neovim 0.7.0
  - [ ] Linux
  - [ ] Mac OS X
  - [X] Windows

my `:checkhealth floaterm` result:
```
floaterm: health#floaterm#check
========================================================================
## common
  - INFO: Platform: win
  - INFO: Nvim: NVIM v0.7.0
  - INFO: Plugin: 875c404

## terminal
  - OK: Terminal emulator is available

## floating
  - OK: Floating window is available
```

**Comment by voldikss** [comment]
Fixed, thanks.

**Comment by yantongl** [comment]
That's fast response! Thank you!
