### ISSUE TITLE
[Question] how to search or copy in floaterm shell , like in tmux vi mode?

### ISSUE THREAD

**Issue by WillDawnlll** [voldikss/vim-floaterm#362]
maybe get floaterm buffer and line number then copy?
not get any info about it after some google...

**Comment by WillDawnlll** [comment]
and in linux or wsl i got tmux , but in windows , i have to select text by mouse ...

**Comment by voldikss** [comment]
First back to the NORMAL mode using `<C-\><C-n>`, and then copy text as you do in the normal buffer.

**Comment by WillDawnlll** [comment]
thanks
