### ISSUE TITLE
How to change the default shell from cmd.exe to powershell?

### ISSUE THREAD

**Issue by SONIC-CODEZ** [voldikss/vim-floaterm#368]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 

  - [ ] Linux
  - [ ] Mac OS X
  - [x] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown

```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim

```

### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

**Comment by voldikss** [comment]
https://github.com/voldikss/vim-floaterm#gfloaterm_shell should satisfy you

**Comment by ykong1337** [comment]
if has('win64) || has('win32')
    let g:floaterm_shell='powershell'
endif
