### ISSUE TITLE
Hide/Toggle with same keybinding

### ISSUE THREAD

**Issue by QiangZiBro** [voldikss/vim-floaterm#375]
Hi, I would like to ask if there's a way to hide/toggle with the same keybinding, currently, I'm using:
```
	let g:floaterm_keymap_hide   = '<F9>'
	let g:floaterm_keymap_toggle = '<F12>'
```
What if we just use `<F12>` to do two things (first toggle then hide)? And it would be nice if such instruction appeared in README. Thank you!

**Comment by voldikss** [comment]
Sorry but I couldn't get the point. <F12> should cover the both cases: toggle to show and toggle to hide, doesn't it?

**Comment by QiangZiBro** [comment]
Just checked and it worked, thank you for the great project!
