### ISSUE TITLE
E492: Not an editor command: tcd /home/jerry

### ISSUE THREAD

**Issue by jerrywang1981** [voldikss/vim-floaterm#401]
### Before reporting

- Please make sure you have searched through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/issues?q=label%3AFAQ) first.

- Please make sure you are using the latest version of this plugin.

- It's better to use English as it's more friendly to other non-Chinese native users.

#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`: 
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 14 2022 02:52:30)
Garbage after option argument: "-version"
More info with: "vim -h"
```
- Platform: 

  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown

```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim

```

### Describe your question, feature request, or bug.
run command `:FloatermNew` and got message:
```
Error detected while processing function floaterm#run[7]..floaterm#new[36]..floaterm#terminal#open[22]..floaterm#path#chdir:

E492: Not an editor command: tcd /home/jerry
```
### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

### Screenshots(Optional, GIF is better)
![image](https://user-images.githubusercontent.com/8133242/230286242-6920f5df-2d40-4c4b-89f4-c8176e60a932.png)

**Comment by voldikss** [comment]
Closed by #401
