### ISSUE TITLE
在floaterm编译code，编译日志太长，怎么可以向上翻看编译日志，目前不知道怎么可以向上翻滚

### ISSUE THREAD

**Issue by longway1024** [voldikss/vim-floaterm#407]
#### If you are using vim(not neovim), fill in the following blanks
vim --9.0
- Output of `vim --version`:
- Platform: 

  - [√ ] Linux
  - [ ] Mac OS X
  - [ ] Windows

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim

```

### Steps to reproduce

Using the minimal vimrc

```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

### Actual behaviour
打开floaterm，然后在shell环境中编译代码，代码编译结束，想查看编译日志
### Expected behaviour
希望可以用鼠标滑轮或者其他方式向上翻滚查看日志

**Comment by voldikss** [comment]
* 方法一，回到 normal 模式（`CTRL-\` + `CTRL-N`），按照正常流程翻滚（CTRL-D 或 CTRL-U 或 j, k）

* 方法二，用鼠标滚轮（前提是设置了 `'mouse'` 选项，推荐 `set mouse=a`）

**Comment by longway1024** [comment]
鼠标有设置滚动的，但是在vim-floaterm里面还是无法滚动，最后执行了exit后才可以滚动，这个算不算是bug

**Comment by longway1024** [comment]
另外如果回到normal模式不是，term不就关闭了么，那样就看不到编译的日志了啊

**Comment by 1332927388** [comment]
实测，ctrl+\进入类似于vim中的normal模式，然后可以进行光标移动，然后按 i 返回正常模式（insert模式）
