### ISSUE TITLE
The wrapper for fzf crashes with fish

### ISSUE THREAD

**Issue by delphinus** [voldikss/vim-floaterm#41]
https://github.com/voldikss/vim-floaterm/blob/ce174b892a5b11b569a2e04757ab97a4fcf1feb4/autoload/floaterm/wrapper/fzf.vim#L8

Here it uses the (ba/z)sh command substitution `$(...)`. But fish cannot recognize because it uses `()`, so it crashes.

1. Change the syntax by `&shell` setting.
2. Use `bash` explicitly in executing the command if `send2shell` is truthy.

In my opinion, 2. is better for this.

**Comment by voldikss** [comment]
Thanks for this.

Might support `FloatermNew fzf` on Windows  in the future. So I prefer the first solution. 

> Change the syntax by &shell setting.

Should we use `if &shell ==# 'zsh' ... elseif &shell ==# 'fish' ...` ?

**Comment by delphinus** [comment]
In actual, a reliable way for detecting shells that have no `$(..)` syntax does not exist.

* sh shells (sh, bash, zsh, ...) → `$(fzf)`
* C shells (csh, tcsh, ...) → <code>&#x60;fzf&#x60;</code>
* fish → `(fzf)`
* and another syntax in another shells...?
* and Windows...?

In this case, the wrappers use bash only in UN*X and another way in Windows. This solves the problem with no side effects, don't you think?

**Comment by voldikss** [comment]
Ok that makes sense, I tried `%fzf%` on Windows this moring and failed. So I agree with you, it's better to use `sh/bash` explicitly.

**Comment by voldikss** [comment]
Wait, sorry I still think the first is better. Here are the reasons:
- Suppose I use `FloatermNew fzf` to open `fzf`, select and open a file. After that if I want to use that floaterm, I reopen it and find it stays on `sh/bash`, but what if I use `zsh` or `fish` as my default shell(see the screenshot demo)
- Most users use either `bash`,`zsh` or `fish`, so I think it's enough to cover these three shell(or `csh` also)

![issue](https://user-images.githubusercontent.com/20282795/75086409-ccdcb000-556e-11ea-9474-200e3e6dcaa8.png)

**Comment by voldikss** [comment]
Hmmm the code implementation of the first method is quite unelegant(I have to use `match()` function), so I use the second method eventually.

**Comment by delphinus** [comment]
> Suppose I use FloatermNew fzf to open fzf, select and open a file. After that if I want to use that floaterm, I reopen it and find it stays on sh/bash, but what if I use zsh or fish as my default shell(see the screenshot demo)

Indeed. This problem still exists after 68632fb. Should `FloatermNew fzf` close & wipe out the window at once after the file is opened? But is this realizable?

As an idea, I propose introducing options to `FloatermNew`.

```vim
" open with fzf, and use the same window after that.
FloatermNew fzf
" open with fzf, and it hides and wipes out the terminal.
" It is good to use this as the default.
FloatermNew -close fzf
```

> Most users use either bash,zsh or fish, so I think it's enough to cover these three shell(or csh also)

That is one way of it. Also fzf supports only bash, zsh, and fish.

**Comment by voldikss** [comment]
> Should FloatermNew fzf close & wipe out the window at once after the file is opened?

It requires lots of work to extend this. So I chosen the first of your suggestion. Use `stridx` to determine the shell and give different commands.
