### ISSUE TITLE
<S-Space> shows escape sequences

### ISSUE THREAD

**Issue by 9mm** [voldikss/vim-floaterm#418]
#### If you are using vim(not neovim), fill in the following blanks

- Output of `vim --version`:
- Platform: 13.5.2 (22G91)

  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows

#### If you are using neovim, just run `:checkhealth floaterm` and post the content
below.

```markdown
==============================================================================
floaterm: health#floaterm#check

common ~
- Platform: macos
- Nvim: NVIM v0.9.2
- Plugin: eeb3f6b


terminal ~
- OK Terminal emulator is available

floating ~
- OK Floating window is available
```

#### Configurations related to vim-floaterm in vimrc(i.e. `g:floaterm_xxx`):

```vim

```

### Describe your question, feature request, or bug.

When I type a word with <S-Space>, for example typing the phrase "SPLIT TEST" it will come out as `SPLIT;2uTEST`

### Steps to reproduce

Open a ZSH shell in floaterm, and type "SPLIT TEST"

### Expected behaviour

escape sequences should maybe have a setting or something? (I searched and couldnt find)

### Screenshots(Optional, GIF is better)

<img width="745" alt="image" src="https://github.com/voldikss/vim-floaterm/assets/1386207/4b36ebfd-9b58-4138-b97a-be68392e4932">

**Comment by voldikss** [comment]
What if typing <S-Space> outside of vim and floaterm?

**Comment by 9mm** [comment]
Hmm actually, that works but I didnt try testing in nvim rather than neovide (gui), and it appears to be from neovide, sorry

**Comment by 9mm** [comment]
Its actually a neovim bug: https://github.com/neovim/neovim/issues/24093
