### ISSUE TITLE
Add variable for minmum width and height

### ISSUE THREAD

**Issue by szsdk** [voldikss/vim-floaterm#49]
Do you think it would be a good idea to add some global variables to limit the minmum width and height of the floaterm? Because some times, the original vim is not that large. Set the floaterm size to some ratio to the parent vim size would make it too small for effective using.

PS: Thanks for bringing us this wonderful plugin.

**Comment by voldikss** [comment]
Hi there, 

Thanks for the suggestion. However, IMO this opinion is unnecessary. Using `g:floaterm_{width|height}_min` is convenient but less flexible. Besides, if we add `g:floaterm_{width|height}_min`, then `g:floaterm_{width|height}_max` is also required. Too many variables makes it complex and hard to use.

The size of a floaterm instance is not persistent during it's lifetime, so people can set `g:floaterm_{width|height}` to an absolute value manually before reopening an floaterm window if they want.

**Comment by szsdk** [comment]
Sure, I totally understand that balancing simplicity and flexibility is a tricky part of development.
Feel free to close this issue and I am going to get a bigger monitor.
