### ISSUE TITLE
Terminal buffer in a pop up window in vim 8

### ISSUE THREAD

**Issue by xulongwu4** [voldikss/vim-floaterm#50]
Do you have plans to support opening a terminal in a pop up window in vim 8? This will allow vim users to have similar experience to a floating terminal in neovim.

**Comment by voldikss** [comment]
I am not very familiar with popup in vim8, vim allows to open a terminal buffer in the popup, but it still has much behaviors different from nvim. So I don't have that plan in a short time.

But could I keep this issue opened? See if someone interested in that could draft a PR, or I would do it when I have spare time.

**Comment by voldikss** [comment]
Hi all, I jus drafted a PR for this feature. Welcome to have a test and give me some feedbacks :)

**Comment by wookayin** [comment]
Awesome, great job @voldikss! It seems that [8.2.191]+ is the minimum version supported (not 8.1.1522). On earlier versions one will run into an error `Cannot put a terminal buffer in a popup window`.

[8.2.191]: https://github.com/vim/vim/commit/219c7d063823498be22aae46dd024d77b5fb2a58

**Comment by voldikss** [comment]
Thank you @wookayin . I've fixed this. In addition, util [8.2.0286](https://github.com/vim/vim/commit/11ec807639ae642bf55da883918489e2cd9911ab) can `popup_close()` be used in a popup terminal, so I changed that accordingly.
