### ISSUE TITLE
Make startinsert optional

### ISSUE THREAD

**Issue by panders23** [voldikss/vim-floaterm#51]
Hi,

currently `startinsert` is executed on every `:FloatermToggle` and terminal switching via `:FloatermNext` or `:FloatermPrev`. I recommend to add a configuration flag the way neoterm did, like `g:floaterm_autoinsert = 0` (default := 1).

**Comment by voldikss** [comment]
Hi there,

Thanks for the suggestion. Acutally I have balanced that and finnally not used that option.
However, I might consider it since it was came up with again. Could you describe the use case? When should we use `let g:floaterm_autoinsert = 0`?

**Comment by panders23** [comment]
No particular scripting use case. I just prefer from a vim useage/feeling standpoint that normal mode should be default state of every buffer. Come to think about it, with my current settings I need leave terminal mode before `:FloatermNext`/Prev actually works. In the other scenario I can use Next/Prev "to switch between previews" and go into insert-mode to use the current terminal session or just watch a `tail - f` w/o needing to go into insert and just use normal mode i'm in for search and yank.

**Comment by panders23** [comment]
Thank you 😊
