### ISSUE TITLE
Not starting insert mode with tnoremap

### ISSUE THREAD

**Issue by delphinus** [voldikss/vim-floaterm#52]
I noticed a slight issue while reading #51. I intended to use `FloatermNew` from terminals with this vimrc below.

```vim
nnoremap <A-n> <Cmd>FloatermNew<CR>
tnoremap <A-n> <Cmd>FloatermNew<CR>
```

The `nnoremap <A-n>` does good. It starts a terminal with the insert mode. But with `tnoremap <A-n>`, it does not start the insert mode.

[![asciicast](https://asciinema.org/a/305098.svg)](https://asciinema.org/a/305098)

For the present, this code below solves the problem. Just FYI.

```vim
nnoremap <A-n> <Cmd>FloatermNew<CR>
tnoremap <A-n> <Cmd>FloatermNew<CR><Cmd>startinsert<CR>
```

**Comment by voldikss** [comment]
> The nnoremap <A-n> does good. It starts a terminal with the insert mode. But with tnoremap <A-n>, it does not start the insert mode.

I can reproduce this issue. However I confirmed this line was executed.
https://github.com/voldikss/vim-floaterm/blob/6ad37b29a9f8093f317c9e110f6fddea800f75da/autoload/floaterm/terminal.vim#L32

I am not sure whether it's a bug or an expected behavior of `<Cmd>` in terminal mode.

**Comment by ssl19** [comment]
":startinsert is ineffective in vim8 's Terminal-Normal mode."
Referres to this
https://vimhelp.org/terminal.txt.html#Terminal-mode

**Comment by voldikss** [comment]
Fixed. Thanks @ssl19 .

**Comment by voldikss** [comment]
Hi @delphinus 
This bug got fixed in neovim!

See https://github.com/neovim/neovim/issues/12246
