### ISSUE TITLE
[Feature Request] Enable to split before editing

### ISSUE THREAD

**Issue by delphinus** [voldikss/vim-floaterm#53]
`nvr` command accepts `-cc {command}` to execute before evaluating. I want to set `-cc split` for `floaterm` command and start editing with splitting windows.

1. Accept `-cc` itself.
   * `floaterm -cc split /path/to/file`
2. Add option for `nvr`.
   * `let g:floaterm_nvr_option = '-cc split'`

How do you feel about this?

**Comment by voldikss** [comment]
Thanks, this option should be added. But IMO it shouldn't be subject to `nvr` according to the following reasons:
- Compatibility with Vim is required. Vim, instead, doesn't have `-cc` option.
- The functionality you mentioned is used  not only with `nvr`(e.g. `floaterm somefile.txt`), but also with `termopen/term_start`'s callback function.(see [line 19](https://github.com/voldikss/vim-floaterm/blob/6ad37b29a9f8093f317c9e110f6fddea800f75da/autoload/floaterm/wrapper/ranger.vim#L19) of `wrapper/ranger.vim`)

As such, I prefer adding an option whose value can be one of `'edit', 'split', 'vsplit', 'tabe', 'drop'`. It's pretty easy to implement though. But it requires a name which I am being entangled with. 

`g:floaterm_openfile_option`, `g:floaterm_openfile_command`, `g:floaterm_open_option`, `g:floaterm_open_command`, which is better? Or could you please help me with that? :cry:

**Comment by delphinus** [comment]
I think `g:floaterm_open_command` is better. First, the candidates (`:split`, etc) are the commands themselves. And second, they can be used with something other than files in the future. For example, URI to fetch its contents.

**Comment by voldikss** [comment]
Thanks, this option was added.
