### ISSUE TITLE
Ability to change the size of "current" term windows

### ISSUE THREAD

**Issue by DanCardin** [voldikss/vim-floaterm#57]
(preword, great plugin, thanks!)

I find it generally much quicker to run e.g. tests or related one-off type actions in a floatterm. This is usually fine. but sometimes the output becomes very large or long and it would be preferable to expand the existing term window to make it easier to look in.

My initial thought would be an API (which I could assign some terminal mapping to) which allowed me to "zoom into" or resize the existing term floating window to (fullsize in my case) temporarily whilst i sleuth.

Thoughts?

**Comment by voldikss** [comment]
Thanks, I will add this feature when neovim's floatwin supports border natively. https://github.com/neovim/neovim/issues/9718

**Comment by vn-ki** [comment]
This is now possible by doing

```
let b:window_opts = {'height': 0.2, width: 0.2}
```
inside the floaterm and then toggling it twice.

Maybe we should add a specific command to do this? @voldikss

**Comment by vn-ki** [comment]
> Maybe we should add a specific command to do this?

Can I open a PR for this @voldikss ?

**Comment by voldikss** [comment]
@vn-ki That would be so nice. :+1:

**Comment by voldikss** [comment]
> Maybe we should add a specific command to do this? @voldikss

Okay, maybe a `FloatermResize` like command?

**Comment by vn-ki** [comment]
I was think `FloatermChangeWindowOpts` or something like that. That way we can change whatever we want.

I was also thinking of adding position to `window_opts` (if you will allow).

**Comment by DanCardin** [comment]
Thanks!

I'm not super familiar with how vimscript variable/scoping works. Any chance you'd know the canonical way to write a function which contains the variable scope to implement a toggle action on a single mapping?

**Comment by vn-ki** [comment]
There's a new command

```
:FloatermUpdate height=0.9 width=1.0
```

**Comment by DanCardin** [comment]
Right, but in order to implement a toggle, i would need to know whether I'm going to 1.0 size, or back to default.

**Comment by vn-ki** [comment]
Toggling sizes won't be possible with the public API atm. It is indeed possible with the private API (i.e. floaterm internals), but it may break with future updates.

**Comment by haykh** [comment]
i have been using the following config for my setup:
```vimscript
tnoremap <Leader>f+ <cmd>FloatermUpdate --height=0.55<cr>
tnoremap <Leader>f- <cmd>FloatermUpdate --height=g:floaterm_height<cr>
```
would of course have been nicer to be able to have something like this:
```vimscript
tnoremap <Leader>f+ <cmd>FloatermUpdate --height=[CURRENT_WIDTH] * 1.1<cr>
tnoremap <Leader>f- <cmd>FloatermUpdate --height=[CURRENT_WIDTH] / 1.1<cr>
```
if there were a way to get the current window width. i will think about what would be the best approach. does `nvim` currently allow to capture the size of the current screen? for the toggle thing i think one might just have a global variable which would be switched, and the an if statement.

**Comment by ooloth** [comment]
Agreed toggling support would be helpful. As a workaround, you can track of the current height of your terminals using a local variable.

Lua/Lazy example (adapt however you like):

```lua
local state = {
  scratch = { -- a terminal name
    height = {
      current = '0.3', 
      default = '0.3',
      max = '1.0',
    },
  },
}

local function toggle_maximized(name)
  local height = state[name].height
  local new_height = height.current == height.max and height.default or height.max -- 'max' <-> 'default'

  vim.cmd.FloatermUpdate('--height=' .. new_height) -- resize terminal
  state[name].height.current = new_height -- cache new height
end

return {
  'voldikss/vim-floaterm',
  keys = {
    -- a terminal-mode keymap that calls your function with your terminal name
    { '<c-z>', mode = 't', function() toggle_maximized('scratch') end, desc = 'Toggle maximized terminal' }
  }
  -- other setup
}
```
