### ISSUE TITLE
lf wrapper deletes previous buffer from list.

### ISSUE THREAD

**Issue by benwoodward** [voldikss/vim-floaterm#59]
I think this is the same for all the wrappers.. 

```
  if filereadable(tmp_file)
    bd!
    let file_data = readfile(tmp_file)
    execute delete(tmp_file)
  else
    return
  endif
```

The buffer is deleted on [line 32](https://github.com/voldikss/vim-floaterm/blob/a56c57bba169212532a2828f070721655a1e8480/autoload/floaterm/wrapper/lf.vim#L32). This destroys the floating window but destroys the buffer from the list as well. 

If I remove this line, the floating window is not destroyed upon pressing `q` to quit `lf`. 

Not sure how to destroy the floating window, and it's terminal without destroying the buffer it was initialised from?

**Comment by voldikss** [comment]
I think it's better to implement lf and fff's wrappers according to that of ranger wrapper [here](https://github.com/voldikss/vim-floaterm/blob/2834432eca40748d09f173edaf646fcb70cd70f2/autoload/floaterm/wrapper/ranger.vim#L16)

**Comment by benwoodward** [comment]
Oh, thanks for fixing that. Works perfectly. 👌🏻
