### ISSUE TITLE
Send Esc sequence to terminal

### ISSUE THREAD

**Issue by jan-xyz** [voldikss/vim-floaterm#60]
It seems impossible to send `Esc` or any other control characters to the terminal. If I run something like `git commit` in the terminal, it opens another vim instance to write the commit and there is no way for me to close them vim instance since the terminal never receives the `Esc` command. Is there a way to still send it?

**Comment by voldikss** [comment]
Now this plugin supports open gitcommit file in the outside nvim instance.

**Comment by voldikss** [comment]
> there is no way for me to close them vim instance since the terminal never receives the Esc command

You might have mapped `<ESC>` to other keys, `tnoremap <Esc> <C-\><C-n>`

**Comment by jan-xyz** [comment]
Thanks! That was quick and it works :)
