### ISSUE TITLE
Feature request, show the current term index and total term count when floating window

### ISSUE THREAD

**Issue by leoatchina** [voldikss/vim-floaterm#61]
Here, add idx/cnt on the border
![image](https://user-images.githubusercontent.com/4470821/76719002-6749a100-6773-11ea-95d1-ba9317d7f8a0.png)

like I config in lightline
![image](https://user-images.githubusercontent.com/4470821/76719027-85af9c80-6773-11ea-93d5-53a9f6d528cb.png)
```
    function! FloatermStatus()
        if get(g:, 'floaterm_type', '') != ''
            let lst = floaterm#buflist#gather()
            let cnt = len(lst)
            let idx = index(lst, floaterm#buflist#find_curr()) + 1
            return 'FT:' . idx . "/" . cnt
        else
            return ''
        endif
    endfunction


```

**Comment by voldikss** [comment]
Thank you for this.

However, in my opinion this feature is necessary since you have already made the function `FloatermStatus()`. I could have added `g:floaterm_count` and `g:floaterm_index`, but it's very ugly to implement that. 

Furthermore, I don't think the "floaterm index" makes a lot of sense though "floaterm count" will be useful sometimes.

What's your opinion?

**Comment by leoatchina** [comment]
Do you mean unnecssary ?
This feature hist one time I had opened lots of floaterms and I wanted to know the idx/cnt of the float terms I had opend, but lightline only works when the cursor in the normal windows, so I had to toggle floaterm to make lightline shown.
According to my custom, if I opend terms, I will keep at what index each job run, so I can swith to it by `Prev/Next`.

althrough I can use vim-clap or coc to browser the terms, but my major fuzzy finder  is leaderf and there is no subcommd for it to browser floaterms

**Comment by voldikss** [comment]
> Do you mean unnecssary ?

Yes, because you have already had `FloatermStatus()` function.

Does the `FloatermStatus()` function works normally?

**Comment by leoatchina** [comment]
Thankup for reply

**Comment by adelarsq** [comment]
There is a change on the `floaterm_type` to `floaterm_wintype`. So use like this:

    function! FloatermStatus()
        if get(g:, 'floaterm_wintype', '') != ''
            let lst = floaterm#buflist#gather()
            let cnt = len(lst)
            let idx = index(lst, floaterm#buflist#find_curr()) + 1
            return 'FT:' . idx . "/" . cnt
        else
            return ''
        endif
    endfunction
