### ISSUE TITLE
Ability to add custom open_actions per key-map for lf

### ISSUE THREAD

**Issue by khalidchawtany** [voldikss/vim-floaterm#63]
I cannot figure a way to have different mappings to trigger different open_actions.
For example, I want to map `<c-t>` to open current active file in  a new tab and map `<c-s>` to open it in a split so on.

**Comment by voldikss** [comment]
Sorry but this feature is unachievable since you must send `<CR>` to `lf` in the terminal. We can not map multiple keys to one action in this case.

**Comment by khalidchawtany** [comment]
The following hack works for me:

```vim
au filetype floaterm call SetFloatermMappings()

function! SetFloatermMappings()
     tnoremap <buffer> <c-t> <cmd>let g:floaterm_open_command = 'tabedit' \| call feedkeys("l", "i")<cr>
     tnoremap <buffer> <c-o> <cmd>let g:floaterm_open_command = 'edit'    \| call feedkeys("l", "i")<CR>
     tnoremap <buffer> <cr>  <cmd>let g:floaterm_open_command = 'edit'    \| call feedkeys("l", "i")<CR>
     tnoremap <buffer> <c-v> <cmd>let g:floaterm_open_command = 'vsplit'  \| call feedkeys("l", "i")<CR>
     tnoremap <buffer> <c-s> <cmd>let g:floaterm_open_command = 'splqit'  \| call feedkeys("l", "i")<CR>
endfunction


```

**Comment by voldikss** [comment]
Hmmm, it's really hacky. Anyway, for personal use it's totally OK and helpful though it will change the `g:floaterm_open_command` option.

**Comment by khalidchawtany** [comment]
>though it will change the g:floaterm_open_command option

Unfortunately :(

**Comment by jkroes** [comment]
@khalidchawtany's solution may be hacky, but it's perfect for the ranger wrapper script provided by floaterm. If you use that, you can place this in your init.vim:
```
autocmd VimEnter * let g:floaterm_open_command_copy = g:floaterm_open_command
```
Then add the following line to the end of s:ranger_callback() in  autoload/floaterm/wrapper/ranger.vim:
```
let g:floaterm_open_command = g:floaterm_open_command_copy
```
That way, you don't have to worry about the bindings altering the global variable permanently, and you can use the bindings to open files from ranger in splits or new tabs.

**Comment by voldikss** [comment]
Mark this issue as per https://github.com/voldikss/vim-floaterm/issues/250#issuecomment-777976652

**Comment by JohanChane** [comment]
> The following hack works for me:
> 
> ```viml
> au filetype floaterm call SetFloatermMappings()
> 
> function! SetFloatermMappings()
>      tnoremap <buffer> <c-t> <cmd>let g:floaterm_open_command = 'tabedit' \| call feedkeys("l", "i")<cr>
>      tnoremap <buffer> <c-o> <cmd>let g:floaterm_open_command = 'edit'    \| call feedkeys("l", "i")<CR>
>      tnoremap <buffer> <c-v> <cmd>let g:floaterm_open_command = 'vsplit'  \| call feedkeys("l", "i")<CR>
>      tnoremap <buffer> <c-s> <cmd>let g:floaterm_open_command = 'splqit'  \| call feedkeys("l", "i")<CR>
> endfunction
> ```

I tried it, but didn't work. So I read the source, I found:
```vim
function! s:on_floaterm_close(bufnr, callback, job, data, ...) abort
  let opener = floaterm#config#get(bufnr, 'opener')
    call a:callback(a:job, a:data, 'exit', opener)
endfunction

function! floaterm#config#get(bufnr, key, ...) abort
  let key = 'floaterm_' . a:key
  let val = getbufvar(a:bufnr, key)
  if val == '' && a:0 == 1
    return a:1
  endif
  return val
endfunction
```
So We should change the buf varibale. It works for me (ranger).

VimL:

```vim
      au filetype floaterm call SetFloatermMappings()

      function! SetFloatermMappings()
           tnoremap <buffer> <C-t> <Cmd>let b:floaterm_opener = "tabedit" \| call feedkeys("l", "i")<CR>
           tnoremap <buffer> <C-o> <Cmd>let b:floaterm_opener = "edit" \| call feedkeys("l", "i")<CR>
           tnoremap <buffer> <C-v> <Cmd>let b:floaterm_opener = "vsplit" \| call feedkeys("l", "i")<CR>
           tnoremap <buffer> <C-s> <Cmd>let b:floaterm_opener = "split" \| call feedkeys("l", "i")<CR>
      endfunction
```

Lua:

```lua
      local set_floaterm_mappings = function()
        local mappings = {
          tabedit = "<C-t>",
          edit    = "<C-o>",
          vsplit  = "<C-v>",
          split   = "<C-s>",
        }
        for opener, key in pairs(mappings) do
          vim.keymap.set(
            "t",
            key,
            function()
              vim.b.floaterm_opener = opener
              vim.api.nvim_feedkeys("l", "i", "false")
            end,
            { noremap = true, buffer = true }
          )
        end
      end

      vim.api.nvim_create_autocmd("filetype", {
        pattern = "floaterm",
        callback = function()
          set_floaterm_mappings()
        end,
      })

```

**Comment by jackielii** [comment]
I've got something more robust:

```vim
nnoremap <leader>f :FloatermNew lf -command "map o open"<CR>
au filetype floaterm call SetFloatermMappings()
function! SetFloatermMappings()
  tnoremap <buffer> <Esc> <Cmd>FloatermKill<CR>
  tnoremap <buffer> <CR>  <Cmd>let b:floaterm_opener = "edit"    \| call feedkeys("o", "i")<CR>
  tnoremap <buffer> <C-t> <Cmd>let b:floaterm_opener = "tabedit" \| call feedkeys("o", "i")<CR>
  tnoremap <buffer> <C-v> <Cmd>let b:floaterm_opener = "vsplit"  \| call feedkeys("o", "i")<CR>
  tnoremap <buffer> <C-s> <Cmd>let b:floaterm_opener = "split"   \| call feedkeys("o", "i")<CR>
endfunction
```
