### ISSUE TITLE
Empty box still remain when move floaterm using wincmd

### ISSUE THREAD

**Issue by lkhphuc** [voldikss/vim-floaterm#65]
An empty box still remains when I move the floaterm to a split using `wincmd J`.
<img width="838" alt="Screenshot 2020-03-29 at 15 56 35" src="https://user-images.githubusercontent.com/12573521/77852306-df817f00-71d5-11ea-9e03-5a502aac0e42.png">

**Comment by voldikss** [comment]
> I want to open **normal** floaterm in the vsplit window.

This only works in the no-floating window for now.
