### ISSUE TITLE
Two problems with nvr (floaterm CLI): GIT_EDITOR, floaterm#util#open

### ISSUE THREAD

**Issue by wookayin** [voldikss/vim-floaterm#68]
Hi, I appreciate this plugin again. I would like to discuss two problems I found about the `floaterm` CLI which calls `neovim-remote` (nvr).

### 1. Please don't set GIT_EDITOR

The plugin overrides `$GIT_EDITOR` when floaterm is autoloaded (#60). I don't want it as I already have my own `$GIT_EDITOR` config in vimrc, so it should be configurable (using some `g:` variables). Well, I suggest this behavior should be turned off by default and users may want to explicit enable this feature, but either default might be fine.

### 2. `floaterm#util#open` just does not work

Even if I have `$GIT_EDITOR = 'floaterm'`, it doesn't work as expected. What the `floaterm` CLI does is just call neovim remote (or `nvr`) with: `--remote-expr "floaterm#util#edit('$name')`

But this function behaves weird. By default it simply hides the floaterm window and runs `:edit`. It closes the floating window --- why? Is it intended? 

I am running `nvr` commands from floating terminals and non-floating terminals (e.g. split and vsplit then `:term`), so what I expected is opening a new floating terminal as the name of function suggests.

**Comment by voldikss** [comment]
> ### 1. Please don't set GIT_EDITOR
> The plugin overrides `$GIT_EDITOR` when floaterm is autoloaded (#60). I don't want it as I already have my own `$GIT_EDITOR` config in vimrc, so it should be configurable (using some `g:` variables). Well, I suggest this behavior should be turned off by default and users may want to explicit enable this feature, but either default might be fine.

Thanks, I added `g:floaterm_gitcommit` option. Set it to `v:null` to disable this feature.

> 
> ### 2. `floaterm#util#open` just does not work
> Even if I have `$GIT_EDITOR = 'floaterm'`, it doesn't work as expected. What the `floaterm` CLI does is just call neovim remote (or `nvr`) with: `--remote-expr "floaterm#util#edit('$name')`

Fixed.

> But this function behaves weird. By default it simply hides the floaterm window and runs `:edit`. It closes the floating window --- why? Is it intended?

I've made some available values for `g:floaterm_gitcommit`.  Now we can choose whether to close the floating window.
