### ISSUE TITLE
Ability to open normal or floating floaterms

### ISSUE THREAD

**Issue by vn-ki** [voldikss/vim-floaterm#70]
Ability to open normal or floating floaterms on demand. Adding to this, ability to control the size of the terms as well.

In context of this feature request and #69, I think the current API of opening terms is wrong. I think an API similar to fzf where there are calls to open terminals would be more suitable for this plugin.

**Comment by voldikss** [comment]
Hi there,

thanks for the feature request.

This feature does have more high customablility. However, since this requires a lot of refactoring work, I didn't consider to implement this for now.

**Comment by vn-ki** [comment]
Will you accept a PR if I implement it?

**Comment by voldikss** [comment]
Hmmm, I am not sure about that, but is it easy for you to implement ?

I am not sure what's the workflow for this plugin after implementing this.

**Comment by voldikss** [comment]
BTW, will the new implemention break up other parts of this plugin?

**Comment by vn-ki** [comment]
> is it easy for you to implement ?

I don't know. I havent looked yet.

> I am not sure what's the workflow for this plugin after implementing this.

My major gripe with the plugin is that there is no real control over it. The control is really barebones. I want to improve that first. Then comes ability to spawn different size floaterm and then ability to name floaterms. Normal/Floating switch would come last.

> BTW, will the new implemention break up other parts of this plugin?

Ideally the current public API would be untouched.

**Comment by voldikss** [comment]
So kind of you. If you have spare time.

**Comment by vn-ki** [comment]
I don't have too much spare time, but it's the least I can do. This plugin has been so useful to me. That being said, I'm not very familiar with viml. So the PR might take some time to arrive.

**Comment by voldikss** [comment]
Take your time. Tell me if there are any problem about viml.
