### ISSUE TITLE
Border window on nvim is sometimes not closed

### ISSUE THREAD

**Issue by vn-ki** [voldikss/vim-floaterm#74]
![image](https://user-images.githubusercontent.com/31964688/78473651-fa1ca080-775f-11ea-9cd5-bbe4f2b8d02b.png)

Steps:

1. `FloatermNew height=0.3 width=0.4 name='1'`
2. `FloatermNew height=0.3 width=0.4 name='2'`
3. `FloatermToggle 1`
4. Without toggling 1, select another window.
5. `FloatermToggle 2`
6. Now toggle both 1 and 2.
7. Border window remains

I do not understand enough about the code base to debug this.

**Comment by voldikss** [comment]
![Peek 2020-04-05 20-02](https://user-images.githubusercontent.com/20282795/78481609-715e2e80-7778-11ea-96fb-e6b1bd57f06e.gif)

**Comment by voldikss** [comment]
Sorry I can not understand entirely the steps. Can you use some phrase like "toggle on" or "toggle off"?(I am not a english native speaker).

**Comment by voldikss** [comment]
Not sure about what's wrong. But could you try the lastest commit 835de76? I think it might fix this issue.

**Comment by vn-ki** [comment]
Yes, that does fix it. But now there is a new problem,

https://asciinema.org/a/3RzRlDXS7ttou2fcY2fAPPdHS

As you can see, 2 disappears when I toggle 1. Intuitively both should be toggled independently IMO.

**Comment by voldikss** [comment]
> As you can see, 2 disappears when I toggle 1. Intuitively both should be toggled independently IMO.

Yes, it is expected. Because I feel that there must be only one floaterm instance displayed, otherwise it is difficult to manager.

**Comment by voldikss** [comment]
If the previous floaterm wasn't hidden, the next floaterm window will overlap the previous one(suppose both are floating window). When toggling the second floaterm off, the first still be there, which is always bothering.

**Comment by vn-ki** [comment]
Oh, that is quite sad. If I can fix it without too much complexity, will you accept it?

**Comment by voldikss** [comment]
Hmm yes

Vishnunarayan K I <notifications@github.com> 于 2020年4月5日周日 下午11:26写道：
