### ISSUE TITLE
Show errors when quitting Vim with floaterm's

### ISSUE THREAD

**Issue by delphinus** [voldikss/vim-floaterm#77]
## reproducing procedure

1. open (Neo)Vim
2. `:FloatermNew`
3. `<C-\><C-n>` to switch mode
4. `:qa`
5. show errors

   ```
   Error detected while processing function <SNR>27_on_floaterm_close:
   line    6:
   E516: No buffers were deleted: 2bdelete!⏎
   ```

## vimrc

```vim
set runtimepath-=~/.vim
set runtimepath+=~/test/vim-floaterm
```

[![asciicast](https://asciinema.org/a/317045.svg)](https://asciinema.org/a/317045)

**Comment by voldikss** [comment]
Thanks, the issue was fixed.
