### ISSUE TITLE
处理 function floaterm#toggle[26]..floaterm#curr[3]..floaterm#new[4]..floaterm#resolver#chdir 时发生错误:

### ISSUE THREAD

**Issue by fgheng** [voldikss/vim-floaterm#79]
你好，我在我的neovim中的一个tab中使用terminal命令打开一个终端之后，又想使用FloatermNew打开一个浮动终端，但是他却提示如下错误：
```viml
处理 function floaterm#toggle[26]..floaterm#curr[3]..floaterm#new[4]..floaterm#resolver#chdir 时发生错误:
```

**Comment by fgheng** [comment]
我知道这个错误了
![image](https://user-images.githubusercontent.com/50551377/78628249-310cc680-78c6-11ea-9547-1270142936d3.png)
应该是这个函数中没有添加判断路径错误的情况，如果我打开了一个终端，那么这个函数的参数会返回终端的路径，也就是类似`term://~//1333:/bin`这种，而这样的错误路径就会导致`cd`出错。

**Comment by fgheng** [comment]
![image](https://user-images.githubusercontent.com/50551377/78628702-85647600-78c7-11ea-81f8-76a4f85435cb.png)
我稍微加一个判断可以了，但是就是只能进入home目录下了。

**Comment by voldikss** [comment]
Fixed
