### ISSUE TITLE
lightline need to be pre-checked, or it shows error when no lightline

### ISSUE THREAD

**Issue by devilyouwei** [voldikss/vim-floaterm#80]
Error detected while processing function <SNR>110_on_floaterm_close:
line    7:
E117: Unknown function: lightline#update

**Comment by devilyouwei** [comment]
How to re-show the issue:
1. toggle open a terminal
2. input：exit
condition: no lightline (mine is airline)
Solution: add pre-check for linghtline#update or add airline support

**Comment by voldikss** [comment]
Thanks, fixed.
