### ISSUE TITLE
Opening with a command throws an error

### ISSUE THREAD

**Issue by Olical** [voldikss/vim-floaterm#81]
Hey, I think the commits from yesterday caused my workflow with floaterm to stop working. I have been using this command: `:FloatermNew lazygit; exit` which was working perfectly well for quite a while.

Now `:FloatermNew` works and drops me into a shell but if I provide any command as an argument it throws this error.

```
Error detected while processing function floaterm#new:
line   23:
E121: Undefined variable: name
E116: Invalid arguments for function floaterm#terminal#send
```

I'll roll back to an older commit for now, I hope this helps!

**Comment by voldikss** [comment]
Thanks, fixed.
