### ISSUE TITLE
How did you make it behaves like this?

### ISSUE THREAD

**Issue by BSDxxxx** [voldikss/vim-floaterm#84]
![](https://user-images.githubusercontent.com/20282795/74799912-de268200-530c-11ea-9831-d412a7700505.png)
 - Different color of border?
 - Auto-resize?

**Comment by voldikss** [comment]
> -Different color of border?

Set `FloatermBorderNF` manually before opening a new floaterm.

> Auto-resize?

I didn't handle this. Just start nvim and open a floaterm in which you start another nvim and open another floaterm and ...

**Comment by BSDxxxx** [comment]
> > -Different color of border?
> 
> Set `FloatermBorderNF` manually before opening a new floaterm.
> 
> > Auto-resize?
> 
> I didn't handle this. Just start nvim and open a floaterm in which you start another nvim and open another floaterm and ...

LOL, tks.

**Comment by BSDxxxx** [comment]
@voldikss 自动生成不同颜色的边框，以实现类似终端tags的功能，便于切换时区分终端，如何？

**Comment by voldikss** [comment]
应该可行，可以自己包装实现的。

**Comment by BSDxxxx** [comment]
@voldikss Yep, but this could be a fancy feature inside the plugin -0.0-

**Comment by voldikss** [comment]
Hmmm sorry but no plan for this "random border feature" now. Users can easily implement it by themselves.
