### ISSUE TITLE
can float_window support vim?

### ISSUE THREAD

**Issue by Freed-Wu** [voldikss/vim-floaterm#85]
vim 8.2.200 allow user open a terminal in the popup window, i know <https://skywind3000.github.io/images/p/quickui/terminal.png> had done.

it is an enhancement, thanks!

**Comment by voldikss** [comment]
Yes, vim popup terminal support has been marked in #50 .

**Comment by Freed-Wu** [comment]
good. let us close it and watch #50.

**Comment by voldikss** [comment]
Since the plan is recorded, I will close this issue.
