### ISSUE TITLE
Can it provide the function?

### ISSUE THREAD

**Issue by Freed-Wu** [voldikss/vim-floaterm#86]
in <https://github.com/sillybun/vim-repl>, user can define
```let g:repl_program = {
            \   'python': 'ipython',
            \   'default': 'zsh',
            \   'r': 'R',
            \   'lua': 'lua',
            \   'vim': 'vim -e',
            \   }
let g:repl_predefine_python = {
            \   'numpy': 'import numpy as np',
            \   'matplotlib': 'from matplotlib import pyplot as plt'
            \   }
```

then when user in python file, it will auto open python, and import predefind command.

can it provide the same function?

**Comment by voldikss** [comment]
IMO this feature should exists only in those plugins which are designed all for REPL.  This plugin is not a common plugin, that is to say it won't contains those specialized functionaties like "predefined commands".
