### ISSUE TITLE
E475: Invalid argument: term_api

### ISSUE THREAD

**Issue by abdalrahman-ali** [voldikss/vim-floaterm#91]
Error detected while processing function floaterm#run[3]..floaterm#new[18]..floaterm#terminal#open:
E475: Invalid argument: term_api

**To Reproduce**
1. Install the plugin
2. :FloatermNew

Output of :checkhealth
E492: Not an editor command: checkhealth

**Comment by voldikss** [comment]
Use the latest Vim, see #90

abdalrahman-ali <notifications@github.com> 于 2020年4月15日周三 下午7:39写道：

**Comment by voldikss** [comment]
Hi @abdalrahman-ali @conor-f, I've add a check for `term_api` support. I think this issue got fixed.
