### ISSUE TITLE
Send Vim Commands from within floatterm

### ISSUE THREAD

**Issue by LeelaPakanati** [voldikss/vim-floaterm#92]
Hi,

I really like using the floaterm but am unsure how I send vim commands from within the terminal. In other words, how do I send the ":FloatermToggle" command from within the floating terminal

**Comment by voldikss** [comment]
Use <C-\><C-n> to go to the normal mode. Then you can use that command

**Comment by delphinus** [comment]
> &lt;C-&gt;

I think it should be `<C-\><C-n>`?

**Comment by voldikss** [comment]
Yes @delphinus I've made a mistake above.
