### ISSUE TITLE
FloatermToggle will leave a [No Name] buffer when `g:floaterm_wintype` is `normal`

### ISSUE THREAD

**Issue by icefed** [voldikss/vim-floaterm#93]
Make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

**Describe the bug**
When I set `g:floaterm_wintype` to `normal`, use `:FloatermToggle` open a terminal, a `[No Name]` buffer created,  then use `:FloatermToggle` close terminal, `[No Name]` buffer still there and will create more when `:FloatermToggle` used.

**To Reproduce**
1. 
2. 
3. 
4. 

**Enviroment :**
 - OS [e.g. Arch Linux]: MacOS 10.15.3
 - Version [e.g. NVIM v0.5.0-fa9b057]:  NVIM v0.4.3
 - Checkhealth info [run `:checkhealth` and post the messages]: 

**Screenshots(Optional)**

![image](https://user-images.githubusercontent.com/3964419/79540723-3256a400-80bb-11ea-88aa-ce140ecfb0c6.png)

**Comment by voldikss** [comment]
Could this issue be reproduced with the minimal vimrc(see below)? 
```vim
set nocompatible
set hidden
set termguicolors
set runtimepath^=/path/to/vim-floaterm
filetype plugin indent on
syntax on
```

**Comment by icefed** [comment]
> Could this issue be reproduced with the minimal vimrc(see below)?
> 
> ```viml
> set nocompatible
> set hidden
> set termguicolors
> set runtimepath^=/path/to/vim-floaterm
> filetype plugin indent on
> syntax on
> ```

Yes, it happens.
![image](https://user-images.githubusercontent.com/3964419/79546311-caa55680-80c4-11ea-92e2-8125c3ce752a.png)

**Comment by voldikss** [comment]
Thanks. Just fixed this bug.
