### ISSUE TITLE
Is there a filetype for floating term?

### ISSUE THREAD

**Issue by ywpkwon** [voldikss/vim-floaterm#94]
Thanks for this convenient plugin!

There is a plugin called "vim-indent-guides", which shows indentation information. 
![image](https://user-images.githubusercontent.com/18429284/79629302-65ba2280-80fd-11ea-86c2-4cce3deaf71d.png)

Since users don't want to visualize indentation for `nerdtree`, `startify`, etc., the plugin provides setting like `let g:indent_guides_exclude_filetypes = ['help', 'nerdtree', 'startify']`.

In `Floaterm`, when using ranger, I want to disable the plugin.
![image](https://user-images.githubusercontent.com/18429284/79629318-9732ee00-80fd-11ea-9fe5-7aedc4c7d21c.png)

So, I'm wondering if the terminal window has some internal `filetype` value. I couldn't find it. Nevermind if there is no such thing. I found there is a workaround: https://github.com/nathanaelkane/vim-indent-guides/issues/140.

I'm just curious here.

**Comment by voldikss** [comment]
The file type is exactly `floaterm`.

Youngwook Paul Kwon <notifications@github.com> 于 2020年4月18日周六 下午1:51写道：

**Comment by ywpkwon** [comment]
Wow. haha. I  tried just `terminal`. Thanks.
