### ISSUE TITLE
Is there a way to know vim's servername?

### ISSUE THREAD

**Issue by ywpkwon** [voldikss/vim-floaterm#95]
When using neovim, `:echo v:servername` shows vim's servername (e.g., `/tmp/nvimJYqTHS/0`). 
If I run Floaterm from this (neo)vim, Is there a way to know the vim's servername from the the terminal?

If so, I think one can do many things like splitting windows for the parent vim or sending keys to the parent vim. Do you think if it is possible?

**Comment by voldikss** [comment]
> Is there a way to know the vim's servername from the the terminal?

You mean `$NVIM_LISTEN_ADDRESS`?

**Comment by ywpkwon** [comment]
Yes.

**Comment by ywpkwon** [comment]
Aha, you meant accessing with `$NVIM_LISTEN_ADDRESS` from the terminal? I thought you asked me back about what I meant. Yes, I checked it works. Thanks. Cool!
