### ISSUE TITLE
When open lazygit the width has abnormal filling

### ISSUE THREAD

**Issue by raphaer** [voldikss/vim-floaterm#96]
Make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

### Describe the bug
as title

### To Reproduce

- Use the minimal vimrc

  ```vim
  set nocompatible
  set hidden
  set termguicolors
  set runtimepath^=/path/to/vim-floaterm
  filetype plugin indent on
  syntax on
  ```

- Steps to reproduce the behavior:
  1.run this command
`nnoremap <silent> <Leader>gz :<C-u>FloatermNew height=0.7 width=0.8 lazygit<CR>
`

### Enviroment
 - OS [e.g. Arch Linux]: mac os 10.15.4
 - Version [e.g. NVIM v0.5.0-fa9b057]:NVIM v0.5.0-nightly
 - Checkhealth info [run `:checkhealth` and post the messages]:
```
health#floaterm#check
========================================================================
  - OK: Terminal feature is OK
  - OK: Floating window feature is OK
  - OK: nvr is OK
```
### Screenshots(Optional, GIF is better)
![image](https://user-images.githubusercontent.com/41671631/79634790-660afa00-819f-11ea-97c7-de0a0eced545.png)

**Comment by voldikss** [comment]
I'm using nvim-0.5.0-nightly on Arch linux, can not reproduce this issue.

P.S. Does this also exists in normal nvim `terminal` window which is opened using `:terminal`?

**Comment by raphaer** [comment]
Aha, thanks, i fixed it.

**Comment by lynndylanhurley** [comment]
@glepnir i'm having the same issue. what did you do to fix?

**Comment by glepnir** [comment]
@lynndylanhurley  Please check does this setting on your vimrc `sidescrolloff`
