### ISSUE TITLE
can it directly run a program in terminal?

### ISSUE THREAD

**Issue by Freed-Wu** [voldikss/vim-floaterm#98]
when i
```
call floaterm#new('mysql', {}, {'curwin':1})
```

or 

```
FloatermNew mysql
```

it will open a terminal then input mysql and type `<CR>`

![image](https://user-images.githubusercontent.com/32936898/79680108-9655a580-823e-11ea-89f7-182a29bb67db.png)

can it directly run a program in terminal? like `terminal mysql`

![image](https://user-images.githubusercontent.com/32936898/79680113-a1a8d100-823e-11ea-9241-aa94a6755cb1.png)

thanks!

**Comment by voldikss** [comment]
Now you can do that

**Comment by wookayin** [comment]
I think this should be the correct behavior akin to how `:terminal` works. Can we have the previous behavior back upon some configuration, options, or via other commands? This looks like a change to me.

**Comment by wookayin** [comment]
By default neovim terminals will have the terminal window unclosed after the process exiting, with some messages like `[Process exited 0]`. You can verify by `:term ls`.

However, the current behavior of floaterm is just have the floating window "immediately" closed, so the terminal window will be immediately lost.

**Comment by voldikss** [comment]
Thanks @wookayin for the suggestion! That indeed is thoughtless change.

 > However, the current behavior of floaterm is just have the floating window "immediately" closed, so the terminal window will be immediately lost.

That was cause by this line:
https://github.com/voldikss/vim-floaterm/blob/781fc75f99417a0eafb379b197cc35dbec7f2881/autoload/floaterm/terminal.vim#L47

I'm considering whether to remove it or not, or add an option to allow users to decide whether to delete the window once the job gets finished.

I come up with several ideas but havn't decided which to choose:

1. Just remove the line above. In this way, the messages like `[Process exited 0]` are reserved, but users need to one more step(type any key) to close the floating window.

2. Or add an option `g:floaterm_***` to 1. Users can decided whether to close floating window after finishing job by setting that option to `v:true` or `v:false`. But  I don't know how to name the option for now.

3. Revert the previous commit. But add an argument like `use_shell`(set to `v:true` by default) to `floaterm#new(cmd, winopts, jobopts)`. In this case, if users want to run programs directly, the only method is to use the API function, e.g., `call floaterm#new('mysql', {}, {}, v:false)`.
    ```diff
    - function! floaterm#new(cmd, winopts, jobopts) abort
    + function! floaterm#new(cmd, winopts, jobopts, use_shell) abort
    ```

Which one do you think is more reasonable? Please give me some advise if possible.

**Comment by voldikss** [comment]
Finally I think the second is the best solution. I've add an option `g:floaterm_autoclose`.

**Comment by wookayin** [comment]
Thanks @voldikss. I also agree that Option 2 is the best and most reasonable choice. For having the original behavior (i.e., sendkeys), I end up using implementing a custom command to sendkeys myself.

I would also need a configuration point so that one can run a floaterm window with a $SHELL running that would autoclose (only for the current one). This is similar to Option 3, but I don't think your original API proposal -- adding a new argument --- is a good idea. Maybe we can have it in `winopts` (but this is technically not a "window" opts)?

**Comment by wookayin** [comment]
Yeah, let's move our discussion to a separate issue (#100).
