### ISSUE TITLE
height, width and position doesn't work in normal wintype 

### ISSUE THREAD

**Issue by vn-ki** [voldikss/vim-floaterm#99]
Make sure you have looked through the [F.A.Q.](https://github.com/voldikss/vim-floaterm/#faq) first.

### Describe the bug

```
:FloatermNew width=0.3 height=0.2 wintype=normal position=right
```

produces a terminal with half split on the bottom

**Comment by vn-ki** [comment]
I suspect the following line is the problem.
https://github.com/voldikss/vim-floaterm/blob/554ab158e2a1103f0c22bd2133684eef6870de84/autoload/floaterm/window.vim#L182
Why is it there?

**Comment by voldikss** [comment]
Thx, fixed that.
